from synthnews.prompts.angles import Angle


ANGLES: list[Angle] = [
    {
        "id": "cl_001",
        "category": "breaking_crime",
        "angle": "Police investigate overnight shooting in residential neighborhood",
        "focus": "A fast-moving incident report centered on victims, suspects, witnesses, and neighborhood reaction.",
        "questions": [
            "What do police say happened and when?",
            "Are investigators searching for suspects or a motive?",
            "How are nearby residents reacting to the violence?",
        ],
    },
    {
        "id": "cl_002",
        "category": "breaking_crime",
        "angle": "Downtown stabbing raises renewed safety concerns",
        "focus": "An immediate public-safety story about a violent attack in a high-traffic area.",
        "questions": [
            "Did the suspect know the victim or appear to act randomly?",
            "What security footage or witness accounts exist?",
            "Are city leaders promising visible safety changes?",
        ],
    },
    {
        "id": "cl_003",
        "category": "breaking_crime",
        "angle": "Armed robbery spree leaves businesses on edge",
        "focus": "Multiple linked robberies prompt fear among shop owners and workers.",
        "questions": [
            "Do investigators believe the same group is responsible?",
            "What patterns connect the incidents?",
            "How are businesses changing security measures?",
        ],
    },
    {
        "id": "cl_004",
        "category": "breaking_crime",
        "angle": "Suspicious death investigation turns quiet block into active crime scene",
        "focus": "A local mystery story blending police updates, neighborhood tension, and forensic uncertainty.",
        "questions": [
            "What evidence has been confirmed by investigators?",
            "Have police ruled out foul play?",
            "How long might residents wait for answers?",
        ],
    },
    {
        "id": "cl_005",
        "category": "breaking_crime",
        "angle": "Carjacking trend spreads fear among commuters",
        "focus": "A crime pattern story tied to mobility, visibility, and public anxiety.",
        "questions": [
            "Where and when are incidents happening most often?",
            "Are the attacks opportunistic or organized?",
            "What are police urging drivers to do?",
        ],
    },
    {
        "id": "cl_006",
        "category": "breaking_crime",
        "angle": "Home invasion case rattles sense of security",
        "focus": "A story about crime at the most personal level: inside private homes.",
        "questions": [
            "Was the home specifically targeted?",
            "What details suggest planning versus randomness?",
            "How is the case affecting neighborhood behavior?",
        ],
    },
    {
        "id": "cl_007",
        "category": "breaking_crime",
        "angle": "Kidnapping or custody dispute leaves authorities racing against time",
        "focus": "A high-stakes case where legal and emotional realities may overlap.",
        "questions": [
            "Is this being treated as an abduction or family dispute?",
            "What legal custody arrangements are relevant?",
            "What clues are shaping the search effort?",
        ],
    },
    {
        "id": "cl_008",
        "category": "breaking_crime",
        "angle": "Human remains discovery opens long-running missing persons mystery",
        "focus": "A grim development with both forensic and emotional dimensions.",
        "questions": [
            "How was the scene discovered?",
            "What identification methods are being used?",
            "Could this resolve other open cases?",
        ],
    },
    {
        "id": "cl_009",
        "category": "property_crime",
        "angle": "Store owners say theft is becoming a cost of doing business",
        "focus": "A ground-level business and crime story about recurring losses and weak deterrence.",
        "questions": [
            "How large are the losses for merchants?",
            "Are repeat offenders a major factor?",
            "What policy or enforcement changes are business owners demanding?",
        ],
    },
    {
        "id": "cl_010",
        "category": "property_crime",
        "angle": "Copper theft, cargo theft, and infrastructure crime hit the real economy",
        "focus": "Crimes that disrupt utilities, construction, freight, and basic services.",
        "questions": [
            "What systems or industries are being targeted?",
            "How organized are these theft rings?",
            "What secondary economic damage follows the thefts?",
        ],
    },
    {
        "id": "cl_011",
        "category": "property_crime",
        "angle": "Vehicle theft ring exploits technology and weak points in modern security",
        "focus": "A hybrid crime-tech story about theft methods and law enforcement response.",
        "questions": [
            "What methods are thieves using to bypass protections?",
            "Is organized crime involved?",
            "How are manufacturers and police responding?",
        ],
    },
    {
        "id": "cl_012",
        "category": "fraud",
        "angle": "Elder fraud cases reveal how scammers weaponize trust",
        "focus": "A story about vulnerability, manipulation, and often limited financial recovery.",
        "questions": [
            "What tactics are scammers using most often?",
            "Why are older adults especially targeted?",
            "How successful are recovery and prosecution efforts?",
        ],
    },
    {
        "id": "cl_013",
        "category": "fraud",
        "angle": "Online marketplace scams blur the line between petty theft and organized fraud",
        "focus": "A consumer-facing look at how digital scams scale quickly.",
        "questions": [
            "Which platforms are most affected?",
            "Are scams local, national, or international?",
            "What protections are actually working for users?",
        ],
    },
    {
        "id": "cl_014",
        "category": "fraud",
        "angle": "Ponzi-style investment scheme collapses after months of promises",
        "focus": "A white-collar crime story driven by greed, trust, and institutional failure.",
        "questions": [
            "How long did the scheme operate?",
            "Who looked the other way or missed warning signs?",
            "How much money can victims realistically recover?",
        ],
    },
    {
        "id": "cl_015",
        "category": "cybercrime",
        "angle": "Ransomware attack cripples hospital, school, or city services",
        "focus": "A cybercrime story with immediate consequences in the physical world.",
        "questions": [
            "What systems were disrupted?",
            "Did officials pay, negotiate, or refuse?",
            "How long will recovery take and who bears the cost?",
        ],
    },
    {
        "id": "cl_016",
        "category": "cybercrime",
        "angle": "Massive identity theft case shows how ordinary people become digital victims",
        "focus": "A practical cybercrime piece centered on banks, victims, and investigators.",
        "questions": [
            "How was the data obtained?",
            "How many people may be affected?",
            "What can victims do to limit the damage?",
        ],
    },
    {
        "id": "cl_017",
        "category": "cybercrime",
        "angle": "Synthetic identities and deepfake evidence challenge investigators",
        "focus": "A modern crime story about deception, evidence, and authentication.",
        "questions": [
            "What role did AI-generated material play?",
            "How are investigators verifying what is real?",
            "Will courts treat this as a new category of evidentiary risk?",
        ],
    },
    {
        "id": "cl_018",
        "category": "drugs",
        "angle": "Major fentanyl bust highlights shifting drug supply networks",
        "focus": "A narcotics case tied to overdose deaths, trafficking, and public health.",
        "questions": [
            "Where did the drugs originate?",
            "How significant is the seizure in practical terms?",
            "Will authorities emphasize punishment, prevention, or both?",
        ],
    },
    {
        "id": "cl_019",
        "category": "drugs",
        "angle": "Open-air drug market becomes the center of neighborhood anger",
        "focus": "A public-order story mixing addiction, disorder, and enforcement frustration.",
        "questions": [
            "Why has the market persisted in that area?",
            "What are residents demanding from city officials?",
            "What happens when enforcement and treatment goals clash?",
        ],
    },
    {
        "id": "cl_020",
        "category": "gangs_and_organized_crime",
        "angle": "Gang retaliation cycle drives violence across a handful of blocks",
        "focus": "A concentrated violence story that is local in geography but large in impact.",
        "questions": [
            "What sequence of events sparked the latest violence?",
            "How are retaliation patterns tracked by police?",
            "What intervention efforts exist beyond arrests?",
        ],
    },
    {
        "id": "cl_021",
        "category": "gangs_and_organized_crime",
        "angle": "Organized retail theft network linked to wider criminal enterprise",
        "focus": "A story connecting visible theft to more sophisticated criminal logistics.",
        "questions": [
            "How are stolen goods being moved and resold?",
            "What distinguishes organized theft from opportunistic shoplifting?",
            "What charges could suspects ultimately face?",
        ],
    },
    {
        "id": "cl_022",
        "category": "gangs_and_organized_crime",
        "angle": "Money laundering operation hides in plain sight behind legitimate businesses",
        "focus": "A business-crime crossover about concealment, paperwork, and shadow finance.",
        "questions": [
            "What businesses were allegedly used as fronts?",
            "How did investigators detect suspicious patterns?",
            "How international or local is the laundering network?",
        ],
    },
    {
        "id": "cl_023",
        "category": "domestic_violence",
        "angle": "Domestic violence case raises questions about warning signs missed",
        "focus": "A deeply human and legally complex story about escalation and intervention failure.",
        "questions": [
            "Were prior police calls or protective orders involved?",
            "What support systems did the victim try to access?",
            "Could earlier intervention have changed the outcome?",
        ],
    },
    {
        "id": "cl_024",
        "category": "sexual_offenses",
        "angle": "Sexual assault investigation tests evidence, credibility, and public pressure",
        "focus": "A sensitive case where trauma, proof, and public narrative collide.",
        "questions": [
            "What evidence is central to the case?",
            "How are investigators handling survivor-sensitive procedures?",
            "How does publicity affect fairness for everyone involved?",
        ],
    },
    {
        "id": "cl_025",
        "category": "juvenile_justice",
        "angle": "Youth violence case ignites debate over punishment versus intervention",
        "focus": "A case that can be covered as individual wrongdoing or as a system failure upstream.",
        "questions": [
            "What role did schools, family systems, or social media play?",
            "Should the suspect be treated as a child or as an adult offender?",
            "What interventions might have prevented escalation?",
        ],
    },
    {
        "id": "cl_026",
        "category": "policing",
        "angle": "Police release body camera footage after controversial arrest",
        "focus": "A public-accountability story where video may clarify some facts but inflame other disputes.",
        "questions": [
            "What does the footage show clearly and what remains disputed?",
            "Why was the release delayed or expedited?",
            "How are officials explaining officer conduct?",
        ],
    },
    {
        "id": "cl_027",
        "category": "policing",
        "angle": "Use-of-force incident prompts protests and internal review",
        "focus": "A story about force, legitimacy, and the speed at which one incident becomes political.",
        "questions": [
            "What department policies are now under scrutiny?",
            "Who is conducting the review and how independent are they?",
            "What outcome are protesters demanding?",
        ],
    },
    {
        "id": "cl_028",
        "category": "policing",
        "angle": "Police staffing shortages change how departments answer calls",
        "focus": "A structural law-enforcement story about capacity rather than a single incident.",
        "questions": [
            "What calls now receive slower responses?",
            "Why are recruitment and retention proving so difficult?",
            "How does staffing affect public safety and officer behavior?",
        ],
    },
    {
        "id": "cl_029",
        "category": "policing",
        "angle": "Predictive policing and facial recognition face renewed scrutiny",
        "focus": "A technology-and-civil-liberties story about police tools expanding ahead of public trust.",
        "questions": [
            "What tools are agencies actually using?",
            "How are false positives or biased outcomes measured?",
            "What legal guardrails, if any, are in place?",
        ],
    },
    {
        "id": "cl_030",
        "category": "public_order",
        "angle": "Visible disorder on transit becomes a citywide political issue",
        "focus": "A quality-of-life story where fear, inconvenience, and governance all converge.",
        "questions": [
            "Are riders reacting to data, visibility, or both?",
            "What offenses or behaviors are most driving complaints?",
            "What enforcement model are transit officials choosing?",
        ],
    },
    {
        "id": "cl_031",
        "category": "public_order",
        "angle": "Encampments, public drug use, and trespassing blur the line between crime and crisis",
        "focus": "A difficult law-and-policy story where enforcement alone may be inadequate.",
        "questions": [
            "What problems are residents and businesses reporting?",
            "When do cities treat the issue as health, housing, or criminal law?",
            "What happens when these systems conflict?",
        ],
    },
    {
        "id": "cl_032",
        "category": "investigations",
        "angle": "Cold case reopened after new DNA or forensic lead",
        "focus": "A long-tail justice story driven by persistence, science, and memory.",
        "questions": [
            "What new evidence changed the case?",
            "Why did the investigation stall originally?",
            "What does reopening the case mean for surviving relatives?",
        ],
    },
    {
        "id": "cl_033",
        "category": "investigations",
        "angle": "Whistleblower tips trigger sweeping corruption inquiry",
        "focus": "An investigative accountability story involving documents, insiders, and institutional exposure.",
        "questions": [
            "What triggered the investigation?",
            "How credible and specific are the allegations?",
            "Which officials or agencies are most at risk?",
        ],
    },
    {
        "id": "cl_034",
        "category": "prosecution",
        "angle": "Prosecutors unveil major indictment and frame the stakes for the public",
        "focus": "A charging story about narrative, evidence, and prosecutorial strategy.",
        "questions": [
            "What are the central charges?",
            "Why did prosecutors decide to move now?",
            "How much of the case is already visible versus still sealed?",
        ],
    },
    {
        "id": "cl_035",
        "category": "prosecution",
        "angle": "Decision not to charge suspect fuels anger, relief, or confusion",
        "focus": "A story about prosecutorial discretion and contested thresholds for action.",
        "questions": [
            "What legal standard prevented charges?",
            "How are police, victims, or defense lawyers responding?",
            "What does the public misunderstand about charging decisions?",
        ],
    },
    {
        "id": "cl_036",
        "category": "prosecution",
        "angle": "High-profile defendant turns court filing into political theater",
        "focus": "A legal drama story where courtroom strategy doubles as public messaging.",
        "questions": [
            "What arguments are meant for the judge versus the public?",
            "How does publicity affect the case narrative?",
            "What risks come from litigating in both court and media?",
        ],
    },
    {
        "id": "cl_037",
        "category": "bail_and_pretrial",
        "angle": "Bail hearing becomes a flashpoint over fairness and danger",
        "focus": "A pretrial justice story where one hearing symbolizes bigger policy fights.",
        "questions": [
            "What facts are prosecutors using to argue risk?",
            "How is the defense framing liberty before trial?",
            "What larger debate does this case plug into?",
        ],
    },
    {
        "id": "cl_038",
        "category": "bail_and_pretrial",
        "angle": "Defendant held for months before trial exposes cost of delay",
        "focus": "A procedural justice story about what happens before guilt is established.",
        "questions": [
            "Why has the case moved so slowly?",
            "How has detention affected the defendant's life and case strategy?",
            "What does this reveal about pretrial practice more broadly?",
        ],
    },
    {
        "id": "cl_039",
        "category": "trial_drama",
        "angle": "Murder trial gripped by dueling narratives and forensic uncertainty",
        "focus": "A classic courtroom drama where the jury must choose between competing stories.",
        "questions": [
            "What evidence anchors each side's theory?",
            "How persuasive are expert witnesses proving to be?",
            "What legal rulings may shape the jury's view?",
        ],
    },
    {
        "id": "cl_040",
        "category": "trial_drama",
        "angle": "Jury selection reveals the politics and psychology of a major case",
        "focus": "A pretrial story about bias, publicity, and strategic exclusion.",
        "questions": [
            "What kinds of jurors are each side trying to avoid?",
            "How has publicity affected jury selection?",
            "Can a truly impartial panel still be found?",
        ],
    },
    {
        "id": "cl_041",
        "category": "trial_drama",
        "angle": "Witness credibility becomes the hinge point of the case",
        "focus": "A courtroom story built around trust, memory, motive, and contradiction.",
        "questions": [
            "What inconsistencies are being highlighted?",
            "How are prosecutors or defense lawyers rehabilitating damaged witnesses?",
            "What kind of testimony matters most to jurors?",
        ],
    },
    {
        "id": "cl_042",
        "category": "trial_drama",
        "angle": "Hung jury leaves explosive case unresolved",
        "focus": "A dramatic non-ending with major implications for victims, defendants, and prosecutors.",
        "questions": [
            "What appears to have divided jurors?",
            "Will prosecutors retry the case?",
            "How do families and the community respond to no verdict?",
        ],
    },
    {
        "id": "cl_043",
        "category": "sentencing",
        "angle": "Victim statements and judicial remarks define emotional sentencing hearing",
        "focus": "A human-centered story about punishment, closure, and public meaning.",
        "questions": [
            "What sentence did the judge impose and why?",
            "How did victims frame the harm done?",
            "Did the sentence satisfy public expectations or deepen division?",
        ],
    },
    {
        "id": "cl_044",
        "category": "sentencing",
        "angle": "Mandatory minimum sentence reignites debate over discretion",
        "focus": "A law-and-policy story about rigid punishment rules versus individualized justice.",
        "questions": [
            "Was the judge's hands tied by statute?",
            "Do prosecutors gain too much leverage from mandatory penalties?",
            "What reforms are supporters and critics proposing?",
        ],
    },
    {
        "id": "cl_045",
        "category": "appeals",
        "angle": "Conviction thrown into doubt on appeal over evidence or procedure",
        "focus": "A story showing how trial outcomes are not always final or stable.",
        "questions": [
            "What error did the appellate court identify?",
            "How serious was the procedural flaw?",
            "Will there be a retrial, plea deal, or dismissal?",
        ],
    },
    {
        "id": "cl_046",
        "category": "appeals",
        "angle": "Appellate judges weigh whether prosecutors crossed the line",
        "focus": "A legal ethics and fairness story centered on courtroom conduct.",
        "questions": [
            "What actions are alleged to have prejudiced the trial?",
            "How deferential are appeals courts to trial prosecutors?",
            "What precedent could this case set?",
        ],
    },
    {
        "id": "cl_047",
        "category": "wrongful_convictions",
        "angle": "Exoneration after decades in prison forces system-wide reckoning",
        "focus": "A powerful story about error, injustice, and delayed correction.",
        "questions": [
            "What caused the wrongful conviction?",
            "Why did it take so long to reverse?",
            "Who is being held accountable now?",
        ],
    },
    {
        "id": "cl_048",
        "category": "wrongful_convictions",
        "angle": "Old forensics and shaky witnesses come under renewed challenge",
        "focus": "A story about the fragility of certainty in criminal law.",
        "questions": [
            "Which evidence techniques are now disputed?",
            "How often are legacy convictions built on weak foundations?",
            "What review mechanisms exist for old cases?",
        ],
    },
    {
        "id": "cl_049",
        "category": "prisons_and_jails",
        "angle": "Violence inside jail raises questions about supervision and overcrowding",
        "focus": "A corrections story about what happens after conviction or detention.",
        "questions": [
            "What were the conditions inside the facility?",
            "Did staffing or overcrowding contribute to the violence?",
            "How are jail officials explaining the failure?",
        ],
    },
    {
        "id": "cl_050",
        "category": "prisons_and_jails",
        "angle": "Contraband phones, drugs, and weapons expose prison control gaps",
        "focus": "A story about the hidden economy inside correctional institutions.",
        "questions": [
            "How is contraband entering the facility?",
            "What role do gangs or corrupt staff play?",
            "What reforms are being proposed to tighten control?",
        ],
    },
    {
        "id": "cl_051",
        "category": "reentry",
        "angle": "Life after prison becomes a second test of the justice system",
        "focus": "A post-release story about housing, work, stigma, and recidivism risk.",
        "questions": [
            "What barriers do former inmates face immediately after release?",
            "Which support programs actually reduce repeat offending?",
            "How much does reentry success depend on public policy versus local employers?",
        ],
    },
    {
        "id": "cl_052",
        "category": "legal_system",
        "angle": "Court backlogs leave victims and defendants waiting for years",
        "focus": "A structural justice story about delay, legitimacy, and system stress.",
        "questions": [
            "How large is the backlog and what caused it?",
            "Who suffers most from the delays?",
            "What emergency measures are courts trying?",
        ],
    },
    {
        "id": "cl_053",
        "category": "legal_system",
        "angle": "Public defender crisis exposes unequal access to justice",
        "focus": "A fundamental fairness story about money, workload, and constitutional rights.",
        "questions": [
            "How severe are public defender caseloads?",
            "What does under-resourced defense look like in practice?",
            "Can courts function fairly under these conditions?",
        ],
    },
    {
        "id": "cl_054",
        "category": "legal_system",
        "angle": "Plea bargains dominate the system but remain poorly understood by the public",
        "focus": "A higher-level explanatory story about how most criminal cases really end.",
        "questions": [
            "Why do so few cases go to trial?",
            "How much pressure do defendants face to plead?",
            "Does efficiency come at the expense of truth or fairness?",
        ],
    },
    {
        "id": "cl_055",
        "category": "civil_rights",
        "angle": "Search and seizure fight tests how old rights apply to new technology",
        "focus": "A constitutional law story centered on phones, cars, tracking, and digital privacy.",
        "questions": [
            "What exactly did police search and under what authority?",
            "How are judges adapting old precedent to digital evidence?",
            "Could the ruling change everyday policing?",
        ],
    },
    {
        "id": "cl_056",
        "category": "civil_rights",
        "angle": "Mass surveillance tools face challenge from privacy advocates",
        "focus": "A legal-tech story about cameras, plate readers, geofencing, and state power.",
        "questions": [
            "What surveillance tools are under challenge?",
            "How much oversight exists over their use?",
            "When does public safety justification stop persuading judges?",
        ],
    },
    {
        "id": "cl_057",
        "category": "civil_rights",
        "angle": "Free speech case collides with threats, harassment, or extremist rhetoric",
        "focus": "A difficult law story where constitutional principle meets public fear.",
        "questions": [
            "Where do courts draw the line between protected speech and criminal conduct?",
            "How does online speech complicate enforcement?",
            "What precedent could broader audiences care about?",
        ],
    },
    {
        "id": "cl_058",
        "category": "government_corruption",
        "angle": "Elected official or agency leader indicted in corruption probe",
        "focus": "A power-and-accountability story that often becomes immediate political drama.",
        "questions": [
            "What is the alleged scheme?",
            "Who benefited and who enabled it?",
            "How are political allies and opponents reacting?",
        ],
    },
    {
        "id": "cl_059",
        "category": "government_corruption",
        "angle": "Bid-rigging and patronage case reveals how public money gets diverted",
        "focus": "A systems story about corruption beyond one scandalous personality.",
        "questions": [
            "What contracts or agencies are implicated?",
            "How long did the scheme allegedly operate?",
            "What safeguards failed along the way?",
        ],
    },
    {
        "id": "cl_060",
        "category": "white_collar_crime",
        "angle": "Corporate fraud case shows how huge harm can remain nearly invisible",
        "focus": "A business-law story about financial damage without street-level violence.",
        "questions": [
            "Who was harmed financially?",
            "What documents, audits, or insiders exposed the scheme?",
            "Why do white-collar cases often move so slowly?",
        ],
    },
    {
        "id": "cl_061",
        "category": "white_collar_crime",
        "angle": "Insider trading or market manipulation probe reaches elite circles",
        "focus": "A finance-and-law story about privilege, access, and complex evidence.",
        "questions": [
            "What allegedly nonpublic information was used?",
            "How are investigators tracing intent?",
            "Why do these cases matter beyond the people charged?",
        ],
    },
    {
        "id": "cl_062",
        "category": "immigration_and_border_law",
        "angle": "Border enforcement operation becomes a flashpoint over crime and authority",
        "focus": "A law-and-politics story where criminal law and administrative law intersect.",
        "questions": [
            "What conduct is alleged: trafficking, smuggling, unlawful entry, or something else?",
            "How are officials framing the enforcement action?",
            "What larger political argument does the case feed?",
        ],
    },
    {
        "id": "cl_063",
        "category": "immigration_and_border_law",
        "angle": "Human smuggling case exposes desperation, exploitation, and legal bottlenecks",
        "focus": "A cross-border crime story with humanitarian and prosecutorial dimensions.",
        "questions": [
            "How did the smuggling network operate?",
            "What risks did migrants face in transit?",
            "Will the case change policy or just produce headlines?",
        ],
    },
    {
        "id": "cl_064",
        "category": "legislation",
        "angle": "Tough-on-crime bill surges after high-profile incident",
        "focus": "A politics-of-law story about how fear and urgency shape statutes.",
        "questions": [
            "What event triggered legislative momentum?",
            "Will the bill materially change outcomes or mostly signal resolve?",
            "What unintended consequences do critics predict?",
        ],
    },
    {
        "id": "cl_065",
        "category": "legislation",
        "angle": "Reform package seeks to reduce incarceration and redirect low-level cases",
        "focus": "A competing lawmaking frame focused on decarceration, diversion, and system redesign.",
        "questions": [
            "What offenses or defendants would be affected?",
            "How do supporters define success?",
            "What attacks are opponents making against the reforms?",
        ],
    },
    {
        "id": "cl_066",
        "category": "state_high_court",
        "angle": "State high court ruling reshapes policing, sentencing, or evidence rules",
        "focus": "A major legal development below the national supreme court level but with sweeping local effects.",
        "questions": [
            "What doctrine or statute did the court reinterpret?",
            "How quickly will police, lawyers, and judges have to adapt?",
            "Could the ruling influence other states or provinces?",
        ],
    },
    {
        "id": "cl_067",
        "category": "state_high_court",
        "angle": "Sharp split among top judges reveals deeper ideological divide",
        "focus": "A judicial drama story about not just the ruling, but the fight inside the court.",
        "questions": [
            "What did the dissent accuse the majority of doing wrong?",
            "Is the dispute technical, ideological, or both?",
            "How might this split shape future cases?",
        ],
    },
    {
        "id": "cl_068",
        "category": "supreme_court",
        "angle": "Supreme court hears blockbuster case on criminal procedure",
        "focus": "A high-level legal drama story where doctrine and daily policing meet.",
        "questions": [
            "What specific question is before the court?",
            "How could the ruling affect arrests, searches, or prosecutions nationwide?",
            "Which justices appeared skeptical during arguments?",
        ],
    },
    {
        "id": "cl_069",
        "category": "supreme_court",
        "angle": "Supreme court weighs balance between public safety and constitutional rights",
        "focus": "A classic national legal battle over how far government power can go.",
        "questions": [
            "What right is allegedly being limited?",
            "How is the government defending its authority?",
            "Could the ruling transform future law enforcement practice?",
        ],
    },
    {
        "id": "cl_070",
        "category": "supreme_court",
        "angle": "Explosive dissent turns court ruling into institutional drama",
        "focus": "A judiciary-as-politics story where tone, legitimacy, and power matter as much as doctrine.",
        "questions": [
            "Why is the dissent drawing so much attention?",
            "What does it reveal about internal tensions on the court?",
            "How does rhetoric shape public trust in the judiciary?",
        ],
    },
    {
        "id": "cl_071",
        "category": "supreme_court",
        "angle": "Emergency order from supreme court changes legal landscape overnight",
        "focus": "A fast-moving court story about shadow dockets, injunctions, and immediate legal uncertainty.",
        "questions": [
            "What practical effect does the order have right now?",
            "How much reasoning did the court provide?",
            "Are critics accusing the justices of acting too quickly or opaquely?",
        ],
    },
    {
        "id": "cl_072",
        "category": "supreme_court",
        "angle": "Supreme court legitimacy becomes part of the story, not just the ruling",
        "focus": "A meta-judicial story where ethics, ideology, and public trust surround the case.",
        "questions": [
            "How is the court's reputation shaping reaction to the decision?",
            "Do observers see law, politics, or both driving the outcome?",
            "What does this mean for compliance and future controversies?",
        ],
    },
    {
        "id": "cl_073",
        "category": "judicial_ethics",
        "angle": "Judge's conduct, conflict, or undisclosed ties spark ethics inquiry",
        "focus": "A rule-of-law story about whether judges themselves are being held to adequate standards.",
        "questions": [
            "What conduct is under scrutiny?",
            "What ethics rules allegedly apply?",
            "How often are judges meaningfully disciplined?",
        ],
    },
    {
        "id": "cl_074",
        "category": "judicial_ethics",
        "angle": "Recusal fight in major case raises questions about fairness from the bench",
        "focus": "A procedural drama story that can shape the whole case before the merits are reached.",
        "questions": [
            "Why do critics say the judge should step aside?",
            "What standards govern recusal here?",
            "How might the dispute affect confidence in the eventual ruling?",
        ],
    },
    {
        "id": "cl_075",
        "category": "forensics",
        "angle": "DNA, phone records, and surveillance video become the spine of the prosecution case",
        "focus": "A modern evidence story about why investigations increasingly depend on technical traces.",
        "questions": [
            "Which forensic or digital evidence is strongest?",
            "How is the defense challenging interpretation?",
            "Do jurors tend to overtrust scientific-looking evidence?",
        ],
    },
    {
        "id": "cl_076",
        "category": "forensics",
        "angle": "Defense attacks reliability of forensic lab work in major case",
        "focus": "A courtroom-science story about chain of custody, contamination, and expert uncertainty.",
        "questions": [
            "What failures are alleged in the lab process?",
            "Could similar problems affect other cases?",
            "How much certainty did prosecutors claim before the challenge?",
        ],
    },
    {
        "id": "cl_077",
        "category": "victims_and_families",
        "angle": "Families say the justice system moves too slowly for those living with grief",
        "focus": "A victim-centered story about delay, closure, and procedural frustration.",
        "questions": [
            "What stage is the case stuck in?",
            "How are families participating in the process?",
            "What would meaningful accountability look like to them?",
        ],
    },
    {
        "id": "cl_078",
        "category": "victims_and_families",
        "angle": "Restorative justice option divides opinion in emotionally charged case",
        "focus": "A story about alternative justice models meeting public expectations for punishment.",
        "questions": [
            "Why was restorative justice considered here?",
            "How do victims and defendants understand accountability differently?",
            "What do critics fear this approach minimizes?",
        ],
    },
    {
        "id": "cl_079",
        "category": "law_and_politics",
        "angle": "Election-season crime rhetoric collides with courtroom reality",
        "focus": "A story about how politicians simplify legal complexity into campaign messages.",
        "questions": [
            "Which cases are being invoked for political gain?",
            "Where does rhetoric diverge from what the law actually allows?",
            "How are prosecutors, judges, or defense lawyers reacting?",
        ],
    },
    {
        "id": "cl_080",
        "category": "law_and_politics",
        "angle": "Attorney general or justice minister faces accusations of politicized enforcement",
        "focus": "A power story about whether law is being applied neutrally.",
        "questions": [
            "What decision triggered the accusation?",
            "What evidence supports or undercuts claims of selective enforcement?",
            "How much public trust is at stake?",
        ],
    },
    {
        "id": "cl_081",
        "category": "constitutional_drama",
        "angle": "Top court confrontation redefines the boundaries of executive power",
        "focus": "A supreme-court-level clash with implications beyond crime law alone.",
        "questions": [
            "What power is the executive branch claiming?",
            "How are justices framing the constitutional stakes?",
            "Could the ruling shift the balance among institutions?",
        ],
    },
    {
        "id": "cl_082",
        "category": "constitutional_drama",
        "angle": "Major ruling on due process could reshape how the state treats the accused",
        "focus": "A high-consequence legal story about fairness before punishment.",
        "questions": [
            "What procedural protections are in dispute?",
            "Who will benefit most immediately from the ruling?",
            "How far might lower courts extend the precedent?",
        ],
    },
    {
        "id": "cl_083",
        "category": "constitutional_drama",
        "angle": "Court weighs whether emergency powers went too far in the name of safety",
        "focus": "A dramatic story about crisis governance, rights, and retrospective judgment.",
        "questions": [
            "What emergency measures are being challenged?",
            "What harms or protections resulted from those measures?",
            "Will the court prioritize deference or restraint?",
        ],
    },
    {
        "id": "cl_084",
        "category": "systemwide",
        "angle": "Crime trends are falling, but trust in the justice system is not recovering",
        "focus": "A high-level explanatory story about why data and public sentiment often diverge.",
        "questions": [
            "What do the numbers say and what do people feel instead?",
            "Which institutions suffer the deepest trust gap?",
            "What would actually rebuild legitimacy?",
        ],
    },
    {
        "id": "cl_085",
        "category": "systemwide",
        "angle": "Every stage of the justice system is under strain, from arrest to appeal",
        "focus": "A broad systems story connecting staffing, backlog, prison conditions, and constitutional pressure.",
        "questions": [
            "Where is the system most overloaded?",
            "How do failures at one stage create failures at another?",
            "What reforms are realistic versus purely symbolic?",
        ],
    },
    {
        "id": "cl_086",
        "category": "systemwide",
        "angle": "The real crime and law story is legitimacy: who still trusts the system, and why",
        "focus": "A top-level framing story linking crime coverage, court drama, civil rights, and institutional confidence.",
        "questions": [
            "Which actors still command public trust?",
            "What events most damage perceived legitimacy?",
            "Can safety, fairness, and liberty be defended at the same time?",
        ],
    },
]
