economics_business_angles = {
    "topic": "economics_and_business",
    "version": "1.0",
    "angles": [
        {
            "id": "eb_001",
            "category": "macroeconomics",
            "angle": "Inflation fatigue changes household behavior",
            "focus": "How persistent price increases alter shopping, saving, and lifestyle choices.",
            "questions": [
                "What spending categories are consumers cutting first?",
                "Which products are seeing the strongest downtrading?",
                "Are households changing long-term habits or just delaying purchases?",
            ],
        },
        {
            "id": "eb_002",
            "category": "macroeconomics",
            "angle": "High interest rates squeeze businesses and borrowers",
            "focus": "The real-world consequences of elevated borrowing costs.",
            "questions": [
                "Which sectors are most vulnerable to refinancing risk?",
                "How are consumers adapting to higher loan payments?",
                "What signs suggest rate pressure is spreading through the economy?",
            ],
        },
        {
            "id": "eb_003",
            "category": "macroeconomics",
            "angle": "The uneven slowdown across sectors",
            "focus": "Why some parts of the economy cool quickly while others remain resilient.",
            "questions": [
                "Which industries are still expanding despite broader weakness?",
                "Where is demand falling fastest?",
                "What does the divergence reveal about structural shifts?",
            ],
        },
        {
            "id": "eb_004",
            "category": "macroeconomics",
            "angle": "The hidden economy behind official GDP growth",
            "focus": "The gap between headline economic growth and lived economic experience.",
            "questions": [
                "Why can GDP rise while many households feel worse off?",
                "Which regions or demographics are being left behind?",
                "How do economists measure this disconnect?",
            ],
        },
        {
            "id": "eb_005",
            "category": "macroeconomics",
            "angle": "Are recession fears changing corporate strategy?",
            "focus": "How businesses prepare for a downturn before it arrives.",
            "questions": [
                "Are firms freezing hiring, delaying projects, or preserving cash?",
                "Which executives are acting defensively?",
                "How much caution is perception versus real deterioration?",
            ],
        },
        {
            "id": "eb_006",
            "category": "macroeconomics",
            "angle": "Productivity puzzle in the post-pandemic economy",
            "focus": "Why productivity growth remains volatile and difficult to interpret.",
            "questions": [
                "Which sectors are seeing measurable productivity gains?",
                "How much has automation changed output per worker?",
                "What role does remote work play in the productivity debate?",
            ],
        },
        {
            "id": "eb_007",
            "category": "labor",
            "angle": "Layoffs spread beyond tech",
            "focus": "How cost-cutting expands into sectors once seen as stable.",
            "questions": [
                "Which industries are now reducing headcount?",
                "Are layoffs driven by weak demand, automation, or investor pressure?",
                "What does the severance and rehiring landscape look like?",
            ],
        },
        {
            "id": "eb_008",
            "category": "labor",
            "angle": "The rise of quiet hiring",
            "focus": "Companies filling skill gaps without adding permanent staff.",
            "questions": [
                "How are employers redistributing work internally?",
                "What skills are most often reassigned?",
                "Does quiet hiring improve agility or increase burnout?",
            ],
        },
        {
            "id": "eb_009",
            "category": "labor",
            "angle": "Wage growth versus cost of living",
            "focus": "Whether pay increases are actually improving worker purchasing power.",
            "questions": [
                "Which occupations have seen real wage gains?",
                "Where are raises still lagging inflation?",
                "How does wage growth differ across age and income groups?",
            ],
        },
        {
            "id": "eb_010",
            "category": "labor",
            "angle": "The new geography of work",
            "focus": "How hybrid and remote work are reshaping regional economies.",
            "questions": [
                "Which cities are gaining remote workers?",
                "How are office districts adapting to lower foot traffic?",
                "What businesses benefit when workers stay local?",
            ],
        },
        {
            "id": "eb_011",
            "category": "labor",
            "angle": "A tighter labor market changes employer power",
            "focus": "How worker leverage affects pay, perks, and job mobility.",
            "questions": [
                "Which sectors still face talent shortages?",
                "How are employers responding to retention pressure?",
                "Is worker bargaining power starting to fade?",
            ],
        },
        {
            "id": "eb_012",
            "category": "labor",
            "angle": "The side-hustle economy becomes permanent",
            "focus": "Why more workers are treating secondary income as a necessity, not a hobby.",
            "questions": [
                "What types of side hustles are growing fastest?",
                "How much of this is driven by debt or rising rent?",
                "Are platforms making it easier or harder to earn reliably?",
            ],
        },
        {
            "id": "eb_013",
            "category": "labor",
            "angle": "Generative AI reshapes white-collar roles",
            "focus": "How AI tools are changing expectations for knowledge workers.",
            "questions": [
                "Which tasks are being automated first?",
                "Are companies reducing hiring because of AI?",
                "How are workers being retrained or re-evaluated?",
            ],
        },
        {
            "id": "eb_014",
            "category": "small_business",
            "angle": "Small businesses absorb the cost shock",
            "focus": "How smaller firms cope with higher wages, rent, insurance, and financing costs.",
            "questions": [
                "Which expenses are hitting small firms hardest?",
                "How are owners balancing price hikes against customer resistance?",
                "What businesses are most at risk of closure?",
            ],
        },
        {
            "id": "eb_015",
            "category": "small_business",
            "angle": "The neighborhood business revival story",
            "focus": "How local entrepreneurs are filling gaps left by chains or closures.",
            "questions": [
                "What kinds of businesses are returning to main streets?",
                "Why are some communities seeing new local momentum?",
                "What role do grants, zoning, or tourism play?",
            ],
        },
        {
            "id": "eb_016",
            "category": "small_business",
            "angle": "Franchise growth as a safer bet",
            "focus": "Why entrepreneurs may choose franchise models during uncertainty.",
            "questions": [
                "Which franchise categories are attracting new investors?",
                "How do startup risks compare with independent businesses?",
                "What tradeoffs come with franchise fees and rules?",
            ],
        },
        {
            "id": "eb_017",
            "category": "consumer",
            "angle": "Consumers trade down but still seek small luxuries",
            "focus": "Why shoppers cut back broadly while protecting a few indulgences.",
            "questions": [
                "Which affordable luxuries are proving resilient?",
                "How are brands repositioning around value and comfort?",
                "What does this reveal about consumer psychology?",
            ],
        },
        {
            "id": "eb_018",
            "category": "consumer",
            "angle": "Subscription fatigue hits household budgets",
            "focus": "How consumers are auditing recurring spending.",
            "questions": [
                "What kinds of subscriptions are easiest to cancel?",
                "How are companies responding to churn?",
                "Are consumers moving back toward one-time purchases?",
            ],
        },
        {
            "id": "eb_019",
            "category": "consumer",
            "angle": "Buy now, pay later becomes a household balancing tool",
            "focus": "The normalization of installment financing for everyday purchases.",
            "questions": [
                "Who relies most on short-term installment products?",
                "Are missed payments becoming a bigger concern?",
                "What does this trend say about household financial stress?",
            ],
        },
        {
            "id": "eb_020",
            "category": "consumer",
            "angle": "The comeback of discount retail",
            "focus": "Why value chains and off-price sellers thrive in uncertain times.",
            "questions": [
                "Which retailers are capturing budget-conscious shoppers?",
                "How are premium brands responding to discount competition?",
                "What products are moving most through value channels?",
            ],
        },
        {
            "id": "eb_021",
            "category": "housing",
            "angle": "The lock-in effect freezes the housing market",
            "focus": "How existing homeowners with low mortgage rates stay put, reducing supply.",
            "questions": [
                "How much does rate lock-in constrain resale inventory?",
                "What markets are most affected?",
                "What businesses lose out when fewer people move?",
            ],
        },
        {
            "id": "eb_022",
            "category": "housing",
            "angle": "Renters face a new affordability ceiling",
            "focus": "How rising rents change living arrangements and consumer behavior.",
            "questions": [
                "Where are renters doubling up or moving farther out?",
                "How are landlords responding to affordability pressure?",
                "What spillover effects hit transit, retail, and schools?",
            ],
        },
        {
            "id": "eb_023",
            "category": "housing",
            "angle": "Construction slowdown threatens future supply",
            "focus": "Whether fewer starts now will deepen shortages later.",
            "questions": [
                "What is causing builders to pull back?",
                "Which housing segments are still being built?",
                "How does financing cost affect project viability?",
            ],
        },
        {
            "id": "eb_024",
            "category": "housing",
            "angle": "Office towers search for a second life",
            "focus": "How cities and developers are repurposing underused commercial buildings.",
            "questions": [
                "What conversions are financially realistic?",
                "Which zoning and engineering barriers remain?",
                "Can office-to-residential projects materially ease housing shortages?",
            ],
        },
        {
            "id": "eb_025",
            "category": "banking",
            "angle": "Regional banks under pressure",
            "focus": "How funding costs, commercial real estate exposure, and regulation affect smaller lenders.",
            "questions": [
                "Which balance-sheet risks matter most now?",
                "Are depositors changing behavior?",
                "How are regional lenders adapting their loan books?",
            ],
        },
        {
            "id": "eb_026",
            "category": "banking",
            "angle": "Credit gets harder to access for ordinary borrowers",
            "focus": "The consequences of tighter lending standards.",
            "questions": [
                "Who is being priced out of credit?",
                "Which loan categories are seeing the biggest pullback?",
                "How does tighter credit feed back into growth?",
            ],
        },
        {
            "id": "eb_027",
            "category": "banking",
            "angle": "Deposits migrate in search of yield",
            "focus": "Why savers are moving money and what that means for banks.",
            "questions": [
                "How aggressive are banks becoming on deposit rates?",
                "Where are customers moving their cash?",
                "What does deposit competition mean for profitability?",
            ],
        },
        {
            "id": "eb_028",
            "category": "markets",
            "angle": "Stock markets rally while the real economy softens",
            "focus": "The disconnect between investor optimism and economic caution.",
            "questions": [
                "Which narratives are driving equity valuations?",
                "How concentrated is market leadership?",
                "What risks could break the divergence?",
            ],
        },
        {
            "id": "eb_029",
            "category": "markets",
            "angle": "Retail investors return to risk",
            "focus": "How individual traders are re-entering volatile corners of the market.",
            "questions": [
                "What themes are attracting retail enthusiasm?",
                "Are social platforms still shaping trading behavior?",
                "What does renewed speculation signal about sentiment?",
            ],
        },
        {
            "id": "eb_030",
            "category": "markets",
            "angle": "Private markets promise stability in an unstable world",
            "focus": "Why investors are shifting interest toward private credit and private equity.",
            "questions": [
                "What risks are being underestimated in private markets?",
                "Why are institutions allocating more capital there?",
                "How does illiquidity change investor behavior?",
            ],
        },
        {
            "id": "eb_031",
            "category": "corporate",
            "angle": "Profit margins under pressure",
            "focus": "How companies defend margins when costs stay elevated and demand softens.",
            "questions": [
                "Which tactics are businesses using to protect earnings?",
                "Where are price increases no longer accepted?",
                "How much margin preservation comes from layoffs or automation?",
            ],
        },
        {
            "id": "eb_032",
            "category": "corporate",
            "angle": "The era of corporate belt-tightening",
            "focus": "From travel budgets to software sprawl, companies trim hidden excess.",
            "questions": [
                "What spending categories are being cut first?",
                "How are CFOs redefining efficiency?",
                "Which vendors are losing business as a result?",
            ],
        },
        {
            "id": "eb_033",
            "category": "corporate",
            "angle": "Mergers return as valuations reset",
            "focus": "Why dealmaking may rebound after a period of hesitation.",
            "questions": [
                "Which sectors are ripest for consolidation?",
                "How are antitrust concerns shaping strategy?",
                "Are distressed assets becoming attractive again?",
            ],
        },
        {
            "id": "eb_034",
            "category": "corporate",
            "angle": "Share buybacks versus business investment",
            "focus": "How companies decide between rewarding investors and expanding operations.",
            "questions": [
                "Which firms are prioritizing buybacks over capex?",
                "How do investors react to each approach?",
                "What does the choice reveal about growth confidence?",
            ],
        },
        {
            "id": "eb_035",
            "category": "technology_business",
            "angle": "AI spending boom creates winners and bystanders",
            "focus": "The businesses benefiting most from the race to build and deploy AI.",
            "questions": [
                "Which parts of the supply chain see the biggest revenue gains?",
                "What costs are enterprises underestimating?",
                "Are smaller firms being left behind?",
            ],
        },
        {
            "id": "eb_036",
            "category": "technology_business",
            "angle": "Tech firms pivot from growth at all costs to monetization",
            "focus": "How digital companies are squeezing more revenue from existing users.",
            "questions": [
                "What products are being paywalled or repriced?",
                "How do customers respond to monetization pushes?",
                "Which business models are proving durable?",
            ],
        },
        {
            "id": "eb_037",
            "category": "technology_business",
            "angle": "Cloud and compute demand reshape capital spending",
            "focus": "How infrastructure needs are driving massive corporate investment.",
            "questions": [
                "Which companies are spending most on data centers and chips?",
                "What does this mean for utilities and construction?",
                "Could demand outpace power or real estate supply?",
            ],
        },
        {
            "id": "eb_038",
            "category": "technology_business",
            "angle": "Startups face a tougher funding reality",
            "focus": "How founders adjust when cheap capital disappears.",
            "questions": [
                "Which startups can still raise easily?",
                "How are valuations and terms changing?",
                "What sectors remain attractive to venture investors?",
            ],
        },
        {
            "id": "eb_039",
            "category": "trade",
            "angle": "Trade fragmentation creates new winners",
            "focus": "How geopolitical tension reshapes import routes and manufacturing hubs.",
            "questions": [
                "Which countries are gaining business from supply-chain diversification?",
                "What products are being reshored or friend-shored?",
                "How expensive is resilience compared with efficiency?",
            ],
        },
        {
            "id": "eb_040",
            "category": "trade",
            "angle": "Tariffs return as an industrial policy tool",
            "focus": "The business consequences of using trade barriers to protect domestic industry.",
            "questions": [
                "Which sectors benefit most from tariff support?",
                "Who ultimately absorbs the added cost?",
                "Do tariffs stimulate local production or just raise prices?",
            ],
        },
        {
            "id": "eb_041",
            "category": "trade",
            "angle": "Ports, shipping, and logistics feel global strain",
            "focus": "How disruptions ripple through freight costs and retail shelves.",
            "questions": [
                "What bottlenecks are most damaging to business planning?",
                "How are importers adapting their inventory strategies?",
                "Which goods are most vulnerable to delay?",
            ],
        },
        {
            "id": "eb_042",
            "category": "manufacturing",
            "angle": "Factories bet on automation to offset labor shortages",
            "focus": "The push toward robotics and smarter production systems.",
            "questions": [
                "Which manufacturers are automating fastest?",
                "What jobs are changing rather than disappearing?",
                "How long is the payback period on new equipment?",
            ],
        },
        {
            "id": "eb_043",
            "category": "manufacturing",
            "angle": "Industrial policy sparks a factory building wave",
            "focus": "How subsidies and tax incentives influence where plants get built.",
            "questions": [
                "Which regions are attracting the most manufacturing investment?",
                "How durable are these projects if policy changes?",
                "What local economic effects follow a new plant?",
            ],
        },
        {
            "id": "eb_044",
            "category": "manufacturing",
            "angle": "The cost of reindustrialization",
            "focus": "Whether bringing production closer to home is economically sustainable.",
            "questions": [
                "What tradeoffs do firms accept to reduce geopolitical risk?",
                "Which products make economic sense to reshore?",
                "How much will consumers pay for supply-chain security?",
            ],
        },
        {
            "id": "eb_045",
            "category": "energy",
            "angle": "Energy prices become a business planning risk",
            "focus": "How volatility in fuel and power markets affects margins and investment.",
            "questions": [
                "Which industries are most exposed to energy swings?",
                "How are firms hedging against price spikes?",
                "What happens when energy costs collide with weak demand?",
            ],
        },
        {
            "id": "eb_046",
            "category": "energy",
            "angle": "The business case for electrification",
            "focus": "How companies weigh the cost and savings of switching fleets, heating, or operations.",
            "questions": [
                "Which sectors are electrifying first?",
                "What incentives make the economics work?",
                "Where do infrastructure gaps remain a barrier?",
            ],
        },
        {
            "id": "eb_047",
            "category": "energy",
            "angle": "Clean energy investment meets grid reality",
            "focus": "Why renewable growth can outpace transmission and storage readiness.",
            "questions": [
                "Which projects are delayed by grid constraints?",
                "How are businesses adjusting to power availability concerns?",
                "What investment opportunities emerge from bottlenecks?",
            ],
        },
        {
            "id": "eb_048",
            "category": "retail",
            "angle": "Retail theft, security costs, and store economics",
            "focus": "How shrink and loss prevention change store profitability and strategy.",
            "questions": [
                "How significant are losses relative to other cost pressures?",
                "What anti-theft measures are retailers adopting?",
                "Do security changes affect customer experience and sales?",
            ],
        },
        {
            "id": "eb_049",
            "category": "retail",
            "angle": "Physical stores reinvent themselves in the e-commerce age",
            "focus": "Why brick-and-mortar locations still matter and how their role is changing.",
            "questions": [
                "What store formats are proving effective?",
                "How are retailers using locations for pickup, returns, and experience?",
                "Which categories still depend heavily on in-person sales?",
            ],
        },
        {
            "id": "eb_050",
            "category": "retail",
            "angle": "Retail calendars no longer follow old seasonal patterns",
            "focus": "How promotions, weather, and consumer caution disrupt traditional shopping cycles.",
            "questions": [
                "Which seasons are seeing weaker or earlier demand?",
                "How are retailers adjusting inventory buys?",
                "What does this mean for discounting and margins?",
            ],
        },
        {
            "id": "eb_051",
            "category": "real_estate",
            "angle": "Commercial real estate repricing changes local economies",
            "focus": "How falling property values affect lenders, tax bases, and downtown recovery.",
            "questions": [
                "Which property types face the steepest repricing?",
                "How will municipal finances be affected?",
                "What investors see opportunity in distressed assets?",
            ],
        },
        {
            "id": "eb_052",
            "category": "real_estate",
            "angle": "Warehouses boom while other property types struggle",
            "focus": "The uneven fortunes of industrial versus office and retail real estate.",
            "questions": [
                "Which logistics markets remain strong?",
                "Has e-commerce demand plateaued or normalized?",
                "What makes industrial space resilient?",
            ],
        },
        {
            "id": "eb_053",
            "category": "transportation",
            "angle": "Airlines and travel firms test consumer resilience",
            "focus": "Whether people keep paying for travel despite broader cost pressure.",
            "questions": [
                "Which travel segments hold up best?",
                "How are companies managing fuel, labor, and pricing?",
                "Is demand being driven by upper-income households alone?",
            ],
        },
        {
            "id": "eb_054",
            "category": "transportation",
            "angle": "The economics of EV adoption slow down",
            "focus": "Why enthusiasm for electric vehicles may not translate into uniform demand.",
            "questions": [
                "What affordability and infrastructure issues remain?",
                "How are automakers revising production plans?",
                "Which buyer groups are still driving EV sales?",
            ],
        },
        {
            "id": "eb_055",
            "category": "agriculture",
            "angle": "Food inflation reshapes the farm-to-shelf chain",
            "focus": "How rising input costs, weather, and logistics influence grocery bills.",
            "questions": [
                "Which parts of the food chain capture the biggest share of price increases?",
                "How are producers and grocers balancing margins?",
                "What products best illustrate the pressure?",
            ],
        },
        {
            "id": "eb_056",
            "category": "agriculture",
            "angle": "Weather risk becomes a business risk",
            "focus": "How climate-linked volatility affects agriculture, insurance, and commodity markets.",
            "questions": [
                "Which businesses are most exposed to weather disruption?",
                "How are insurers and lenders pricing the risk?",
                "What adaptation strategies are gaining traction?",
            ],
        },
        {
            "id": "eb_057",
            "category": "finance",
            "angle": "Household debt becomes the next economic flashpoint",
            "focus": "The accumulation of credit card, auto, and student debt burdens.",
            "questions": [
                "Which debt categories are creating the most stress?",
                "How does debt pressure affect consumer demand?",
                "What lenders are seeing early warning signs?",
            ],
        },
        {
            "id": "eb_058",
            "category": "finance",
            "angle": "Savings buffers built during the pandemic finally erode",
            "focus": "What happens when households run out of extra cash.",
            "questions": [
                "Which income groups depleted savings first?",
                "How does this change retail and credit trends?",
                "What sectors depend most on leftover consumer buffers?",
            ],
        },
        {
            "id": "eb_059",
            "category": "finance",
            "angle": "Insurance costs surge across households and businesses",
            "focus": "Why insurance is becoming a more visible driver of economic strain.",
            "questions": [
                "Which forms of insurance are rising fastest?",
                "How are businesses passing along higher costs?",
                "Are some regions becoming harder to insure?",
            ],
        },
        {
            "id": "eb_060",
            "category": "policy",
            "angle": "Industrial subsidies change competitive dynamics",
            "focus": "How government incentives reshape corporate strategy and location decisions.",
            "questions": [
                "Which industries benefit most from public support?",
                "How are rivals responding in other countries?",
                "Do subsidies create durable advantage or temporary distortions?",
            ],
        },
        {
            "id": "eb_061",
            "category": "policy",
            "angle": "Minimum wage increases test local business models",
            "focus": "How employers adapt to higher mandated pay floors.",
            "questions": [
                "Which sectors absorb the increase most easily?",
                "Are price hikes, automation, or schedule cuts the main response?",
                "How do workers' gains compare with employer strain?",
            ],
        },
        {
            "id": "eb_062",
            "category": "policy",
            "angle": "Regulation drives a new compliance economy",
            "focus": "The growth of businesses and roles dedicated to navigating rules and disclosure.",
            "questions": [
                "Which regulations are most costly for firms to implement?",
                "What new services or software are benefiting?",
                "Do large companies gain an advantage from higher compliance burdens?",
            ],
        },
        {
            "id": "eb_063",
            "category": "global_business",
            "angle": "Emerging markets offer growth but more volatility",
            "focus": "Why multinationals still pursue riskier geographies.",
            "questions": [
                "Which markets are attracting capital despite instability?",
                "How are firms hedging currency and political risk?",
                "What sectors are expanding most aggressively abroad?",
            ],
        },
        {
            "id": "eb_064",
            "category": "global_business",
            "angle": "Currency swings rewrite corporate earnings",
            "focus": "How exchange rates influence revenues, costs, and competitiveness.",
            "questions": [
                "Which multinational firms are most exposed to FX moves?",
                "How do hedging strategies affect results?",
                "What does a stronger or weaker currency mean for exporters?",
            ],
        },
        {
            "id": "eb_065",
            "category": "entrepreneurship",
            "angle": "The new startup playbook is leaner and more disciplined",
            "focus": "Why founders now prioritize cash flow over raw user growth.",
            "questions": [
                "How are startup metrics and milestones changing?",
                "Which sectors can still pursue blitzscaling?",
                "What investor expectations now define a viable business?",
            ],
        },
        {
            "id": "eb_066",
            "category": "entrepreneurship",
            "angle": "Micro-businesses built on creators and niches",
            "focus": "How individuals turn audiences, expertise, or niche products into durable income.",
            "questions": [
                "What business models work best for solo founders?",
                "How dependent are they on major platforms?",
                "What separates sustainable niche businesses from short-lived trends?",
            ],
        },
        {
            "id": "eb_067",
            "category": "supply_chain",
            "angle": "Inventory mistakes become expensive again",
            "focus": "How over-ordering or under-ordering hurts companies when demand is uncertain.",
            "questions": [
                "Which industries are most vulnerable to forecasting errors?",
                "How are businesses using data to improve inventory decisions?",
                "What markdowns or shortages show the cost of miscalculation?",
            ],
        },
        {
            "id": "eb_068",
            "category": "supply_chain",
            "angle": "The push for resilient supply chains raises consumer prices",
            "focus": "Why redundancy and geographic diversification carry a cost.",
            "questions": [
                "How much are firms willing to pay for resilience?",
                "Which products are most affected by supply-chain redesign?",
                "Will consumers reward reliability enough to justify the cost?",
            ],
        },
        {
            "id": "eb_069",
            "category": "inequality",
            "angle": "A strong economy on paper, a divided economy in practice",
            "focus": "How gains concentrate among certain households, firms, and regions.",
            "questions": [
                "Who benefits most from current growth patterns?",
                "What indicators best capture uneven outcomes?",
                "How do businesses adapt to polarized consumer capacity?",
            ],
        },
        {
            "id": "eb_070",
            "category": "inequality",
            "angle": "Luxury demand stays strong while mass-market demand weakens",
            "focus": "Why higher-end spending can remain resilient in a strained economy.",
            "questions": [
                "Which luxury segments are still outperforming?",
                "What does that say about wealth concentration?",
                "How are mid-market brands caught in the middle?",
            ],
        },
        {
            "id": "eb_071",
            "category": "demographics",
            "angle": "An aging population changes the economy",
            "focus": "How demographic shifts affect labor markets, housing, healthcare, and consumer demand.",
            "questions": [
                "Which industries gain from aging demographics?",
                "Where do labor shortages intensify?",
                "How are businesses redesigning products for older customers?",
            ],
        },
        {
            "id": "eb_072",
            "category": "demographics",
            "angle": "Youth economic pessimism influences spending and career choices",
            "focus": "How younger adults respond to housing costs, debt, and job insecurity.",
            "questions": [
                "What purchases are being delayed the most?",
                "How are younger workers changing job expectations?",
                "What industries are adapting to new generational preferences?",
            ],
        },
        {
            "id": "eb_073",
            "category": "education_business",
            "angle": "The business of skills training expands",
            "focus": "How employers and workers seek alternatives to traditional degrees.",
            "questions": [
                "Which credentials are gaining employer recognition?",
                "What industries are investing directly in workforce training?",
                "Is this improving access or just shifting costs?",
            ],
        },
        {
            "id": "eb_074",
            "category": "healthcare_business",
            "angle": "Healthcare labor shortages become an economic issue",
            "focus": "How staffing pressure in healthcare affects business costs and productivity.",
            "questions": [
                "How do shortages change wages and service availability?",
                "What employers face the biggest health-benefit cost increases?",
                "How are health systems trying to stabilize staffing?",
            ],
        },
        {
            "id": "eb_075",
            "category": "healthcare_business",
            "angle": "Healthcare consolidation changes local markets",
            "focus": "The economic impact of mergers among hospitals, insurers, and clinics.",
            "questions": [
                "Do larger systems lower costs or increase pricing power?",
                "How does consolidation affect rural or underserved communities?",
                "What businesses are affected by local healthcare concentration?",
            ],
        },
        {
            "id": "eb_076",
            "category": "media_business",
            "angle": "Advertising budgets become an early recession signal",
            "focus": "How marketing cuts reveal business confidence levels.",
            "questions": [
                "Which sectors cut advertising first?",
                "What channels lose spend fastest?",
                "How reliable is ad demand as a leading indicator?",
            ],
        },
        {
            "id": "eb_077",
            "category": "media_business",
            "angle": "The economics of streaming hit maturity",
            "focus": "Why media companies now prioritize profitability over subscriber growth at any cost.",
            "questions": [
                "How are bundling, ads, and price hikes changing the model?",
                "Which platforms can sustain large content budgets?",
                "What does consolidation look like in streaming?",
            ],
        },
        {
            "id": "eb_078",
            "category": "tourism_business",
            "angle": "Tourism-dependent economies ride a fragile boom",
            "focus": "How local economies tied to visitors manage seasonal demand and cost pressures.",
            "questions": [
                "Which destinations are benefiting most from travel demand?",
                "How vulnerable are they to consumer pullbacks?",
                "What strains does tourism place on housing and labor?",
            ],
        },
        {
            "id": "eb_079",
            "category": "public_finance",
            "angle": "Local government finances feel the business cycle",
            "focus": "How tax revenue, property values, and business closures influence public budgets.",
            "questions": [
                "Which revenue streams are weakening first?",
                "How do cities respond when downtown values fall?",
                "What services or projects are most at risk?",
            ],
        },
        {
            "id": "eb_080",
            "category": "public_finance",
            "angle": "Infrastructure spending as an economic stabilizer",
            "focus": "Whether public works can offset private-sector hesitation.",
            "questions": [
                "Which industries benefit most from infrastructure outlays?",
                "How quickly do projects translate into jobs and orders?",
                "What bottlenecks delay the economic payoff?",
            ],
        },
        {
            "id": "eb_081",
            "category": "corporate_governance",
            "angle": "Executive pay under scrutiny during layoffs",
            "focus": "How compensation decisions shape morale, reputation, and investor opinion.",
            "questions": [
                "How often does executive compensation rise during workforce cuts?",
                "What reactions come from shareholders and employees?",
                "Are boards changing how they justify pay packages?",
            ],
        },
        {
            "id": "eb_082",
            "category": "corporate_governance",
            "angle": "Short-term earnings pressure versus long-term resilience",
            "focus": "How public companies balance quarterly expectations against strategic patience.",
            "questions": [
                "Which leaders are sacrificing near-term margins for future advantage?",
                "How do investors respond to long-horizon spending?",
                "What sectors reward long-term thinking most?",
            ],
        },
        {
            "id": "eb_083",
            "category": "business_culture",
            "angle": "Corporate return-to-office battles carry economic consequences",
            "focus": "How workplace policy affects productivity, retention, commuting, and urban spending.",
            "questions": [
                "What industries are enforcing office attendance most aggressively?",
                "How do workers respond when flexibility is reduced?",
                "Which local businesses gain or lose from office returns?",
            ],
        },
        {
            "id": "eb_084",
            "category": "business_culture",
            "angle": "Burnout becomes a business performance problem",
            "focus": "How overwork and mental strain affect productivity and retention.",
            "questions": [
                "Which sectors show the highest burnout risk?",
                "How are firms quantifying the business cost of exhaustion?",
                "Do wellness efforts meaningfully change outcomes?",
            ],
        },
        {
            "id": "eb_085",
            "category": "innovation",
            "angle": "R&D budgets reveal who is planning for the next cycle",
            "focus": "How companies decide whether to keep investing in future products during uncertainty.",
            "questions": [
                "Which industries maintain R&D even under cost pressure?",
                "What does sustained innovation spending signal to investors?",
                "How often are future bets cut too early?",
            ],
        },
        {
            "id": "eb_086",
            "category": "innovation",
            "angle": "Patent races and strategic technology bets",
            "focus": "How firms compete for advantage in emerging industries.",
            "questions": [
                "Which sectors are seeing the fastest IP competition?",
                "How do patent strategies affect market power?",
                "Are smaller innovators being acquired before they can scale?",
            ],
        },
        {
            "id": "eb_087",
            "category": "commodities",
            "angle": "Commodity prices signal more than inflation",
            "focus": "How moves in oil, metals, and crops reveal business expectations.",
            "questions": [
                "Which commodities best reflect industrial demand?",
                "How quickly do commodity shifts affect consumer prices?",
                "What sectors react first to a change in raw-material costs?",
            ],
        },
        {
            "id": "eb_088",
            "category": "commodities",
            "angle": "Critical minerals become a strategic business story",
            "focus": "Why supply chains for batteries and advanced manufacturing attract intense attention.",
            "questions": [
                "Which countries and firms dominate supply?",
                "How are buyers trying to secure access?",
                "What environmental or political tradeoffs complicate expansion?",
            ],
        },
        {
            "id": "eb_089",
            "category": "international_competitiveness",
            "angle": "Who wins the next manufacturing race?",
            "focus": "How tax policy, labor, energy, and logistics shape national competitiveness.",
            "questions": [
                "What factors matter most in corporate site selection?",
                "Which regions are improving fastest?",
                "How sticky are these decisions once plants are built?",
            ],
        },
        {
            "id": "eb_090",
            "category": "international_competitiveness",
            "angle": "Can advanced economies still build at scale?",
            "focus": "The costs and constraints of large industrial projects in mature markets.",
            "questions": [
                "What slows major projects most: labor, permits, financing, or infrastructure?",
                "How do timelines compare across countries?",
                "What does this mean for future industrial policy?",
            ],
        },
    ],
}
