from synthnews.prompts.angles import Angle


ANGLES: list[Angle] = [
    {
        "id": "ent_001",
        "category": "film",
        "angle": "Major studio bets big on an original film in a sequel-dominated market",
        "focus": "A movie business story about creative risk, audience appetite, and franchise fatigue.",
        "questions": [
            "Why is the studio taking a chance on an original property now?",
            "How are executives framing the film's commercial prospects?",
            "What would success or failure signal for future greenlights?",
        ],
    },
    {
        "id": "ent_002",
        "category": "film",
        "angle": "Box office surprise turns a modest release into a breakout hit",
        "focus": "A momentum story about how audience buzz outpaces industry expectations.",
        "questions": [
            "What drove the film's sudden surge?",
            "Did critics, social media, or word of mouth matter most?",
            "How is the studio responding to the unexpected success?",
        ],
    },
    {
        "id": "ent_003",
        "category": "film",
        "angle": "Big-budget flop raises new doubts about franchise strategy",
        "focus": "A studio drama story about overspending, audience fatigue, and brand erosion.",
        "questions": [
            "Why did the film underperform?",
            "Was the problem marketing, quality, timing, or franchise exhaustion?",
            "What projects might be reconsidered after the disappointment?",
        ],
    },
    {
        "id": "ent_004",
        "category": "film",
        "angle": "Prestige drama becomes an awards contender after a quiet release",
        "focus": "A critical-acclaim story about how smaller films build momentum through reviews and performances.",
        "questions": [
            "What turned the film into an awards threat?",
            "Which performances or creative choices are drawing the most attention?",
            "Can prestige buzz translate into commercial staying power?",
        ],
    },
    {
        "id": "ent_005",
        "category": "film",
        "angle": "Remake or reboot announcement triggers debate over nostalgia and creative stagnation",
        "focus": "A culture story about whether Hollywood is mining memory instead of generating novelty.",
        "questions": [
            "Why did the studio revive this property now?",
            "How are fans reacting to the remake plan?",
            "What does the project say about current studio risk tolerance?",
        ],
    },
    {
        "id": "ent_006",
        "category": "film",
        "angle": "Indie filmmakers find audiences outside the traditional theatrical model",
        "focus": "A film ecosystem story about festivals, streaming, niche communities, and alternative release paths.",
        "questions": [
            "How are smaller films building visibility?",
            "What release strategies are proving effective for independents?",
            "Does the new landscape create freedom or fragmentation?",
        ],
    },
    {
        "id": "ent_007",
        "category": "film",
        "angle": "A casting choice becomes the story before filming even begins",
        "focus": "A pre-release entertainment story about fan expectations, identity, and franchise stewardship.",
        "questions": [
            "Why is the casting decision generating such strong reaction?",
            "What expectations come with the role?",
            "How are the studio and talent managing the backlash or excitement?",
        ],
    },
    {
        "id": "ent_008",
        "category": "film",
        "angle": "Director's cut revives debate over who really controls a movie",
        "focus": "A creative-authority story about studios, filmmakers, fandom, and artistic intent.",
        "questions": [
            "What makes this alternate version feel significant?",
            "How much did studio intervention shape the original release?",
            "Why do audiences become invested in version politics?",
        ],
    },
    {
        "id": "ent_009",
        "category": "television",
        "angle": "Breakout series becomes the cultural conversation of the season",
        "focus": "A television momentum story about how one show suddenly dominates attention.",
        "questions": [
            "What made the series catch fire with audiences?",
            "How much did memes, critics, or cliffhangers fuel the rise?",
            "Can the show sustain interest beyond the initial buzz?",
        ],
    },
    {
        "id": "ent_010",
        "category": "television",
        "angle": "Fan backlash hits beloved series after a controversial creative turn",
        "focus": "A fandom and storytelling story about expectation, betrayal, and serialized trust.",
        "questions": [
            "What decision triggered the backlash?",
            "Are fans reacting to quality, tone, character arcs, or ideology?",
            "Can the show recover audience goodwill?",
        ],
    },
    {
        "id": "ent_011",
        "category": "television",
        "angle": "Network or streaming cancellation sparks outrage from a loyal fan base",
        "focus": "A cancellation drama story about the gap between engagement and business decisions.",
        "questions": [
            "Why was the show canceled despite passionate support?",
            "How do platforms measure value beyond visible fandom?",
            "Is there any realistic path to revival?",
        ],
    },
    {
        "id": "ent_012",
        "category": "television",
        "angle": "Limited series blurs the line between television event and prestige film",
        "focus": "A format story about how serialized storytelling attracts cinematic ambition.",
        "questions": [
            "Why was this story told as a series instead of a movie?",
            "What creative advantages come from the format?",
            "How are audiences responding to event-style limited runs?",
        ],
    },
    {
        "id": "ent_013",
        "category": "television",
        "angle": "Reality show scandal spills off-screen and overwhelms the actual program",
        "focus": "A story where cast conflict, leaked information, or social drama eclipses the broadcast itself.",
        "questions": [
            "What off-screen development changed the show's public narrative?",
            "How are producers using or managing the controversy?",
            "Does scandal strengthen ratings or damage the brand?",
        ],
    },
    {
        "id": "ent_014",
        "category": "streaming",
        "angle": "Streaming platform raises prices and tests audience loyalty",
        "focus": "A business-and-audience story about how much consumers will tolerate for convenience.",
        "questions": [
            "Why is the platform changing pricing now?",
            "How are subscribers reacting?",
            "Does the service still offer enough value to prevent churn?",
        ],
    },
    {
        "id": "ent_015",
        "category": "streaming",
        "angle": "Streaming hit proves algorithms still cannot fully predict culture",
        "focus": "A platform story about the limits of data-driven commissioning and recommendation systems.",
        "questions": [
            "Why did this title break through unexpectedly?",
            "What role did platform promotion versus genuine audience discovery play?",
            "What does the breakout reveal about streaming strategy?",
        ],
    },
    {
        "id": "ent_016",
        "category": "streaming",
        "angle": "Ad-supported streaming tier changes the feel of digital entertainment",
        "focus": "A format and business story about the return of interruption in on-demand media.",
        "questions": [
            "How are viewers responding to ads inside streaming services?",
            "What tradeoffs make the lower-cost tier attractive?",
            "Does advertising alter what kinds of shows get made?",
        ],
    },
    {
        "id": "ent_017",
        "category": "music",
        "angle": "Artist's surprise release turns a quiet week into a music event",
        "focus": "A release-strategy story about momentum, secrecy, and fan mobilization.",
        "questions": [
            "Why was the release kept secret or dropped suddenly?",
            "How did fans and platforms amplify the moment?",
            "What does the move say about the artist's confidence and status?",
        ],
    },
    {
        "id": "ent_018",
        "category": "music",
        "angle": "Tour announcement becomes a referendum on ticket prices and fan access",
        "focus": "A live music story about demand, loyalty, and affordability friction.",
        "questions": [
            "How expensive are tickets relative to fan expectations?",
            "What role do presales and dynamic pricing play in frustration?",
            "Can artist popularity survive repeated ticketing outrage?",
        ],
    },
    {
        "id": "ent_019",
        "category": "music",
        "angle": "Album rollout becomes as carefully engineered as the music itself",
        "focus": "A pop strategy story about teasers, aesthetics, timing, and online community.",
        "questions": [
            "What elements made the rollout feel like an event?",
            "How does image-building shape musical reception?",
            "Can hype ever overshadow the music too much?",
        ],
    },
    {
        "id": "ent_020",
        "category": "music",
        "angle": "Legacy act proves older catalogs can still command massive audiences",
        "focus": "A nostalgia and endurance story about long-term fandom and cultural staying power.",
        "questions": [
            "Why does this artist still matter across generations?",
            "How are newer audiences discovering older music?",
            "What makes a catalog stay culturally alive?",
        ],
    },
    {
        "id": "ent_021",
        "category": "music",
        "angle": "Rising star's sudden backlash shows how fast online fandom can reverse",
        "focus": "A volatility story about celebrity construction, scrutiny, and audience mood swings.",
        "questions": [
            "What triggered the shift in public sentiment?",
            "How are fan communities dividing in response?",
            "Can a rising artist recover narrative control after online backlash?",
        ],
    },
    {
        "id": "ent_022",
        "category": "music",
        "angle": "Genre crossover becomes the key to a bigger mainstream breakthrough",
        "focus": "A trend story about artists blending sounds to expand audiences and reposition themselves.",
        "questions": [
            "What genres are being combined and why?",
            "How do core fans respond to the shift?",
            "Does crossover success reflect artistic growth or market calculation?",
        ],
    },
    {
        "id": "ent_023",
        "category": "celebrity",
        "angle": "Celebrity relationship news becomes an entertainment economy of its own",
        "focus": "A fame story about how romance, breakup, and rumor cycles generate attention independent of actual work.",
        "questions": [
            "Why does this relationship dominate public interest?",
            "How do tabloids, fan accounts, and platforms amplify the story?",
            "What happens when celebrity identity becomes inseparable from personal life coverage?",
        ],
    },
    {
        "id": "ent_024",
        "category": "celebrity",
        "angle": "Public apology from a major star becomes a test of reputation recovery",
        "focus": "A scandal-management story about sincerity, timing, and audience forgiveness.",
        "questions": [
            "What exactly is the celebrity apologizing for?",
            "Does the apology feel strategic or genuine?",
            "What determines whether a comeback is possible?",
        ],
    },
    {
        "id": "ent_025",
        "category": "celebrity",
        "angle": "A star's image overhaul reveals how carefully fame is managed",
        "focus": "A celebrity-brand story about reinvention after missteps, stagnation, or maturity.",
        "questions": [
            "What is changing in the celebrity's presentation?",
            "Why is reinvention happening now?",
            "How do fans distinguish authentic growth from strategic rebranding?",
        ],
    },
    {
        "id": "ent_026",
        "category": "celebrity",
        "angle": "Nepotism debate returns as another famous family launches the next generation",
        "focus": "A culture-industry story about access, legitimacy, and inherited visibility.",
        "questions": [
            "Why does this case provoke resentment or defensiveness?",
            "How much does access actually determine entertainment success?",
            "Can audiences ever separate talent from advantage?",
        ],
    },
    {
        "id": "ent_027",
        "category": "awards",
        "angle": "Awards ceremony becomes the stage for unexpected drama",
        "focus": "A live-event story where speeches, snubs, protests, or awkward moments eclipse the winners.",
        "questions": [
            "What moment dominated attention beyond the trophies?",
            "How are organizers and attendees reacting afterward?",
            "Did the incident help or hurt the ceremony's cultural relevance?",
        ],
    },
    {
        "id": "ent_028",
        "category": "awards",
        "angle": "A major snub reignites debate over who awards shows really value",
        "focus": "A legitimacy story about taste, politics, industry bias, and representation.",
        "questions": [
            "Who was left out and why are reactions so strong?",
            "What patterns do critics see in the nominations or wins?",
            "Do awards still shape careers the way they once did?",
        ],
    },
    {
        "id": "ent_029",
        "category": "awards",
        "angle": "Campaign season reveals awards as strategy as much as artistic recognition",
        "focus": "A behind-the-scenes story about lobbying, positioning, and prestige economics.",
        "questions": [
            "How do studios and publicists shape awards momentum?",
            "What narratives are being built around contenders?",
            "How much do campaigns matter compared to the work itself?",
        ],
    },
    {
        "id": "ent_030",
        "category": "social_media_creators",
        "angle": "Creator crosses from internet fame into mainstream entertainment",
        "focus": "A platform migration story about whether digital celebrity can convert into durable career power.",
        "questions": [
            "What opportunities is the creator moving into?",
            "How does mainstream entertainment evaluate creator audiences?",
            "Can online fame survive a shift to traditional formats?",
        ],
    },
    {
        "id": "ent_031",
        "category": "social_media_creators",
        "angle": "Influencer scandal exposes the fragility of parasocial trust",
        "focus": "A digital fame story about audience intimacy, betrayal, and monetized authenticity.",
        "questions": [
            "What behavior or revelation caused the backlash?",
            "Why did followers feel personally invested in the fallout?",
            "How do creators rebuild after trust breaks?",
        ],
    },
    {
        "id": "ent_032",
        "category": "social_media_creators",
        "angle": "Platform algorithm shift rewrites who gets seen and who disappears",
        "focus": "A creator economy story about visibility, dependency, and abrupt career instability.",
        "questions": [
            "What changed on the platform?",
            "Which creators are benefiting or losing out?",
            "What does this reveal about platform dependence in entertainment?",
        ],
    },
    {
        "id": "ent_033",
        "category": "gaming_entertainment",
        "angle": "A major game release becomes a cultural event beyond the gaming audience",
        "focus": "A crossover story about how games now function as mainstream entertainment launches.",
        "questions": [
            "Why is this release resonating so broadly?",
            "How are non-gaming audiences interacting with the title?",
            "What does the launch say about games as dominant entertainment?",
        ],
    },
    {
        "id": "ent_034",
        "category": "gaming_entertainment",
        "angle": "Live-service controversy sparks fan revolt over monetization and trust",
        "focus": "A business-and-fandom story about updates, microtransactions, and player loyalty.",
        "questions": [
            "What monetization decision triggered the backlash?",
            "How are developers communicating with players?",
            "Can a damaged live-service game recover community confidence?",
        ],
    },
    {
        "id": "ent_035",
        "category": "gaming_entertainment",
        "angle": "Video game adaptation finally breaks the curse and wins over critics",
        "focus": "A cross-media story about why some adaptations succeed where many failed.",
        "questions": [
            "What did the adaptation understand about the source material?",
            "How did it appeal to both fans and newcomers?",
            "Will the success trigger a new adaptation wave?",
        ],
    },
    {
        "id": "ent_036",
        "category": "theater_and_live_events",
        "angle": "Stage production becomes a must-see phenomenon through word of mouth alone",
        "focus": "A live performance story about organic momentum and cultural prestige.",
        "questions": [
            "What makes the production stand out so strongly?",
            "How are audiences discovering it?",
            "Can the demand expand beyond core theatergoers?",
        ],
    },
    {
        "id": "ent_037",
        "category": "theater_and_live_events",
        "angle": "Big-name star joins stage production and transforms its economics overnight",
        "focus": "A story about celebrity draw reshaping the scale and attention of live performance.",
        "questions": [
            "How much has the star changed ticket demand?",
            "What does the casting mean for the production's artistic identity?",
            "Are audiences coming for the show or the celebrity?",
        ],
    },
    {
        "id": "ent_038",
        "category": "theater_and_live_events",
        "angle": "Festival chaos becomes the defining story instead of the performances",
        "focus": "A live event story about logistics failure, fan anger, and brand damage.",
        "questions": [
            "What went wrong operationally?",
            "How are attendees and artists responding?",
            "Can organizers recover credibility after a messy event?",
        ],
    },
    {
        "id": "ent_039",
        "category": "industry_business",
        "angle": "Studio restructuring shows the entertainment business is in a defensive phase",
        "focus": "An industry story about layoffs, mergers, canceled projects, and shifting priorities.",
        "questions": [
            "What pressures are driving the restructuring?",
            "Which divisions or projects are being hit hardest?",
            "What does the move reveal about where the industry thinks growth still exists?",
        ],
    },
    {
        "id": "ent_040",
        "category": "industry_business",
        "angle": "Entertainment merger promises scale but raises fears of creative sameness",
        "focus": "A consolidation story about efficiency, bargaining power, and diminished diversity of output.",
        "questions": [
            "Why do executives say the merger is necessary?",
            "What creative risks come with concentration?",
            "How might audiences feel the effects over time?",
        ],
    },
    {
        "id": "ent_041",
        "category": "industry_business",
        "angle": "Layoffs in gaming, media, or film reveal the cost of overexpansion",
        "focus": "A labor story about what happens after boom-era hiring meets a colder market.",
        "questions": [
            "What assumptions from the growth era are now breaking down?",
            "Which workers are being hit first?",
            "How does creative output change when the business retreats?",
        ],
    },
    {
        "id": "ent_042",
        "category": "industry_business",
        "angle": "International markets become the real growth engine for entertainment giants",
        "focus": "A global strategy story about where audience expansion still looks strongest.",
        "questions": [
            "Which regions matter most to future growth?",
            "How are companies adapting content for global appeal?",
            "What tensions arise between global scale and local specificity?",
        ],
    },
    {
        "id": "ent_043",
        "category": "culture_and_trends",
        "angle": "Nostalgia wave reshapes what audiences want from entertainment",
        "focus": "A broader culture story about comfort viewing, revived aesthetics, and retro branding.",
        "questions": [
            "Why is nostalgia so commercially potent right now?",
            "Which eras or styles are being revived most aggressively?",
            "Does nostalgia offer cultural comfort or creative retreat?",
        ],
    },
    {
        "id": "ent_044",
        "category": "culture_and_trends",
        "angle": "One performance, speech, or viral clip turns an artist into a household name overnight",
        "focus": "A momentum story about how attention suddenly crystallizes around a single public moment.",
        "questions": [
            "What made the moment so shareable?",
            "How prepared was the artist or team for the surge in visibility?",
            "Can sudden fame be converted into a lasting career?",
        ],
    },
    {
        "id": "ent_045",
        "category": "culture_and_trends",
        "angle": "Audience fatigue with constant content leads to renewed demand for event entertainment",
        "focus": "A consumption story about how abundance can make scarcity and anticipation more valuable again.",
        "questions": [
            "Why are audiences gravitating toward event-style releases?",
            "What kinds of releases benefit from anticipation the most?",
            "Does too much content make viewers more selective?",
        ],
    },
    {
        "id": "ent_046",
        "category": "fashion_and_entertainment",
        "angle": "Red carpet moment becomes more discussed than the project being promoted",
        "focus": "A style-and-celebrity story about image as entertainment in its own right.",
        "questions": [
            "What about the look triggered so much attention?",
            "How do fashion moments extend publicity cycles?",
            "When does image overwhelm the underlying work?",
        ],
    },
    {
        "id": "ent_047",
        "category": "fashion_and_entertainment",
        "angle": "Designer-celebrity partnership turns branding into a cultural event",
        "focus": "A crossover story about fashion, fame, commerce, and identity.",
        "questions": [
            "Why is this partnership resonating with audiences?",
            "What does each side gain from the collaboration?",
            "How do fans interpret celebrity-brand alliances?",
        ],
    },
    {
        "id": "ent_048",
        "category": "comedy",
        "angle": "Comedian's controversial set sparks fight over offense, context, and audience expectation",
        "focus": "A comedy culture story about boundaries, intent, and reputational fallout.",
        "questions": [
            "What specifically drew criticism?",
            "How are fans and critics framing the issue differently?",
            "What does the controversy reveal about comedy's current cultural position?",
        ],
    },
    {
        "id": "ent_049",
        "category": "comedy",
        "angle": "Stand-up special becomes a breakout platform for a new comedic voice",
        "focus": "A discovery story about timing, style, and the search for fresh perspective.",
        "questions": [
            "What makes the comedian's voice feel distinct?",
            "How did the special reach a wider audience?",
            "Can breakout acclaim translate into sustained mainstream visibility?",
        ],
    },
    {
        "id": "ent_050",
        "category": "books_and_adaptations",
        "angle": "Bestseller adaptation ignites fight over faithfulness to the source",
        "focus": "A fandom and adaptation story about competing ideas of what a work should preserve.",
        "questions": [
            "What changes are fans objecting to most?",
            "Why did creators make those changes?",
            "What does the backlash reveal about adaptation culture?",
        ],
    },
    {
        "id": "ent_051",
        "category": "books_and_adaptations",
        "angle": "BookTok or online reading culture unexpectedly turns a novel into a screen property",
        "focus": "A platform-to-industry story about how niche enthusiasm becomes development fuel.",
        "questions": [
            "How did online reading communities create momentum?",
            "Why did the property suddenly look valuable to studios?",
            "Can internet-driven literary success survive adaptation?",
        ],
    },
    {
        "id": "ent_052",
        "category": "documentary",
        "angle": "Documentary becomes a public argument rather than just a film",
        "focus": "A nonfiction story where evidence, editing, and politics shape reception.",
        "questions": [
            "What claims or revelations are driving the debate?",
            "How are subjects or institutions pushing back?",
            "When does a documentary become an active participant in the story it tells?",
        ],
    },
    {
        "id": "ent_053",
        "category": "documentary",
        "angle": "True-crime series captures attention while raising ethical questions",
        "focus": "A nonfiction entertainment story about victim sensitivity, sensationalism, and public obsession.",
        "questions": [
            "Why is this case resonating so strongly with viewers?",
            "Are critics worried about exploitation or distortion?",
            "How do families and communities react to renewed attention?",
        ],
    },
    {
        "id": "ent_054",
        "category": "animation",
        "angle": "Animated project proves the format is not a niche but a broad creative engine",
        "focus": "A craft and audience story about animation as prestige art, family entertainment, and commercial force.",
        "questions": [
            "What distinguishes the project's visual or narrative approach?",
            "Who is the intended audience and who actually showed up?",
            "Does the success challenge old assumptions about animation?",
        ],
    },
    {
        "id": "ent_055",
        "category": "animation",
        "angle": "Voice casting and AI debates reshape the future of animated production",
        "focus": "A labor-and-technology story about performance, ownership, and the meaning of creative work.",
        "questions": [
            "What role is technology playing in the controversy?",
            "How are actors and studios framing the dispute?",
            "What might change in production practices going forward?",
        ],
    },
    {
        "id": "ent_056",
        "category": "labor_and_unions",
        "angle": "Writers, actors, or crew push back against changing economics of entertainment work",
        "focus": "A labor story about residuals, security, visibility, and power in a changing industry.",
        "questions": [
            "What are workers demanding most urgently?",
            "How have streaming and technology changed the labor equation?",
            "What production disruptions or compromises may follow?",
        ],
    },
    {
        "id": "ent_057",
        "category": "labor_and_unions",
        "angle": "Behind-the-scenes workers say glamour at the top hides precarity below",
        "focus": "An industry reality story about assistants, crew, freelancers, and unstable careers.",
        "questions": [
            "Which kinds of workers are under the most pressure?",
            "How does precarious work shape the projects audiences see?",
            "Why is this side of entertainment less visible to the public?",
        ],
    },
    {
        "id": "ent_058",
        "category": "international_entertainment",
        "angle": "Global hit from outside Hollywood forces the industry to rethink cultural hierarchy",
        "focus": "A cross-border story about language, export power, and shifting audience openness.",
        "questions": [
            "Why did this project break through internationally?",
            "How are domestic studios reacting to foreign success?",
            "Does the hit change assumptions about what can travel globally?",
        ],
    },
    {
        "id": "ent_059",
        "category": "international_entertainment",
        "angle": "Regional music, film, or television industry becomes an export powerhouse",
        "focus": "A growth story about how local creative ecosystems become global influences.",
        "questions": [
            "What infrastructure helped this industry scale internationally?",
            "How does local identity become a strength rather than a barrier?",
            "What lessons are other markets trying to copy?",
        ],
    },
    {
        "id": "ent_060",
        "category": "fan_culture",
        "angle": "Fan campaign shows audiences now expect to influence creative decisions directly",
        "focus": "A participation story about fandom as pressure group, marketing force, and community.",
        "questions": [
            "What are fans trying to change or save?",
            "How much influence do fan campaigns actually have?",
            "When does fan involvement become creatively distorting?",
        ],
    },
    {
        "id": "ent_061",
        "category": "fan_culture",
        "angle": "Convention, fan event, or leak cycle becomes essential to the entertainment calendar",
        "focus": "A hype-economy story about how fandom infrastructure drives anticipation and coverage.",
        "questions": [
            "What announcements or reveals are audiences expecting?",
            "How do studios and publishers use these events strategically?",
            "Why do leaks sometimes generate more attention than official promotion?",
        ],
    },
    {
        "id": "ent_062",
        "category": "technology_and_entertainment",
        "angle": "AI-generated entertainment raises the question of what audiences still value as human",
        "focus": "A frontier story about authorship, novelty, convenience, and unease.",
        "questions": [
            "Where is AI entering the entertainment pipeline first?",
            "How do creators and audiences react differently to AI-assisted work?",
            "What parts of entertainment remain most tied to human authenticity?",
        ],
    },
    {
        "id": "ent_063",
        "category": "technology_and_entertainment",
        "angle": "Virtual performers and digital likenesses blur the meaning of celebrity",
        "focus": "A future-fame story about identity, performance, and ownership.",
        "questions": [
            "Why are virtual or synthetic performers gaining attention?",
            "How do audiences relate to nontraditional celebrity figures?",
            "What legal and artistic questions follow digital likeness expansion?",
        ],
    },
    {
        "id": "ent_064",
        "category": "sports_entertainment_crossover",
        "angle": "Sports star crosses into entertainment and expands beyond athletic fame",
        "focus": "A crossover celebrity story about branding, charisma, and audience transfer.",
        "questions": [
            "What makes the athlete attractive to entertainment producers?",
            "How do fans respond when sports fame becomes media fame?",
            "Can crossover visibility outlast athletic peak years?",
        ],
    },
    {
        "id": "ent_065",
        "category": "sports_entertainment_crossover",
        "angle": "Entertainment event borrows from sports spectacle to capture attention",
        "focus": "A format story about how competition, live stakes, and event framing reshape entertainment.",
        "questions": [
            "What sports-like elements are being adopted?",
            "Why do audiences respond to spectacle and liveness?",
            "What does this mean for future event programming?",
        ],
    },
    {
        "id": "ent_066",
        "category": "meta_industry",
        "angle": "The real entertainment story is no longer just what gets made, but how attention gets organized",
        "focus": "A high-level industry and culture story about platforms, fandom, algorithms, and eventization.",
        "questions": [
            "Who has the most power over what audiences notice?",
            "How do hype, timing, and distribution shape cultural success?",
            "Is entertainment becoming more democratic or more controlled?",
        ],
    },
]
