from synthnews.prompts import Angle

ANGLES: list[Angle] = [
    {
        "id": "pol_001",
        "category": "elections",
        "angle": "Voter frustration reshapes the campaign landscape",
        "focus": "How dissatisfaction with institutions, prices, leadership, or daily life creates openings for new messages and candidates.",
        "questions": [
            "What are voters most frustrated about right now?",
            "Which candidates are channeling discontent most effectively?",
            "Is frustration leading to turnout, apathy, or political realignment?",
        ],
    },
    {
        "id": "pol_002",
        "category": "elections",
        "angle": "The battle for suburban swing voters",
        "focus": "Why suburban communities remain politically decisive and how parties tailor messages to them.",
        "questions": [
            "Which issues matter most in suburban districts?",
            "How are candidates balancing moderate and base-oriented messaging?",
            "What demographic shifts are changing suburban politics?",
        ],
    },
    {
        "id": "pol_003",
        "category": "elections",
        "angle": "Young voters are energized but not always aligned",
        "focus": "How younger voters shape political debate while remaining diverse in priorities and turnout behavior.",
        "questions": [
            "What issues most motivate younger voters?",
            "How do enthusiasm and actual turnout compare?",
            "Are parties adapting effectively to younger political expectations?",
        ],
    },
    {
        "id": "pol_004",
        "category": "elections",
        "angle": "Older voters remain the most dependable bloc",
        "focus": "How older citizens continue to influence elections through consistent turnout and issue discipline.",
        "questions": [
            "Which issues are most effective with older voters?",
            "How do candidates protect support among reliable voting blocs?",
            "What generational divides are most politically relevant?",
        ],
    },
    {
        "id": "pol_005",
        "category": "elections",
        "angle": "Turnout may matter more than persuasion",
        "focus": "Why modern campaigns increasingly focus on mobilizing known supporters rather than converting opponents.",
        "questions": [
            "Which side has the stronger turnout infrastructure?",
            "What local factors most affect turnout?",
            "How do campaigns identify and motivate infrequent voters?",
        ],
    },
    {
        "id": "pol_006",
        "category": "elections",
        "angle": "Independent voters become the most contested audience",
        "focus": "How loosely affiliated voters are courted by parties, candidates, and issue campaigns.",
        "questions": [
            "What persuades independent voters most effectively?",
            "How stable is the independent label in practice?",
            "Are independents truly centrist or simply politically detached?",
        ],
    },
    {
        "id": "pol_007",
        "category": "elections",
        "angle": "The primary fight before the general election",
        "focus": "How intraparty divisions shape candidates, messaging, and strategy before the broader contest begins.",
        "questions": [
            "Which factions have the most influence in the primary phase?",
            "How much do primary positions constrain general-election pivots?",
            "What does the primary reveal about the future direction of the party?",
        ],
    },
    {
        "id": "pol_008",
        "category": "elections",
        "angle": "Local races become national proxy battles",
        "focus": "How school boards, mayoral contests, and regional elections become stand-ins for national ideological fights.",
        "questions": [
            "Why are local elections drawing national attention?",
            "What outside groups are influencing smaller races?",
            "How do local issues get reframed through national narratives?",
        ],
    },
    {
        "id": "pol_009",
        "category": "campaigns",
        "angle": "Campaigns increasingly run as media operations",
        "focus": "How modern political campaigns resemble always-on content studios rather than traditional field-only organizations.",
        "questions": [
            "What kinds of content perform best politically?",
            "How do campaigns balance authenticity with message discipline?",
            "Are viral moments replacing traditional persuasion?",
        ],
    },
    {
        "id": "pol_010",
        "category": "campaigns",
        "angle": "Money floods the race but does it change minds?",
        "focus": "How campaign spending influences visibility, organization, and persuasion.",
        "questions": [
            "Where is political money being spent most aggressively?",
            "What kinds of spending actually move outcomes?",
            "When does fundraising strength become a self-fulfilling political signal?",
        ],
    },
    {
        "id": "pol_011",
        "category": "campaigns",
        "angle": "Small donors versus big donors",
        "focus": "How grassroots fundraising and elite financial backing create different kinds of political power.",
        "questions": [
            "What does the donor mix reveal about a candidate's coalition?",
            "Do small-dollar campaigns have strategic advantages?",
            "How do major donors influence priorities, directly or indirectly?",
        ],
    },
    {
        "id": "pol_012",
        "category": "campaigns",
        "angle": "Negative campaigning dominates attention",
        "focus": "Why attacks, warnings, and opponent framing remain central to political strategy.",
        "questions": [
            "What kinds of attacks are most effective?",
            "When does negativity backfire?",
            "How do voters process constant political conflict messaging?",
        ],
    },
    {
        "id": "pol_013",
        "category": "campaigns",
        "angle": "Candidate authenticity becomes a political weapon",
        "focus": "How voters judge whether candidates feel real, staged, scripted, or relatable.",
        "questions": [
            "What makes a politician seem authentic to supporters?",
            "Can over-managed campaigns damage trust?",
            "How much does authenticity outweigh policy detail?",
        ],
    },
    {
        "id": "pol_014",
        "category": "campaigns",
        "angle": "The politics of candidate age and stamina",
        "focus": "How public perceptions of energy, health, and generational fit shape campaigns.",
        "questions": [
            "How are candidates addressing concerns about age or readiness?",
            "Do voters treat age differently depending on party or ideology?",
            "What role does media amplification play in age narratives?",
        ],
    },
    {
        "id": "pol_015",
        "category": "governance",
        "angle": "Governing becomes harder in an era of permanent campaigning",
        "focus": "How leaders struggle to compromise when every move is evaluated through the next election cycle.",
        "questions": [
            "What incentives discourage bipartisan governance?",
            "How do politicians balance policy work with campaign pressures?",
            "What institutions are most affected by perpetual election mode?",
        ],
    },
    {
        "id": "pol_016",
        "category": "governance",
        "angle": "Legislative gridlock becomes its own political message",
        "focus": "How inaction, delay, and stalemate are used both as criticism and as strategy.",
        "questions": [
            "Who benefits politically from dysfunction?",
            "How do leaders explain stalemate to voters?",
            "When does gridlock create electoral consequences?",
        ],
    },
    {
        "id": "pol_017",
        "category": "governance",
        "angle": "Executive power expands when legislatures stall",
        "focus": "How leaders rely more heavily on executive tools when formal lawmaking slows down.",
        "questions": [
            "What actions are increasingly being done without legislation?",
            "How are checks and balances responding?",
            "What long-term precedents are being created?",
        ],
    },
    {
        "id": "pol_018",
        "category": "governance",
        "angle": "Political promises collide with governing reality",
        "focus": "What happens when campaign rhetoric meets budget limits, institutions, and legal constraints.",
        "questions": [
            "Which promises prove hardest to implement?",
            "How do politicians explain compromises to supporters?",
            "What does this gap mean for public trust?",
        ],
    },
    {
        "id": "pol_019",
        "category": "parties",
        "angle": "Political parties become broader but less coherent coalitions",
        "focus": "How major parties contain more internal ideological tension than ever.",
        "questions": [
            "Which factions are most at odds within each party?",
            "How do party leaders manage internal contradictions?",
            "What issues most clearly expose coalition fractures?",
        ],
    },
    {
        "id": "pol_020",
        "category": "parties",
        "angle": "The center struggles to hold in polarized times",
        "focus": "How moderate politicians operate when party incentives reward sharper ideological positioning.",
        "questions": [
            "What happens to politicians who try to remain centrist?",
            "Are moderate voters underrepresented in party primaries?",
            "Can centrist politics still generate enthusiasm?",
        ],
    },
    {
        "id": "pol_021",
        "category": "parties",
        "angle": "Populist rhetoric reshapes traditional party brands",
        "focus": "How anti-elite messaging changes the language and strategy of mainstream political actors.",
        "questions": [
            "Which party leaders are borrowing populist themes?",
            "How does anti-establishment language affect governance expectations?",
            "Can populism coexist with institutional leadership?",
        ],
    },
    {
        "id": "pol_022",
        "category": "institutions",
        "angle": "Trust in institutions becomes a core political fault line",
        "focus": "How confidence or skepticism toward courts, legislatures, media, and public agencies drives political behavior.",
        "questions": [
            "Which institutions retain the most trust?",
            "What events most sharply erode confidence?",
            "How do politicians use distrust as a mobilizing tool?",
        ],
    },
    {
        "id": "pol_023",
        "category": "institutions",
        "angle": "Courts take a bigger role in political conflict",
        "focus": "How legal institutions increasingly resolve disputes that elected officials cannot or will not settle.",
        "questions": [
            "Why are more major political battles ending up in court?",
            "How do legal decisions shape electoral narratives?",
            "What does judicialization mean for democratic legitimacy?",
        ],
    },
    {
        "id": "pol_024",
        "category": "institutions",
        "angle": "Civil service and bureaucracy become political targets",
        "focus": "How administrative agencies are drawn into partisan contests over legitimacy, competence, and control.",
        "questions": [
            "Why are bureaucratic institutions becoming more politically visible?",
            "How do reform proposals differ from attempts at control?",
            "What happens when public administration becomes openly partisan terrain?",
        ],
    },
    {
        "id": "pol_025",
        "category": "media",
        "angle": "Political narratives now spread faster than fact-checking",
        "focus": "How modern media ecosystems reward speed, emotion, and partisan framing.",
        "questions": [
            "What kinds of political claims spread most rapidly?",
            "How do parties exploit fragmented media environments?",
            "Can corrections catch up once a narrative hardens?",
        ],
    },
    {
        "id": "pol_026",
        "category": "media",
        "angle": "Partisan media shapes not just opinion but reality",
        "focus": "How different audiences inhabit fundamentally different understandings of the same political events.",
        "questions": [
            "How much do media ecosystems shape voter identity?",
            "What stories look completely different across partisan outlets?",
            "Can shared public understanding still be rebuilt?",
        ],
    },
    {
        "id": "pol_027",
        "category": "media",
        "angle": "The rise of political influencers and independent commentators",
        "focus": "How nontraditional media figures now rival established outlets in shaping political discourse.",
        "questions": [
            "Who trusts influencers more than traditional media?",
            "How do politicians adapt to creator-driven communication?",
            "What accountability standards apply to political creators?",
        ],
    },
    {
        "id": "pol_028",
        "category": "media",
        "angle": "Debates matter less as persuasion and more as performance",
        "focus": "How candidate debates increasingly generate clips, symbols, and momentum rather than detailed policy understanding.",
        "questions": [
            "What moments define debates in the public mind?",
            "Do debates still move undecided voters?",
            "How much are debates designed for post-event media circulation?",
        ],
    },
    {
        "id": "pol_029",
        "category": "technology",
        "angle": "AI and synthetic media complicate political trust",
        "focus": "How generated text, images, audio, and video affect campaigning, persuasion, and public confidence.",
        "questions": [
            "What political uses of synthetic media worry experts most?",
            "How can voters distinguish authentic from manipulated content?",
            "How are campaigns and regulators responding?",
        ],
    },
    {
        "id": "pol_030",
        "category": "technology",
        "angle": "Microtargeting changes the language of politics",
        "focus": "How campaigns tailor different messages to different audiences using data-driven communication tools.",
        "questions": [
            "How precise can modern political targeting become?",
            "What are the ethical limits of personalized persuasion?",
            "Does microtargeting weaken shared democratic debate?",
        ],
    },
    {
        "id": "pol_031",
        "category": "technology",
        "angle": "Political organizing goes platform-native",
        "focus": "How campaigns use messaging apps, livestreams, short video, and digital communities as core organizing tools.",
        "questions": [
            "Which platforms are most politically influential?",
            "How do digital communities translate into real-world action?",
            "What kinds of messages work best in platform-native politics?",
        ],
    },
    {
        "id": "pol_032",
        "category": "identity",
        "angle": "Identity remains one of the strongest forces in modern politics",
        "focus": "How culture, region, religion, language, ethnicity, or class shape political belonging and conflict.",
        "questions": [
            "Which identities are most politically mobilized right now?",
            "How do parties build broad coalitions across identity lines?",
            "When does identity outweigh policy in shaping votes?",
        ],
    },
    {
        "id": "pol_033",
        "category": "identity",
        "angle": "Cultural issues often overpower economic issues",
        "focus": "Why symbolic conflicts can drive stronger political engagement than material concerns.",
        "questions": [
            "Which cultural issues are becoming electoral litmus tests?",
            "Why do symbolic issues mobilize voters so effectively?",
            "How do parties decide which cultural battles to emphasize?",
        ],
    },
    {
        "id": "pol_034",
        "category": "identity",
        "angle": "Class politics is reappearing in new forms",
        "focus": "How inequality, elite distrust, and economic frustration are being translated into new political identities.",
        "questions": [
            "Which voters feel most politically unrepresented by economic elites?",
            "How are class grievances being framed by different parties?",
            "Is class replacing or merging with other identity conflicts?",
        ],
    },
    {
        "id": "pol_035",
        "category": "public_opinion",
        "angle": "Polls show movement, but what do they really capture?",
        "focus": "How polling reflects sentiment, uncertainty, turnout likelihood, and media influence rather than fixed outcomes.",
        "questions": [
            "What are the biggest limits of modern polling?",
            "How do likely-voter models shape narratives?",
            "Why do campaign teams often see the same polls differently?",
        ],
    },
    {
        "id": "pol_036",
        "category": "public_opinion",
        "angle": "Intensity matters as much as majority opinion",
        "focus": "How small but highly motivated groups can shape policy and elections disproportionately.",
        "questions": [
            "Which issues have the most intensity gap between supporters and opponents?",
            "How do parties respond to highly energized minorities?",
            "When does issue intensity outweigh broad but shallow support?",
        ],
    },
    {
        "id": "pol_037",
        "category": "public_opinion",
        "angle": "Voters want change but disagree on what kind",
        "focus": "How broad appetite for political change masks very different visions of reform or restoration.",
        "questions": [
            "What kinds of change are different voter blocs asking for?",
            "How do politicians define change in strategically vague ways?",
            "What happens when a single election becomes a vessel for conflicting hopes?",
        ],
    },
    {
        "id": "pol_038",
        "category": "policy",
        "angle": "Economic anxiety becomes political fuel",
        "focus": "How inflation, wages, debt, and affordability concerns shape ideology and voting behavior.",
        "questions": [
            "Which economic pressures most influence political attitudes?",
            "How are parties translating economic pain into campaign language?",
            "Do voters blame local leaders, national leaders, or broader systems?",
        ],
    },
    {
        "id": "pol_039",
        "category": "policy",
        "angle": "Housing becomes one of the defining political issues",
        "focus": "How rent, home prices, zoning, development, and affordability drive political conflict.",
        "questions": [
            "Which politicians are most effectively addressing housing frustration?",
            "How do local housing debates scale into national politics?",
            "Why is housing reform so difficult even when demand for change is high?",
        ],
    },
    {
        "id": "pol_040",
        "category": "policy",
        "angle": "Crime politics is as much about perception as statistics",
        "focus": "How safety, disorder, fear, and lived experience shape public reaction beyond official data.",
        "questions": [
            "How do politicians frame crime when data and perception diverge?",
            "What kinds of incidents most shift public opinion?",
            "How do local experiences influence national law-and-order narratives?",
        ],
    },
    {
        "id": "pol_041",
        "category": "policy",
        "angle": "Migration becomes a test of state capacity",
        "focus": "How immigration and border debates become arguments about law, identity, labor, and government competence.",
        "questions": [
            "What aspects of migration policy create the most political pressure?",
            "How do leaders balance enforcement, humanitarianism, and economic need?",
            "Why does migration so easily become a symbolic political issue?",
        ],
    },
    {
        "id": "pol_042",
        "category": "policy",
        "angle": "Education policy becomes a cultural and parental battleground",
        "focus": "How curriculum, standards, school governance, and parental rights debates intensify political polarization.",
        "questions": [
            "Which education issues most mobilize voters?",
            "Why have school systems become so politically visible?",
            "How are local education fights influencing party strategy?",
        ],
    },
    {
        "id": "pol_043",
        "category": "policy",
        "angle": "Healthcare politics persists even when reform stalls",
        "focus": "How healthcare remains politically potent through cost, access, staffing, and system trust.",
        "questions": [
            "Which healthcare grievances resonate most strongly with voters?",
            "Why does healthcare stay central even without sweeping legislative change?",
            "How do different parties frame health system problems?",
        ],
    },
    {
        "id": "pol_044",
        "category": "policy",
        "angle": "Climate politics enters everyday governance",
        "focus": "How environmental questions become linked to jobs, energy prices, infrastructure, and local risk.",
        "questions": [
            "Which climate policies generate the most political conflict?",
            "How are leaders framing climate action in economic terms?",
            "What local events make climate politics feel immediate to voters?",
        ],
    },
    {
        "id": "pol_045",
        "category": "policy",
        "angle": "Industrial policy returns as a political identity project",
        "focus": "How investment, reshoring, subsidies, and manufacturing are framed as political renewal.",
        "questions": [
            "Why are politicians embracing industrial policy language again?",
            "How do voters respond to promises of national rebuilding?",
            "What risks emerge when industrial policy becomes symbolic as well as economic?",
        ],
    },
    {
        "id": "pol_046",
        "category": "foreign_policy",
        "angle": "Foreign policy becomes more domestically political",
        "focus": "How wars, alliances, trade, and geopolitical rivalry increasingly divide domestic electorates.",
        "questions": [
            "Which international issues most strongly affect domestic politics?",
            "How do leaders frame foreign policy in terms voters care about?",
            "When do overseas conflicts become defining election themes?",
        ],
    },
    {
        "id": "pol_047",
        "category": "foreign_policy",
        "angle": "National security is now economic, digital, and military at once",
        "focus": "How cybersecurity, supply chains, infrastructure, and technology are folded into security politics.",
        "questions": [
            "What new issues are now treated as national security concerns?",
            "How are politicians expanding the idea of strategic vulnerability?",
            "What policies gain support when framed through security language?",
        ],
    },
    {
        "id": "pol_048",
        "category": "foreign_policy",
        "angle": "Trade policy becomes a question of sovereignty",
        "focus": "How tariffs, supply chains, and economic dependence are framed politically as issues of national control.",
        "questions": [
            "Which industries and regions respond most strongly to trade nationalism?",
            "How are parties balancing consumer cost against national resilience?",
            "What alliances are strained by sovereignty-focused trade policy?",
        ],
    },
    {
        "id": "pol_049",
        "category": "democracy",
        "angle": "Election integrity debates become a permanent feature of politics",
        "focus": "How trust in ballots, counting, administration, and outcomes has become politically contested in itself.",
        "questions": [
            "What drives doubts about election administration?",
            "How are governments trying to build confidence in outcomes?",
            "What political incentives keep integrity debates alive?",
        ],
    },
    {
        "id": "pol_050",
        "category": "democracy",
        "angle": "Democratic norms are tested in small decisions as much as big crises",
        "focus": "How routine institutional behavior can gradually strengthen or weaken democratic culture.",
        "questions": [
            "Which small norm violations have outsized long-term consequences?",
            "How do leaders justify bending precedent?",
            "When do voters begin to see procedural erosion as politically important?",
        ],
    },
    {
        "id": "pol_051",
        "category": "democracy",
        "angle": "Political losers increasingly resist the meaning of losing",
        "focus": "How the refusal to accept defeat changes party behavior, institutions, and public trust.",
        "questions": [
            "What incentives encourage leaders to contest unfavorable results?",
            "How do supporters react to disputed legitimacy narratives?",
            "What are the institutional costs of permanent post-election conflict?",
        ],
    },
    {
        "id": "pol_052",
        "category": "law",
        "angle": "Legal accountability becomes a political force of its own",
        "focus": "How investigations, prosecutions, and court cases affect candidates, parties, and public trust.",
        "questions": [
            "How do legal troubles change a politician's support base?",
            "When does accountability strengthen democratic legitimacy?",
            "How do parties frame legal scrutiny as justice or persecution?",
        ],
    },
    {
        "id": "pol_053",
        "category": "law",
        "angle": "Ethics scandals test partisan loyalty",
        "focus": "How corruption allegations or misconduct claims expose the limits of accountability in polarized politics.",
        "questions": [
            "What kinds of scandals still move public opinion?",
            "How do parties decide whether to defend or distance themselves?",
            "Does scandal fatigue reduce consequences for misconduct?",
        ],
    },
    {
        "id": "pol_054",
        "category": "law",
        "angle": "Constitutional questions are no longer abstract",
        "focus": "How disputes over powers, rights, and institutional authority move from legal theory into everyday politics.",
        "questions": [
            "Which constitutional issues now resonate with ordinary voters?",
            "How do legal arguments become campaign messages?",
            "What happens when constitutional interpretation splits sharply along partisan lines?",
        ],
    },
    {
        "id": "pol_055",
        "category": "regional_politics",
        "angle": "The urban-rural divide deepens political polarization",
        "focus": "How geography shapes attitudes toward culture, economy, government, and identity.",
        "questions": [
            "Which issues most sharply divide urban and rural voters?",
            "How do parties perform translation between geographic political cultures?",
            "What policies mean different things in different places?",
        ],
    },
    {
        "id": "pol_056",
        "category": "regional_politics",
        "angle": "Regional political identity becomes stronger than national messaging",
        "focus": "How local history, economy, and culture can overpower centralized party strategy.",
        "questions": [
            "Which regions resist national political trends most strongly?",
            "How do candidates localize national campaigns?",
            "When does regional distinctiveness become politically decisive?",
        ],
    },
    {
        "id": "pol_057",
        "category": "regional_politics",
        "angle": "State and provincial leaders become national political figures",
        "focus": "How regional executives gain influence by acting as counterweights, innovators, or ideological symbols.",
        "questions": [
            "What makes certain regional leaders break into national relevance?",
            "How do they use local governance as a political stage?",
            "Can regional success translate into broader political power?",
        ],
    },
    {
        "id": "pol_058",
        "category": "grassroots",
        "angle": "Grassroots activism pressures parties from below",
        "focus": "How movements, volunteers, and local organizers force institutions to adapt or react.",
        "questions": [
            "Which movements are reshaping party agendas?",
            "How do grassroots groups translate energy into policy influence?",
            "When do movements get absorbed by the institutions they challenge?",
        ],
    },
    {
        "id": "pol_059",
        "category": "grassroots",
        "angle": "Protest politics moves between the street and the ballot box",
        "focus": "How public demonstrations influence legislation, campaigns, and party behavior.",
        "questions": [
            "What makes protest movements politically durable?",
            "How do parties respond when movements refuse easy alignment?",
            "When do protests convert into electoral or legislative change?",
        ],
    },
    {
        "id": "pol_060",
        "category": "grassroots",
        "angle": "Volunteer networks still matter in the digital age",
        "focus": "Why door-knocking, community presence, and local trust remain important alongside online outreach.",
        "questions": [
            "What kinds of races are most affected by volunteer intensity?",
            "How do grassroots networks build trust that ads cannot?",
            "Can field operations still outperform digital-only campaigning?",
        ],
    },
    {
        "id": "pol_061",
        "category": "leadership",
        "angle": "Political leadership is now judged minute by minute",
        "focus": "How leaders operate under continuous commentary, clip circulation, and rapid reaction.",
        "questions": [
            "How does constant scrutiny change decision-making?",
            "What kinds of leadership style perform best in always-on politics?",
            "Does fast judgment make strategic governance harder?",
        ],
    },
    {
        "id": "pol_062",
        "category": "leadership",
        "angle": "Strongman style versus consensus style",
        "focus": "How voters and parties respond differently to forceful centralizing leaders and coalition-builders.",
        "questions": [
            "What conditions favor decisive, dominant leadership?",
            "When do consensus styles appear weak or responsible?",
            "How do media narratives amplify these contrasts?",
        ],
    },
    {
        "id": "pol_063",
        "category": "leadership",
        "angle": "Charisma can outrun organization, but not forever",
        "focus": "How personality-driven politics succeeds, and where it runs into structural limits.",
        "questions": [
            "How much can a charismatic candidate overcome institutional weakness?",
            "What eventually matters more: personality or party machinery?",
            "When does charisma become a liability?",
        ],
    },
    {
        "id": "pol_064",
        "category": "gender_and_representation",
        "angle": "Representation matters, but it does not settle ideology",
        "focus": "How gender, background, and identity representation interact with substantive political disagreement.",
        "questions": [
            "How do voters think about symbolic versus policy representation?",
            "What expectations are placed on politicians seen as historic or trailblazing?",
            "Can representation broaden coalitions without flattening conflict?",
        ],
    },
    {
        "id": "pol_065",
        "category": "gender_and_representation",
        "angle": "Women in politics still face distinct scrutiny",
        "focus": "How political judgment can differ around tone, appearance, authority, and electability.",
        "questions": [
            "What double standards remain visible in political coverage?",
            "How do candidates adapt to gendered expectations?",
            "What progress has been made and what patterns persist?",
        ],
    },
    {
        "id": "pol_066",
        "category": "youth_and_generational_change",
        "angle": "A generational handoff is underway but incomplete",
        "focus": "How younger politicians push new priorities while older leadership structures remain dominant.",
        "questions": [
            "Which issues most clearly mark generational change?",
            "How are younger leaders building influence inside established parties?",
            "What tensions emerge between political seniority and renewal?",
        ],
    },
    {
        "id": "pol_067",
        "category": "youth_and_generational_change",
        "angle": "Political socialization now happens online first",
        "focus": "How younger citizens encounter politics through creators, memes, algorithms, and communities instead of traditional institutions.",
        "questions": [
            "What shapes early political identity in digital environments?",
            "How do parties compete in spaces they do not fully control?",
            "Does online-first political learning deepen engagement or simplify it?",
        ],
    },
    {
        "id": "pol_068",
        "category": "polarization",
        "angle": "Polarization is emotional as much as ideological",
        "focus": "How political opponents are seen not just as wrong, but as threatening, alien, or morally suspect.",
        "questions": [
            "What drives emotional hostility across party lines?",
            "How do politicians benefit from affective polarization?",
            "Can issue agreement exist alongside social mistrust?",
        ],
    },
    {
        "id": "pol_069",
        "category": "polarization",
        "angle": "Compromise becomes politically dangerous",
        "focus": "How incentives inside parties and media ecosystems punish leaders who negotiate across divides.",
        "questions": [
            "Why do politicians fear being seen as weak by their own base?",
            "What kinds of compromise are still politically survivable?",
            "How does this affect legislative output and public expectations?",
        ],
    },
    {
        "id": "pol_070",
        "category": "polarization",
        "angle": "National identity itself becomes politically contested",
        "focus": "How rival political camps imagine the nation differently in values, history, and future direction.",
        "questions": [
            "What competing national stories are most politically powerful?",
            "How do parties wrap policy proposals in identity language?",
            "Why do symbolic national debates become so intense?",
        ],
    },
    {
        "id": "pol_071",
        "category": "disinformation",
        "angle": "Falsehood spreads because it fits existing loyalties",
        "focus": "Why misinformation often succeeds through identity reinforcement more than factual plausibility.",
        "questions": [
            "What kinds of political claims are most believable to partisans?",
            "How do loyalty and distrust interact with misinformation?",
            "Can correction strategies work without rebuilding trust first?",
        ],
    },
    {
        "id": "pol_072",
        "category": "disinformation",
        "angle": "Conspiracy narratives become political organizing tools",
        "focus": "How fringe or semi-mainstream narratives create community, intensity, and political identity.",
        "questions": [
            "Why do conspiracy narratives persist even after debunking?",
            "How do politicians choose whether to amplify or distance themselves from them?",
            "What social needs do such narratives satisfy?",
        ],
    },
    {
        "id": "pol_073",
        "category": "international_politics",
        "angle": "Democracy versus authoritarianism becomes a political frame at home and abroad",
        "focus": "How ideological rivalry between systems shapes domestic rhetoric and foreign alignment.",
        "questions": [
            "How often is foreign rivalry used to justify domestic policy shifts?",
            "What audiences respond most strongly to this framing?",
            "Does values-based rhetoric produce durable political consensus?",
        ],
    },
    {
        "id": "pol_074",
        "category": "international_politics",
        "angle": "Geopolitical shocks reorder domestic political priorities",
        "focus": "How international crises suddenly elevate issues once considered secondary.",
        "questions": [
            "Which foreign events most strongly change domestic agendas?",
            "How do leaders use external crises to consolidate support?",
            "What policies gain momentum when global instability rises?",
        ],
    },
    {
        "id": "pol_075",
        "category": "public_services",
        "angle": "Politics is increasingly judged through service delivery",
        "focus": "How transit, healthcare access, schools, housing permits, and administrative competence become political verdicts.",
        "questions": [
            "Which service failures are most politically damaging?",
            "How do voters distinguish ideology from competence?",
            "Can efficient delivery rebuild trust across partisan lines?",
        ],
    },
    {
        "id": "pol_076",
        "category": "public_services",
        "angle": "Government competence becomes a campaign issue in itself",
        "focus": "How voters judge whether institutions can actually execute policy rather than merely promise it.",
        "questions": [
            "What visible signs make governments seem competent or ineffective?",
            "How do politicians communicate managerial seriousness?",
            "Why is competence often harder to campaign on than outrage?",
        ],
    },
    {
        "id": "pol_077",
        "category": "urban_politics",
        "angle": "Cities become laboratories of ideological governance",
        "focus": "How urban leaders test policy models on housing, transit, policing, climate, and inequality.",
        "questions": [
            "Which city policies are shaping national political debates?",
            "How do urban successes and failures get interpreted ideologically?",
            "Why are mayors increasingly national political figures?",
        ],
    },
    {
        "id": "pol_078",
        "category": "urban_politics",
        "angle": "Downtown decline becomes a political symbol",
        "focus": "How empty offices, visible disorder, weak retail, or stalled recovery shape narratives about leadership and social order.",
        "questions": [
            "How are politicians using downtown conditions as proof of broader arguments?",
            "What explains the gap between perception and data in urban debates?",
            "Which policies are pitched as urban revival solutions?",
        ],
    },
    {
        "id": "pol_079",
        "category": "rural_politics",
        "angle": "Rural communities see politics as recognition as much as policy",
        "focus": "How symbolic respect, cultural visibility, and perceived neglect drive political identity outside major urban areas.",
        "questions": [
            "Why do recognition and respect matter politically in rural regions?",
            "Which parties speak most effectively to rural grievance?",
            "How do material and symbolic concerns reinforce each other?",
        ],
    },
    {
        "id": "pol_080",
        "category": "rural_politics",
        "angle": "Resource politics remains central outside metropolitan centers",
        "focus": "How energy, land use, agriculture, and extraction shape regional political alignments.",
        "questions": [
            "Which resource sectors most strongly shape political identity?",
            "How do environmental and economic arguments collide locally?",
            "Why do resource debates often become wider cultural conflicts?",
        ],
    },
    {
        "id": "pol_081",
        "category": "constitutional_order",
        "angle": "Federalism and local autonomy become ideological battlegrounds",
        "focus": "How fights over who should decide policy reveal deeper conflicts over sovereignty and democratic legitimacy.",
        "questions": [
            "Which issues generate the sharpest disputes over local versus central authority?",
            "How do parties change their federalism arguments depending on who governs where?",
            "What does decentralization solve and what does it complicate?",
        ],
    },
    {
        "id": "pol_082",
        "category": "constitutional_order",
        "angle": "Emergency powers raise long-term political questions",
        "focus": "How extraordinary authority used during crises can alter expectations of government power afterward.",
        "questions": [
            "When do temporary emergency measures become normalized?",
            "How do citizens evaluate necessity versus overreach?",
            "What safeguards prevent exceptional power from becoming routine?",
        ],
    },
    {
        "id": "pol_083",
        "category": "political_culture",
        "angle": "Politics is increasingly a lifestyle signal",
        "focus": "How political affiliation shapes consumer choices, social circles, media habits, and cultural expression.",
        "questions": [
            "How visible has political identity become in daily life?",
            "What products, places, or symbols now carry partisan meaning?",
            "Does lifestyle politics intensify polarization beyond institutions?",
        ],
    },
    {
        "id": "pol_084",
        "category": "political_culture",
        "angle": "Humor, memes, and irony become tools of political belonging",
        "focus": "How comedy and participatory culture shape the language of modern politics.",
        "questions": [
            "What kinds of political humor travel fastest online?",
            "How do memes reinforce in-group identity?",
            "Can ironic politics still translate into serious civic engagement?",
        ],
    },
    {
        "id": "pol_085",
        "category": "strategy",
        "angle": "The smartest campaigns define the stakes before opponents do",
        "focus": "How political actors try to set the meaning of the election early and repeatedly.",
        "questions": [
            "What master narratives are campaigns trying to lock in?",
            "How do successful candidates simplify complex stakes?",
            "What happens when opposing sides tell totally different election stories?",
        ],
    },
    {
        "id": "pol_086",
        "category": "strategy",
        "angle": "Issue ownership still shapes modern contests",
        "focus": "How parties benefit when elections center on issues they are trusted more to handle.",
        "questions": [
            "Which parties are seen as strongest on which issues?",
            "How do candidates try to shift attention onto favorable terrain?",
            "Can strong issue ownership survive repeated governing failures?",
        ],
    },
    {
        "id": "pol_087",
        "category": "strategy",
        "angle": "Symbolic politics often outruns substantive policy",
        "focus": "How gestures, rhetoric, and visible conflicts can matter more than technical policy detail.",
        "questions": [
            "Why do symbolic actions satisfy supporters even without material change?",
            "How do politicians convert symbolism into durable support?",
            "When do voters eventually demand more than symbolic alignment?",
        ],
    },
    {
        "id": "pol_088",
        "category": "reform",
        "angle": "Calls for political reform rise whenever trust falls",
        "focus": "How moments of public frustration revive debates about rules, transparency, and institutional redesign.",
        "questions": [
            "Which reforms gain traction when trust declines?",
            "Are reform agendas sincere, strategic, or both?",
            "What kinds of reform are easiest to campaign on but hardest to enact?",
        ],
    },
    {
        "id": "pol_089",
        "category": "reform",
        "angle": "Electoral system reform gains attention when outcomes feel distorted",
        "focus": "How dissatisfaction with representation or vote translation sparks institutional debate.",
        "questions": [
            "What election outcomes create the most reform pressure?",
            "Which groups benefit from keeping the current rules?",
            "Can reform movements sustain momentum beyond one controversy?",
        ],
    },
    {
        "id": "pol_090",
        "category": "reform",
        "angle": "Transparency promises collide with opaque power",
        "focus": "How calls for openness run up against informal influence, back-channel negotiation, and institutional self-protection.",
        "questions": [
            "What forms of political opacity frustrate voters most?",
            "How much transparency is realistic in high-level governance?",
            "What remains hidden even in systems that promise openness?",
        ],
    },
]
