from synthnews.prompts import Angle


ANGLES: list[Angle] = [
    {
        "id": "st_001",
        "category": "artificial_intelligence",
        "angle": "AI tools move from novelty to workplace infrastructure",
        "focus": "How artificial intelligence systems are becoming embedded in everyday business and institutional workflows.",
        "questions": [
            "Which types of organizations are adopting AI fastest?",
            "What tasks are being delegated to AI first?",
            "Where are the biggest gaps between hype and practical deployment?",
        ],
    },
    {
        "id": "st_002",
        "category": "artificial_intelligence",
        "angle": "The hidden cost of training bigger AI models",
        "focus": "The financial, energy, and infrastructure demands behind increasingly large AI systems.",
        "questions": [
            "Who can still afford to build frontier-scale models?",
            "How much compute is becoming concentrated among a few firms?",
            "What tradeoffs are emerging between performance and cost?",
        ],
    },
    {
        "id": "st_003",
        "category": "artificial_intelligence",
        "angle": "Generative AI changes expectations for creative work",
        "focus": "How text, image, audio, and video generation tools alter the economics of media production.",
        "questions": [
            "Which creative jobs are most affected first?",
            "How are studios and agencies incorporating generative tools?",
            "Where does human craftsmanship still command premium value?",
        ],
    },
    {
        "id": "st_004",
        "category": "artificial_intelligence",
        "angle": "AI copilots become the new software layer",
        "focus": "The emergence of assistive AI interfaces inside productivity tools, development environments, and business platforms.",
        "questions": [
            "Which categories of software are being reshaped by copilots?",
            "How are users adapting to conversational interfaces?",
            "What limits keep copilots from replacing core expertise?",
        ],
    },
    {
        "id": "st_005",
        "category": "artificial_intelligence",
        "angle": "The race to build domain-specific AI",
        "focus": "Why specialized models for law, medicine, finance, and engineering are attracting intense attention.",
        "questions": [
            "What advantages do domain-specific systems have over general models?",
            "How much data quality matters more than model size?",
            "Which industries are most open to specialized AI workflows?",
        ],
    },
    {
        "id": "st_006",
        "category": "artificial_intelligence",
        "angle": "Synthetic content blurs the line between real and generated",
        "focus": "How AI-produced media complicates trust in images, audio, and online information.",
        "questions": [
            "What tools exist to detect synthetic content?",
            "How are platforms responding to generated media at scale?",
            "What happens when audiences stop trusting even authentic material?",
        ],
    },
    {
        "id": "st_007",
        "category": "artificial_intelligence",
        "angle": "AI safety efforts struggle to keep up with capability gains",
        "focus": "Whether alignment, interpretability, and control research can scale alongside rapid model progress.",
        "questions": [
            "Which technical safety problems remain unresolved?",
            "How are labs balancing product launches with caution?",
            "What risks worry researchers most in near-term deployments?",
        ],
    },
    {
        "id": "st_008",
        "category": "artificial_intelligence",
        "angle": "The data pipeline behind AI becomes its own battleground",
        "focus": "How access to data, licensing, and training material shapes the next phase of AI competition.",
        "questions": [
            "Who owns the inputs used to train modern AI systems?",
            "How are companies securing proprietary datasets?",
            "Will synthetic data reduce dependence on real-world corpora?",
        ],
    },
    {
        "id": "st_009",
        "category": "computing",
        "angle": "A new chip cycle transforms the technology sector",
        "focus": "How demand for advanced processors is reshaping computing strategy across industries.",
        "questions": [
            "Which sectors are driving the most chip demand?",
            "How are supply bottlenecks influencing product roadmaps?",
            "What new business models depend on specialized hardware?",
        ],
    },
    {
        "id": "st_010",
        "category": "computing",
        "angle": "Edge computing moves intelligence closer to the device",
        "focus": "Why more processing is happening outside centralized data centers.",
        "questions": [
            "What use cases benefit most from local inference?",
            "How do privacy and latency drive edge adoption?",
            "Which devices are becoming unexpectedly powerful computing platforms?",
        ],
    },
    {
        "id": "st_011",
        "category": "computing",
        "angle": "The comeback of efficient computing",
        "focus": "Why power usage, thermal limits, and cost are making efficiency a competitive advantage again.",
        "questions": [
            "How are hardware designers optimizing for performance per watt?",
            "Which software techniques reduce compute waste?",
            "Why is efficiency becoming strategic rather than merely technical?",
        ],
    },
    {
        "id": "st_012",
        "category": "computing",
        "angle": "The operating system fades while the cloud platform expands",
        "focus": "How local software gives way to service layers distributed across devices and data centers.",
        "questions": [
            "Are users becoming less aware of the underlying operating system?",
            "What functions are increasingly cloud-dependent?",
            "How does this shift affect ownership and control of computing?",
        ],
    },
    {
        "id": "st_013",
        "category": "cybersecurity",
        "angle": "Cyberattacks become a constant cost of digital life",
        "focus": "How organizations adapt to the expectation of continuous cyber threat exposure.",
        "questions": [
            "Which sectors are most frequently targeted?",
            "How are boards and executives changing security priorities?",
            "What defensive habits are proving most effective?",
        ],
    },
    {
        "id": "st_014",
        "category": "cybersecurity",
        "angle": "Ransomware evolves into an industrialized ecosystem",
        "focus": "The business model behind extortion attacks and how defenders are responding.",
        "questions": [
            "How are ransomware groups professionalizing their operations?",
            "What weaknesses make organizations easy targets?",
            "Are law enforcement and insurers changing attacker incentives?",
        ],
    },
    {
        "id": "st_015",
        "category": "cybersecurity",
        "angle": "AI changes both sides of the cybersecurity arms race",
        "focus": "How machine learning is being used to attack, detect, and respond faster.",
        "questions": [
            "What new threats emerge when attackers automate with AI?",
            "How are defenders using AI to reduce analyst workload?",
            "Does AI meaningfully improve security, or mostly increase complexity?",
        ],
    },
    {
        "id": "st_016",
        "category": "cybersecurity",
        "angle": "Critical infrastructure becomes a digital front line",
        "focus": "Why utilities, hospitals, transportation networks, and public systems face growing cyber risk.",
        "questions": [
            "What makes legacy infrastructure hard to secure?",
            "How prepared are operators for prolonged disruption?",
            "Which incidents reveal the biggest systemic vulnerabilities?",
        ],
    },
    {
        "id": "st_017",
        "category": "biotechnology",
        "angle": "Biotech enters a new era of programmable medicine",
        "focus": "How gene editing, RNA platforms, and cell therapies change the logic of treatment development.",
        "questions": [
            "Which diseases are most promising for programmable therapies?",
            "What technical and ethical barriers remain?",
            "How fast can experimental breakthroughs become approved treatments?",
        ],
    },
    {
        "id": "st_018",
        "category": "biotechnology",
        "angle": "Personalized medicine inches toward clinical reality",
        "focus": "The science and economics of tailoring treatments to an individual's biology.",
        "questions": [
            "Which patient groups are benefiting first?",
            "How expensive is personalization at scale?",
            "What kinds of data are needed to make treatment truly individualized?",
        ],
    },
    {
        "id": "st_019",
        "category": "biotechnology",
        "angle": "Lab-grown biology expands beyond pharmaceuticals",
        "focus": "How engineered cells and microbes are being used in materials, chemicals, and food production.",
        "questions": [
            "Which industries are adopting bio-manufacturing fastest?",
            "Can biological production compete with traditional industrial methods?",
            "What infrastructure is required to scale synthetic biology?",
        ],
    },
    {
        "id": "st_020",
        "category": "biotechnology",
        "angle": "The DNA data boom creates new privacy risks",
        "focus": "How rapidly expanding genetic databases raise questions about consent, ownership, and security.",
        "questions": [
            "Who controls genomic information once it is collected?",
            "How are regulators approaching genetic privacy?",
            "What uses of DNA data could surprise the public?",
        ],
    },
    {
        "id": "st_021",
        "category": "health_technology",
        "angle": "Wearables become medical tools instead of lifestyle gadgets",
        "focus": "How consumer devices are moving into disease monitoring and health management.",
        "questions": [
            "Which health metrics are becoming clinically useful?",
            "How reliable are consumer-grade measurements?",
            "Will doctors fully trust data gathered outside the clinic?",
        ],
    },
    {
        "id": "st_022",
        "category": "health_technology",
        "angle": "Telemedicine settles into a second phase",
        "focus": "How remote healthcare evolves after its early rapid expansion.",
        "questions": [
            "Which specialties are best suited for virtual care?",
            "What problems remain unsolved in digital healthcare delivery?",
            "How are insurers and providers adjusting to normalized telemedicine use?",
        ],
    },
    {
        "id": "st_023",
        "category": "health_technology",
        "angle": "AI diagnostics promise faster answers but raise accountability questions",
        "focus": "The tension between diagnostic automation and human medical oversight.",
        "questions": [
            "What kinds of diagnoses are most suited to automation?",
            "Who is responsible when AI-assisted decisions go wrong?",
            "How do clinicians integrate these tools without overreliance?",
        ],
    },
    {
        "id": "st_024",
        "category": "robotics",
        "angle": "Robots leave the factory floor",
        "focus": "How robotics expands into logistics, retail, agriculture, and domestic environments.",
        "questions": [
            "Which non-industrial settings are seeing the fastest adoption?",
            "What technical limitations still prevent widespread deployment?",
            "How do humans adapt when robots enter shared spaces?",
        ],
    },
    {
        "id": "st_025",
        "category": "robotics",
        "angle": "Warehouse automation becomes a logistics arms race",
        "focus": "How fulfillment centers deploy robots, sensors, and software to move goods faster.",
        "questions": [
            "Which warehouse tasks are easiest to automate?",
            "How do labor needs change after automation is introduced?",
            "What does highly automated logistics mean for smaller competitors?",
        ],
    },
    {
        "id": "st_026",
        "category": "robotics",
        "angle": "Humanoid robots chase usefulness beyond spectacle",
        "focus": "Whether general-purpose robotic form factors can become economically practical.",
        "questions": [
            "What tasks actually justify a humanoid design?",
            "Are companies building products or demonstrations?",
            "What breakthroughs are still needed for dependable performance?",
        ],
    },
    {
        "id": "st_027",
        "category": "space",
        "angle": "A new commercial space economy takes shape",
        "focus": "How private launch providers, satellite firms, and service companies reshape access to orbit.",
        "questions": [
            "Which business models in space look sustainable?",
            "How crowded is the launch and satellite market becoming?",
            "What role do governments still play in enabling the sector?",
        ],
    },
    {
        "id": "st_028",
        "category": "space",
        "angle": "Satellites turn Earth into a continuously measured system",
        "focus": "How constellations are transforming communications, mapping, weather, and monitoring.",
        "questions": [
            "What industries depend increasingly on satellite data?",
            "How much of the planet can now be observed in near real time?",
            "What privacy and security concerns follow from constant sensing?",
        ],
    },
    {
        "id": "st_029",
        "category": "space",
        "angle": "Moon missions become a proving ground for the next phase of exploration",
        "focus": "Why lunar programs now serve both scientific goals and industrial ambitions.",
        "questions": [
            "What technologies are being tested through lunar missions?",
            "How are public and private priorities aligning or diverging?",
            "Is the moon becoming a strategic destination rather than a symbolic one?",
        ],
    },
    {
        "id": "st_030",
        "category": "energy_technology",
        "angle": "Battery innovation becomes a central technology story",
        "focus": "How advances in storage affect vehicles, grids, and portable devices.",
        "questions": [
            "Which battery chemistries are gaining momentum?",
            "How close are next-generation batteries to real-world deployment?",
            "What supply constraints could slow adoption?",
        ],
    },
    {
        "id": "st_031",
        "category": "energy_technology",
        "angle": "The grid becomes a software problem",
        "focus": "How digital control, forecasting, and distributed energy systems are changing electricity management.",
        "questions": [
            "What software challenges come with a more dynamic grid?",
            "How are utilities using data to stabilize variable power sources?",
            "Can smarter grids solve reliability without massive new infrastructure?",
        ],
    },
    {
        "id": "st_032",
        "category": "energy_technology",
        "angle": "Fusion research gains momentum but commercial timelines stay uncertain",
        "focus": "The gap between impressive scientific milestones and usable energy systems.",
        "questions": [
            "What breakthroughs matter most in fusion research?",
            "Which engineering challenges remain hardest to solve?",
            "How are startups and governments dividing the field?",
        ],
    },
    {
        "id": "st_033",
        "category": "climate_technology",
        "angle": "Climate tech searches for scalable business models",
        "focus": "How carbon removal, clean materials, and adaptation technologies move from pilot to industry.",
        "questions": [
            "Which climate technologies are closest to economic viability?",
            "Where are subsidies or regulation still necessary?",
            "What separates durable climate businesses from speculative ones?",
        ],
    },
    {
        "id": "st_034",
        "category": "climate_technology",
        "angle": "Carbon accounting becomes a technological challenge",
        "focus": "The systems needed to measure emissions accurately across complex supply chains.",
        "questions": [
            "How do companies verify environmental claims?",
            "What tools are emerging to track emissions in real time?",
            "Where are the biggest gaps in measurement credibility?",
        ],
    },
    {
        "id": "st_035",
        "category": "materials_science",
        "angle": "New materials promise quieter revolutions",
        "focus": "How breakthroughs in materials science enable advances in electronics, energy, and manufacturing.",
        "questions": [
            "Which emerging materials could have the broadest impact?",
            "How long does it take for lab materials to reach industry?",
            "What bottlenecks keep breakthroughs from scaling?",
        ],
    },
    {
        "id": "st_036",
        "category": "materials_science",
        "angle": "The rare earth dilemma shadows modern technology",
        "focus": "How critical materials shape supply chains for electronics, defense, and clean energy.",
        "questions": [
            "Which technologies are most exposed to material constraints?",
            "How are countries and firms diversifying supply?",
            "Can substitutes reduce dependence on scarce inputs?",
        ],
    },
    {
        "id": "st_037",
        "category": "telecommunications",
        "angle": "The next connectivity race is about reliability, not just speed",
        "focus": "How telecom networks compete on consistency, latency, and coverage in addition to raw bandwidth.",
        "questions": [
            "Which applications depend most on low-latency connectivity?",
            "How are carriers justifying expensive infrastructure upgrades?",
            "What users still struggle despite headline advances in network performance?",
        ],
    },
    {
        "id": "st_038",
        "category": "telecommunications",
        "angle": "Rural connectivity becomes a test of technological inclusion",
        "focus": "Why access gaps remain despite improvements in broadband and wireless coverage.",
        "questions": [
            "What technologies best close access gaps in remote areas?",
            "How much do affordability and infrastructure still limit adoption?",
            "What economic activities are held back by weak connectivity?",
        ],
    },
    {
        "id": "st_039",
        "category": "consumer_technology",
        "angle": "Smartphones mature while the search for the next device intensifies",
        "focus": "How the consumer tech industry looks for new growth after years of incremental phone upgrades.",
        "questions": [
            "What device categories are most likely to succeed the smartphone?",
            "How much innovation remains in the handset market?",
            "What user frustrations still go unsolved?",
        ],
    },
    {
        "id": "st_040",
        "category": "consumer_technology",
        "angle": "The smart home becomes an interoperability test",
        "focus": "How connected devices promise convenience but often collide on standards and ecosystems.",
        "questions": [
            "What still makes smart home setups frustrating for users?",
            "How important are common standards to mass adoption?",
            "Which device categories are proving most useful rather than gimmicky?",
        ],
    },
    {
        "id": "st_041",
        "category": "consumer_technology",
        "angle": "Wearable computing searches for a true mainstream purpose",
        "focus": "The challenge of turning always-on personal devices into indispensable tools.",
        "questions": [
            "What use cases justify another screen or sensor on the body?",
            "How do comfort and battery constraints shape product design?",
            "Which demographics are most open to wearable expansion?",
        ],
    },
    {
        "id": "st_042",
        "category": "augmented_virtual_reality",
        "angle": "Mixed reality tries to move beyond early adopter territory",
        "focus": "Whether augmented and virtual reality can become ordinary platforms rather than niche experiments.",
        "questions": [
            "Which use cases create lasting demand for mixed reality?",
            "How much do hardware cost and comfort still limit adoption?",
            "Can software ecosystems mature fast enough to support the platform?",
        ],
    },
    {
        "id": "st_043",
        "category": "augmented_virtual_reality",
        "angle": "Digital worlds become practical tools for work and training",
        "focus": "How immersive environments are being used for design, simulation, and instruction.",
        "questions": [
            "Which industries benefit most from immersive training?",
            "How realistic do simulations need to be to improve performance?",
            "What advantages do virtual environments have over traditional software?",
        ],
    },
    {
        "id": "st_044",
        "category": "education_technology",
        "angle": "AI tutors challenge traditional models of learning support",
        "focus": "How personalized educational tools could change homework, tutoring, and classroom expectations.",
        "questions": [
            "What kinds of students benefit most from AI tutoring?",
            "How do teachers adapt when instant support is always available?",
            "What risks arise when educational tools hallucinate or oversimplify?",
        ],
    },
    {
        "id": "st_045",
        "category": "education_technology",
        "angle": "The future classroom becomes a software stack",
        "focus": "How teaching increasingly depends on platforms, analytics, and digital content systems.",
        "questions": [
            "What parts of classroom management are being automated?",
            "How much visibility into learning data is too much?",
            "Do technology-heavy classrooms improve outcomes consistently?",
        ],
    },
    {
        "id": "st_046",
        "category": "scientific_research",
        "angle": "Automation changes how science gets done",
        "focus": "The rise of robotic labs, automated experiments, and software-driven discovery.",
        "questions": [
            "Which branches of science are most transformed by automation?",
            "How much faster can automated labs iterate than human researchers?",
            "What new kinds of errors emerge when experimentation is heavily automated?",
        ],
    },
    {
        "id": "st_047",
        "category": "scientific_research",
        "angle": "The reproducibility challenge becomes a technology challenge",
        "focus": "How software tools, data standards, and open workflows could improve scientific reliability.",
        "questions": [
            "What technical barriers make reproducibility difficult today?",
            "How are journals and institutions encouraging better practices?",
            "Can automation reduce irreproducible science or simply scale it?",
        ],
    },
    {
        "id": "st_048",
        "category": "scientific_research",
        "angle": "Data-intensive science changes who can compete",
        "focus": "How access to compute, storage, and instrumentation shapes the modern research landscape.",
        "questions": [
            "Which institutions gain the most from data-rich research methods?",
            "Are smaller labs being left behind by infrastructure costs?",
            "How do collaborations compensate for unequal resources?",
        ],
    },
    {
        "id": "st_049",
        "category": "environmental_science",
        "angle": "Scientists build sharper models of extreme weather risk",
        "focus": "How improved forecasting and climate modeling affect public safety and planning.",
        "questions": [
            "What new data sources are improving predictions?",
            "How accurate can localized risk forecasts become?",
            "How are governments and businesses using these tools?",
        ],
    },
    {
        "id": "st_050",
        "category": "environmental_science",
        "angle": "Monitoring the planet becomes a real-time scientific project",
        "focus": "How sensors, satellites, and machine learning are turning ecosystems into continuously observed systems.",
        "questions": [
            "What environmental variables can now be measured at scale?",
            "How do scientists process the flood of incoming data?",
            "Where does more data meaningfully improve intervention?",
        ],
    },
    {
        "id": "st_051",
        "category": "transportation_technology",
        "angle": "Autonomous driving advances in uneven, highly local ways",
        "focus": "Why self-driving systems may succeed in specific conditions long before broad deployment.",
        "questions": [
            "Which environments are most favorable to autonomy?",
            "What edge cases still defeat current systems?",
            "How are cities reacting to autonomous vehicles on public roads?",
        ],
    },
    {
        "id": "st_052",
        "category": "transportation_technology",
        "angle": "Software-defined vehicles change the auto industry",
        "focus": "How cars increasingly resemble connected computing platforms on wheels.",
        "questions": [
            "What features are now being shaped primarily by software?",
            "How do over-the-air updates change ownership expectations?",
            "Which automakers are adapting best to the shift?",
        ],
    },
    {
        "id": "st_053",
        "category": "drone_technology",
        "angle": "Drones become everyday infrastructure",
        "focus": "How aerial robotics expand from hobby and military uses into inspection, mapping, and logistics.",
        "questions": [
            "Which commercial drone applications have proven durable?",
            "What regulations most constrain broader drone use?",
            "How are companies integrating drones into regular operations?",
        ],
    },
    {
        "id": "st_054",
        "category": "drone_technology",
        "angle": "Autonomous aerial systems test the limits of regulation",
        "focus": "How increasingly capable drones force new rules for safety, privacy, and airspace use.",
        "questions": [
            "What safety systems are needed for dense drone traffic?",
            "How do regulators balance innovation with public concern?",
            "What industries stand to gain most if rules become clearer?",
        ],
    },
    {
        "id": "st_055",
        "category": "quantum_technology",
        "angle": "Quantum computing remains promising but difficult to commercialize",
        "focus": "The gap between experimental quantum advances and broadly useful applications.",
        "questions": [
            "What practical problems might quantum systems solve first?",
            "How much error correction is still needed for real utility?",
            "Who is investing most heavily despite long timelines?",
        ],
    },
    {
        "id": "st_056",
        "category": "quantum_technology",
        "angle": "Quantum sensing may arrive before quantum computing",
        "focus": "Why sensing and measurement applications could become the first commercially important quantum tools.",
        "questions": [
            "Which industries could benefit from quantum-enhanced measurement?",
            "How close are these devices to deployable products?",
            "Why might sensing mature faster than computation?",
        ],
    },
    {
        "id": "st_057",
        "category": "privacy",
        "angle": "Convenience technologies quietly expand surveillance",
        "focus": "How apps, platforms, and connected devices gather more information than most users realize.",
        "questions": [
            "What kinds of data collection have become normalized?",
            "How aware are users of passive data harvesting?",
            "Where do privacy safeguards fail in practice?",
        ],
    },
    {
        "id": "st_058",
        "category": "privacy",
        "angle": "Biometric systems spread faster than public trust",
        "focus": "The rise of face, voice, and behavior recognition in consumer and institutional settings.",
        "questions": [
            "Which sectors are adopting biometric systems most aggressively?",
            "What risks arise from false matches or misuse?",
            "How are users reacting to invisible identification systems?",
        ],
    },
    {
        "id": "st_059",
        "category": "platforms",
        "angle": "Digital platforms become infrastructure rather than destinations",
        "focus": "How large technology ecosystems are embedding themselves in commerce, identity, and communication.",
        "questions": [
            "What happens when a platform becomes too central to daily life?",
            "How do businesses cope with dependence on dominant ecosystems?",
            "What services are hardest to leave once adopted?",
        ],
    },
    {
        "id": "st_060",
        "category": "platforms",
        "angle": "Search changes when answers replace links",
        "focus": "How AI-generated summaries and answer engines alter the structure of discovery online.",
        "questions": [
            "How do publishers respond when fewer users click through?",
            "What does this shift mean for trust and verification?",
            "Will users prefer direct answers even when they are less transparent?",
        ],
    },
    {
        "id": "st_061",
        "category": "open_source",
        "angle": "Open-source software becomes a strategic geopolitical asset",
        "focus": "How openly shared code influences innovation, security, and national competitiveness.",
        "questions": [
            "Which sectors rely most deeply on open infrastructure?",
            "How are governments approaching open-source dependencies?",
            "What happens when key maintainers cannot sustain critical projects?",
        ],
    },
    {
        "id": "st_062",
        "category": "open_source",
        "angle": "The economics of open models challenge closed AI ecosystems",
        "focus": "Whether openly released AI systems can compete with heavily capitalized proprietary offerings.",
        "questions": [
            "What makes open models attractive to developers and companies?",
            "How sustainable are the communities behind them?",
            "Can openness coexist with meaningful safety controls?",
        ],
    },
    {
        "id": "st_063",
        "category": "manufacturing_technology",
        "angle": "3D printing grows up into industrial production",
        "focus": "How additive manufacturing moves from prototyping to specialized end-use parts.",
        "questions": [
            "Which industries benefit most from additive manufacturing?",
            "What materials and tolerances remain limiting factors?",
            "Where does 3D printing outperform traditional manufacturing economically?",
        ],
    },
    {
        "id": "st_064",
        "category": "manufacturing_technology",
        "angle": "Digital twins promise better industrial decision-making",
        "focus": "How virtual models of physical systems are used to predict performance and failure.",
        "questions": [
            "Which sectors are making real use of digital twins?",
            "How accurate do models need to be to justify their cost?",
            "What data is hardest to capture from the physical world?",
        ],
    },
    {
        "id": "st_065",
        "category": "food_science",
        "angle": "Alternative proteins search for their breakthrough moment",
        "focus": "How food science tries to create products that are cheaper, tastier, and more scalable than earlier attempts.",
        "questions": [
            "What scientific hurdles remain for alternative proteins?",
            "How important is taste versus price in consumer adoption?",
            "Can manufacturing scale bring costs low enough to compete broadly?",
        ],
    },
    {
        "id": "st_066",
        "category": "food_science",
        "angle": "Agricultural science turns toward resilience",
        "focus": "How crop genetics, sensing, and automation aim to keep yields stable under harsher conditions.",
        "questions": [
            "Which technologies are helping farms adapt fastest?",
            "How do data and genetics work together in modern agriculture?",
            "What barriers prevent scientific advances from reaching smaller producers?",
        ],
    },
    {
        "id": "st_067",
        "category": "ocean_science",
        "angle": "The ocean becomes a new data frontier",
        "focus": "How sensors, robotics, and imaging are improving understanding of marine systems.",
        "questions": [
            "What has been hardest to measure in the oceans until now?",
            "How are autonomous systems expanding marine research?",
            "What discoveries become possible with denser sensing networks?",
        ],
    },
    {
        "id": "st_068",
        "category": "astronomy",
        "angle": "Astronomy enters an age of overwhelming data",
        "focus": "How new telescopes generate more information than traditional methods can easily process.",
        "questions": [
            "How are astronomers using AI to sort celestial data?",
            "What discoveries become more likely when sky surveys scale massively?",
            "How do researchers avoid missing rare signals in huge datasets?",
        ],
    },
    {
        "id": "st_069",
        "category": "astronomy",
        "angle": "Private satellites complicate the night sky for science",
        "focus": "How growing orbital infrastructure affects astronomical observation.",
        "questions": [
            "How severe is satellite interference for different kinds of astronomy?",
            "What mitigation efforts are being proposed or tested?",
            "Can commercial expansion and scientific observation coexist?",
        ],
    },
    {
        "id": "st_070",
        "category": "neuroscience",
        "angle": "Brain-computer interfaces move from experiment to prototype product",
        "focus": "How neural interfaces could change communication, accessibility, and computing control.",
        "questions": [
            "Which applications are realistically closest to deployment?",
            "What safety and ethics concerns remain unsolved?",
            "How much precision is required for truly useful interfaces?",
        ],
    },
    {
        "id": "st_071",
        "category": "neuroscience",
        "angle": "Mapping the brain becomes a grand engineering project",
        "focus": "How neuroscience increasingly depends on large-scale imaging, computation, and collaboration.",
        "questions": [
            "What technologies are improving brain mapping resolution?",
            "How much can structure alone reveal about cognition?",
            "What are the biggest computational bottlenecks in modern neuroscience?",
        ],
    },
    {
        "id": "st_072",
        "category": "policy_and_regulation",
        "angle": "Governments struggle to regulate fast-moving science",
        "focus": "How policy systems attempt to keep pace with advances in AI, biotech, and digital platforms.",
        "questions": [
            "Which technologies most clearly outpace existing regulation?",
            "How do regulators avoid freezing innovation while protecting the public?",
            "What happens when different countries set incompatible rules?",
        ],
    },
    {
        "id": "st_073",
        "category": "policy_and_regulation",
        "angle": "Export controls turn advanced technology into a strategic resource",
        "focus": "How governments use trade rules to shape access to chips, software, and scientific equipment.",
        "questions": [
            "Which technologies are most affected by export controls?",
            "How do firms redesign supply chains around new restrictions?",
            "What long-term effects do controls have on global innovation?",
        ],
    },
    {
        "id": "st_074",
        "category": "science_funding",
        "angle": "Big science depends on fragile funding coalitions",
        "focus": "How major research efforts rely on a mix of public money, private capital, and institutional support.",
        "questions": [
            "Which fields are most vulnerable to funding instability?",
            "How does uncertain financing change scientific ambition?",
            "What research priorities get favored when budgets tighten?",
        ],
    },
    {
        "id": "st_075",
        "category": "science_funding",
        "angle": "Private capital takes a larger role in frontier science",
        "focus": "How venture funding and billionaire-backed projects influence research direction.",
        "questions": [
            "Which scientific fields attract the most private money?",
            "How does private funding change timelines and incentives?",
            "Where does commercial pressure distort scientific priorities?",
        ],
    },
    {
        "id": "st_076",
        "category": "social_technology",
        "angle": "Algorithmic systems quietly shape daily choices",
        "focus": "How recommendation engines and ranking systems influence information, shopping, and behavior.",
        "questions": [
            "Where are algorithms most invisible yet influential?",
            "How much user behavior is genuinely self-directed in platform environments?",
            "Can transparency meaningfully improve trust in ranking systems?",
        ],
    },
    {
        "id": "st_077",
        "category": "social_technology",
        "angle": "Digital loneliness becomes a paradox of hyper-connection",
        "focus": "How always-on technology changes social habits, relationships, and emotional well-being.",
        "questions": [
            "Which forms of technology use correlate with greater isolation?",
            "How are platforms attempting to respond to well-being concerns?",
            "What designs could make digital life feel less fragmenting?",
        ],
    },
    {
        "id": "st_078",
        "category": "future_of_work",
        "angle": "Scientific and technical careers fragment into hybrid roles",
        "focus": "How engineers, researchers, analysts, and operators increasingly share overlapping skill sets.",
        "questions": [
            "Which hybrid roles are emerging fastest?",
            "How are universities and employers adapting training pipelines?",
            "What traditional career boundaries are breaking down?",
        ],
    },
    {
        "id": "st_079",
        "category": "future_of_work",
        "angle": "The scientist as software user and software builder",
        "focus": "How modern research increasingly requires coding, automation, and data engineering.",
        "questions": [
            "Which scientific fields now demand the strongest computing skills?",
            "How are labs training researchers to build their own tools?",
            "Does software fluency create a new divide within science?",
        ],
    },
    {
        "id": "st_080",
        "category": "hardware",
        "angle": "The hardware startup revival depends on smarter supply chains",
        "focus": "How new physical technology companies navigate manufacturing and component risk.",
        "questions": [
            "What makes hardware startups more viable now than in past cycles?",
            "How are founders reducing manufacturing risk?",
            "Which product categories still face the toughest scale-up challenges?",
        ],
    },
    {
        "id": "st_081",
        "category": "hardware",
        "angle": "Repairability becomes a technology design debate",
        "focus": "Whether devices should be built for thinness and control or longevity and serviceability.",
        "questions": [
            "How do consumers actually value repairable design?",
            "What companies gain or lose from easier repair?",
            "How does repairability affect sustainability and ownership?",
        ],
    },
    {
        "id": "st_082",
        "category": "internet",
        "angle": "The web fragments into ecosystems and walled experiences",
        "focus": "How open browsing competes with app platforms, AI layers, and closed communities.",
        "questions": [
            "Is the open web losing relevance or simply changing form?",
            "How do creators and publishers adapt to platform dependency?",
            "What parts of the internet remain stubbornly open?",
        ],
    },
    {
        "id": "st_083",
        "category": "internet",
        "angle": "Identity online becomes harder to verify",
        "focus": "How bots, synthetic personas, and fragmented platforms make trust more difficult.",
        "questions": [
            "What systems might restore confidence in digital identity?",
            "How much online interaction is already shaped by non-human actors?",
            "What are the tradeoffs of stronger identity verification?",
        ],
    },
    {
        "id": "st_084",
        "category": "ethics",
        "angle": "Scientific progress outruns the public conversation",
        "focus": "How technical capability can advance faster than society's ability to debate its implications.",
        "questions": [
            "Which technologies most clearly outpace public understanding?",
            "How are scientists communicating risks and tradeoffs?",
            "What happens when adoption begins before norms are settled?",
        ],
    },
    {
        "id": "st_085",
        "category": "ethics",
        "angle": "Bias in technical systems becomes an engineering and governance problem",
        "focus": "How unfair outcomes emerge from data, models, and design assumptions.",
        "questions": [
            "Which systems are most vulnerable to biased outcomes?",
            "How do organizations measure and reduce harm?",
            "Can fairness be standardized across very different use cases?",
        ],
    },
    {
        "id": "st_086",
        "category": "defense_technology",
        "angle": "Dual-use technology blurs civilian and military innovation",
        "focus": "How advances in AI, drones, space systems, and cyber tools move across sectors.",
        "questions": [
            "Which technologies are most clearly dual-use today?",
            "How do companies navigate commercial and defense demand simultaneously?",
            "What ethical tensions arise when civilian tech becomes militarily useful?",
        ],
    },
    {
        "id": "st_087",
        "category": "defense_technology",
        "angle": "Autonomy changes the logic of modern defense systems",
        "focus": "How machine decision-making affects surveillance, targeting, and military operations.",
        "questions": [
            "What autonomy levels are already considered acceptable?",
            "How do militaries balance speed with human oversight?",
            "What technologies make autonomous systems more reliable or dangerous?",
        ],
    },
    {
        "id": "st_088",
        "category": "scientific_culture",
        "angle": "Prestige science meets public pressure for usefulness",
        "focus": "How institutions justify basic research in an era focused on practical outcomes.",
        "questions": [
            "How do research leaders defend long-horizon science?",
            "Which discoveries emerged from curiosity-driven work rather than applied goals?",
            "What gets lost when usefulness becomes the main funding test?",
        ],
    },
    {
        "id": "st_089",
        "category": "scientific_culture",
        "angle": "Citizen science gains new power through connected tools",
        "focus": "How amateurs contribute meaningfully to data collection and discovery using modern technology.",
        "questions": [
            "Which scientific fields benefit most from public participation?",
            "How do researchers validate citizen-generated data?",
            "Can distributed public involvement reshape how science is organized?",
        ],
    },
    {
        "id": "st_090",
        "category": "frontier_technology",
        "angle": "The next breakthrough may come from combining mature technologies",
        "focus": "How important advances emerge not from one invention alone, but from convergence across fields.",
        "questions": [
            "Which technology combinations look most promising right now?",
            "How do interdisciplinary teams outperform siloed research groups?",
            "Why are convergence stories often harder to notice until after the fact?",
        ],
    },
]
