from synthnews.prompts.angles import Angle


ANGLES: list[Angle] = [
    {
        "id": "spo_001",
        "category": "game_result",
        "angle": "Late comeback turns ordinary game into season-defining statement",
        "focus": "A game story centered on momentum, resilience, and what a dramatic finish means beyond one result.",
        "questions": [
            "What changed the game in the closing stretch?",
            "Which players or coaching decisions defined the comeback?",
            "Could this result change the team's season trajectory?",
        ],
    },
    {
        "id": "spo_002",
        "category": "game_result",
        "angle": "Heavy favorite stunned by underdog in upset that reshapes the standings",
        "focus": "A result story about confidence, vulnerability, and the meaning of a major upset.",
        "questions": [
            "What made the underdog's win possible?",
            "Did the favorite underestimate the opponent or expose a deeper flaw?",
            "How far could the upset ripple through the league or tournament?",
        ],
    },
    {
        "id": "spo_003",
        "category": "game_result",
        "angle": "Defensive battle reveals how winning ugly can still send a message",
        "focus": "A game analysis story about discipline, structure, and low-scoring control.",
        "questions": [
            "What defensive tactics shaped the contest?",
            "Which players made the hidden difference without flashy numbers?",
            "Does this type of win show championship potential?",
        ],
    },
    {
        "id": "spo_004",
        "category": "game_result",
        "angle": "Offensive explosion raises questions about whether the team has finally clicked",
        "focus": "A performance story about rhythm, chemistry, and whether one breakout game signals something real.",
        "questions": [
            "What was different about the team's attack this time?",
            "Which matchups or adjustments opened the floodgates?",
            "Is this sustainable or just a one-night surge?",
        ],
    },
    {
        "id": "spo_005",
        "category": "game_result",
        "angle": "Controversial officiating call becomes bigger than the final score",
        "focus": "A postgame drama story where referees, replay, and interpretation dominate the conversation.",
        "questions": [
            "What exactly happened and how was it ruled?",
            "How are coaches, players, and analysts interpreting the decision?",
            "Will the controversy lead to rule or replay scrutiny?",
        ],
    },
    {
        "id": "spo_006",
        "category": "star_player",
        "angle": "Superstar delivers signature performance when the team needed it most",
        "focus": "A star-driven story about pressure, expectations, and legacy moments.",
        "questions": [
            "What made the performance feel bigger than normal excellence?",
            "How much did the player carry the team versus fit into a larger plan?",
            "Does the outing strengthen MVP or legacy narratives?",
        ],
    },
    {
        "id": "spo_007",
        "category": "star_player",
        "angle": "Star player's prolonged slump becomes the central question around the team",
        "focus": "A concern story about form, confidence, health, and rising pressure.",
        "questions": [
            "Is the slump technical, physical, or mental?",
            "How is the team adapting around diminished production?",
            "At what point does a slump become a real crisis?",
        ],
    },
    {
        "id": "spo_008",
        "category": "star_player",
        "angle": "Young star's breakout changes expectations overnight",
        "focus": "A rise story about talent crystallizing into real league-wide attention.",
        "questions": [
            "What signs suggested the breakout was coming?",
            "How are opponents now adjusting to the player?",
            "Can the athlete handle the new level of scrutiny and responsibility?",
        ],
    },
    {
        "id": "spo_009",
        "category": "star_player",
        "angle": "Veteran proves experience still matters in a league chasing youth",
        "focus": "A longevity story about intelligence, adaptation, and late-career value.",
        "questions": [
            "What allows the veteran to remain effective?",
            "How is the player's role changing with age?",
            "Does the performance alter retirement or contract speculation?",
        ],
    },
    {
        "id": "spo_010",
        "category": "injuries",
        "angle": "Major injury forces contender to rethink everything",
        "focus": "A disruption story about roster construction, identity, and survival after losing a key player.",
        "questions": [
            "How severe is the injury and what timeline matters most?",
            "Who must absorb the missing production?",
            "Can the team remain competitive without its centerpiece?",
        ],
    },
    {
        "id": "spo_011",
        "category": "injuries",
        "angle": "Athlete returns from injury to emotional reception and intense scrutiny",
        "focus": "A comeback story blending hope, risk, and performance pressure.",
        "questions": [
            "How ready did the athlete actually look?",
            "What limitations, if any, were visible?",
            "Does the return restore the team's ceiling immediately?",
        ],
    },
    {
        "id": "spo_012",
        "category": "injuries",
        "angle": "A rash of injuries raises questions about workload, schedule, and preparation",
        "focus": "A systemic story about whether the sport is pushing athletes too hard.",
        "questions": [
            "Why are injuries clustering now?",
            "How do coaches and medical staff explain the pattern?",
            "Could scheduling or training changes reduce the problem?",
        ],
    },
    {
        "id": "spo_013",
        "category": "coaching",
        "angle": "Coach on the hot seat tries to stop season from slipping away",
        "focus": "A leadership-pressure story about trust, tactics, and organizational patience.",
        "questions": [
            "What exactly has gone wrong under this coach?",
            "Are players still responding to the message?",
            "How close is management to making a change?",
        ],
    },
    {
        "id": "spo_014",
        "category": "coaching",
        "angle": "New coach changes tone and tactics faster than expected",
        "focus": "A transition story about immediate stylistic shifts and renewed buy-in.",
        "questions": [
            "What changes are most visible under the new staff?",
            "How quickly are players adapting?",
            "Is the early bounce emotional, tactical, or both?",
        ],
    },
    {
        "id": "spo_015",
        "category": "coaching",
        "angle": "Bold coaching gamble defines the game and sparks debate afterward",
        "focus": "A tactics story about risk-taking, second-guessing, and philosophy under pressure.",
        "questions": [
            "What decision was made and why was it so consequential?",
            "Was the gamble sound process even if the result failed?",
            "How do players and analysts view the choice?",
        ],
    },
    {
        "id": "spo_016",
        "category": "locker_room",
        "angle": "Tension inside the locker room becomes impossible to ignore",
        "focus": "A chemistry story about leadership, ego, accountability, and internal friction.",
        "questions": [
            "What signs suggest deeper conflict?",
            "Are results causing tension or revealing pre-existing fractures?",
            "Who inside the team can still steady the room?",
        ],
    },
    {
        "id": "spo_017",
        "category": "locker_room",
        "angle": "Players-only meeting signals urgency after poor stretch",
        "focus": "A team culture story about whether self-correction is possible before outside intervention.",
        "questions": [
            "What triggered the meeting?",
            "How do players describe the mood inside the team?",
            "Do these meetings ever meaningfully change outcomes?",
        ],
    },
    {
        "id": "spo_018",
        "category": "trade_and_transfer",
        "angle": "Blockbuster trade or transfer shakes up league power balance",
        "focus": "A roster drama story about immediate impact and long-term consequences.",
        "questions": [
            "Why did both sides make the move now?",
            "Who gained more on paper and who took the bigger risk?",
            "How quickly could the deal change the championship picture?",
        ],
    },
    {
        "id": "spo_019",
        "category": "trade_and_transfer",
        "angle": "Trade deadline caution shows teams are afraid of the wrong gamble",
        "focus": "A market story about hesitation, valuation, and strategic patience.",
        "questions": [
            "Why were fewer deals made than expected?",
            "Which teams chose not to act, and what does that signal?",
            "Could caution now lead to regret later?",
        ],
    },
    {
        "id": "spo_020",
        "category": "trade_and_transfer",
        "angle": "Transfer rumor cycle overwhelms the actual sport",
        "focus": "A media-and-business story where speculation becomes part of the entertainment product.",
        "questions": [
            "Why is this player or club at the center of so much speculation?",
            "Who benefits from the rumor machine?",
            "How does constant transfer talk affect on-field focus?",
        ],
    },
    {
        "id": "spo_021",
        "category": "front_office",
        "angle": "General manager's long-term plan faces its biggest test yet",
        "focus": "A team-building story about roster philosophy, timelines, and accountability.",
        "questions": [
            "What vision did management sell originally?",
            "Are current results validating or undermining that plan?",
            "How much patience remains from ownership and fans?",
        ],
    },
    {
        "id": "spo_022",
        "category": "front_office",
        "angle": "Ownership change could alter club ambition, spending, and identity",
        "focus": "A power and money story about what new control means for the future.",
        "questions": [
            "What kind of owner is stepping in?",
            "How might philosophy and investment change?",
            "What do fans fear or hope will happen next?",
        ],
    },
    {
        "id": "spo_023",
        "category": "standings_race",
        "angle": "Crowded playoff race turns every result into a pressure game",
        "focus": "A standings story about thin margins, scoreboard watching, and rising stakes.",
        "questions": [
            "Which teams are separated by the smallest margins?",
            "What remaining schedule factors matter most?",
            "Who looks built for the pressure and who looks vulnerable?",
        ],
    },
    {
        "id": "spo_024",
        "category": "standings_race",
        "angle": "A slow start leaves contender chasing from behind",
        "focus": "A season-shape story about the hidden cost of early inconsistency.",
        "questions": [
            "What caused the poor start?",
            "How much room remains to recover?",
            "Will the chase itself wear the team down later?",
        ],
    },
    {
        "id": "spo_025",
        "category": "playoffs",
        "angle": "Playoff series swings on one momentum-changing game",
        "focus": "A postseason story about turning points, pressure, and psychological edge.",
        "questions": [
            "What made this game feel like the pivot of the series?",
            "Which adjustments now matter most going forward?",
            "How do teams recover emotionally after a swing result?",
        ],
    },
    {
        "id": "spo_026",
        "category": "playoffs",
        "angle": "Underdog playoff run captures neutral fans and unsettles favorites",
        "focus": "A postseason narrative about belief, tactics, and the joy of disruption.",
        "questions": [
            "Why is this underdog succeeding now?",
            "What makes the run emotionally compelling to outsiders?",
            "Can the run continue once opponents fully adjust?",
        ],
    },
    {
        "id": "spo_027",
        "category": "championship",
        "angle": "Championship victory crowns a project years in the making",
        "focus": "A culmination story about vision, patience, and finally delivering under pressure.",
        "questions": [
            "What long-term decisions led to this title?",
            "Which people most shaped the journey?",
            "Could this be the start of a dynasty or the peak of a cycle?",
        ],
    },
    {
        "id": "spo_028",
        "category": "championship",
        "angle": "Painful championship loss raises questions about whether the window is closing",
        "focus": "A near-miss story about aging rosters, missed chances, and future uncertainty.",
        "questions": [
            "What will define this loss in hindsight?",
            "How many real chances does this group have left?",
            "What offseason decisions now become urgent?",
        ],
    },
    {
        "id": "spo_029",
        "category": "dynasty_and_legacy",
        "angle": "Dynasty talk returns as dominant team keeps finding new ways to win",
        "focus": "A legacy story about sustained excellence and the difficulty of staying hungry.",
        "questions": [
            "What separates this team from other contenders?",
            "How has it adapted to avoid decline?",
            "At what point does dominance become historical?",
        ],
    },
    {
        "id": "spo_030",
        "category": "dynasty_and_legacy",
        "angle": "Once-dominant powerhouse looks mortal for the first time in years",
        "focus": "A transition story about decline, complacency, and the end of inevitability.",
        "questions": [
            "What signs suggest the era may be fading?",
            "Is this a blip or a true turning point?",
            "How hard is it for champions to reinvent themselves?",
        ],
    },
    {
        "id": "spo_031",
        "category": "records_and_milestones",
        "angle": "Historic milestone gives fans a reason to pause and appreciate greatness",
        "focus": "A celebratory story about records, longevity, and context across eras.",
        "questions": [
            "Why does this milestone matter beyond the number itself?",
            "How does the athlete compare across generations?",
            "What does the achievement reveal about modern training or durability?",
        ],
    },
    {
        "id": "spo_032",
        "category": "records_and_milestones",
        "angle": "Record chase becomes a nightly drama inside the season",
        "focus": "A serialized story about anticipation, pressure, and performance under a spotlight.",
        "questions": [
            "How is the athlete handling the buildup?",
            "What makes this record especially meaningful?",
            "Does the chase help or distract from team goals?",
        ],
    },
    {
        "id": "spo_033",
        "category": "rookies_and_prospects",
        "angle": "Top rookie arrives with hype, pressure, and impossible comparisons",
        "focus": "A debut story about expectation, development, and the burden of projections.",
        "questions": [
            "What makes this prospect feel different from others?",
            "How patient will the team and fan base be?",
            "What early signs matter more than raw statistics?",
        ],
    },
    {
        "id": "spo_034",
        "category": "rookies_and_prospects",
        "angle": "Overlooked prospect forces team to rethink its depth chart",
        "focus": "A discovery story about internal competition and surprise emergence.",
        "questions": [
            "What has this player shown that coaches can no longer ignore?",
            "How does the rise alter other players' roles?",
            "Could this become one of the season's defining surprises?",
        ],
    },
    {
        "id": "spo_035",
        "category": "college_sports",
        "angle": "Power program stumbles and suddenly looks vulnerable in its own backyard",
        "focus": "A college sports story about recruiting, pressure, and the weight of tradition.",
        "questions": [
            "What has caused the decline or inconsistency?",
            "How are fans and alumni reacting?",
            "What would it take to restore the program's aura?",
        ],
    },
    {
        "id": "spo_036",
        "category": "college_sports",
        "angle": "Cinderella tournament run turns unknown athletes into national stories",
        "focus": "A tournament story about belief, exposure, and the speed of sports fame.",
        "questions": [
            "What makes this run feel magical beyond the wins themselves?",
            "How are the athletes handling sudden attention?",
            "Can the team keep playing freely as the stakes rise?",
        ],
    },
    {
        "id": "spo_037",
        "category": "college_sports",
        "angle": "Coaching carousel turns offseason into a battle for relevance",
        "focus": "A program-building story about leadership, recruiting, and institutional ambition.",
        "questions": [
            "Why did this school make a move now?",
            "What does the hire signal about future expectations?",
            "How quickly can a new coach change the program's trajectory?",
        ],
    },
    {
        "id": "spo_038",
        "category": "women_sports",
        "angle": "Women's game draws record attention and demands new levels of investment",
        "focus": "A growth story about audience demand, infrastructure, and overdue recognition.",
        "questions": [
            "What is driving the surge in attention?",
            "Are leagues and networks investing enough to match momentum?",
            "How sustainable is the current growth wave?",
        ],
    },
    {
        "id": "spo_039",
        "category": "women_sports",
        "angle": "Star rivalry helps transform the visibility of an entire league",
        "focus": "A league-building story where individual charisma lifts the broader product.",
        "questions": [
            "Why has this rivalry connected so strongly with audiences?",
            "How are the players managing competition and media attention?",
            "Can the league convert star power into long-term growth?",
        ],
    },
    {
        "id": "spo_040",
        "category": "women_sports",
        "angle": "Pay, travel, and facilities debate highlights gap between popularity and support",
        "focus": "An equity story about professional respect and structural investment.",
        "questions": [
            "What material inequalities are athletes pointing to?",
            "How are leagues and governing bodies responding?",
            "What changes would most improve working conditions?",
        ],
    },
    {
        "id": "spo_041",
        "category": "international_sports",
        "angle": "National team carries the weight of expectation into a major tournament",
        "focus": "A global competition story about pressure, identity, and representing more than a club.",
        "questions": [
            "What does the team symbolize to supporters back home?",
            "Where are its strengths and vulnerabilities most visible?",
            "How much pressure comes from history rather than current form?",
        ],
    },
    {
        "id": "spo_042",
        "category": "international_sports",
        "angle": "Host nation hopes sports spectacle can become a national statement",
        "focus": "A mega-event story about image, ambition, and the politics of hosting.",
        "questions": [
            "What does hosting mean to the country or city?",
            "How are organizers presenting the event to the world?",
            "What tensions sit beneath the celebration?",
        ],
    },
    {
        "id": "spo_043",
        "category": "international_sports",
        "angle": "Tournament upset proves reputation does not guarantee control",
        "focus": "A major-event story about volatility, tactical surprise, and national emotion.",
        "questions": [
            "What made the favorite look vulnerable?",
            "How did the underdog seize belief and momentum?",
            "Could the result reshape the whole bracket?",
        ],
    },
    {
        "id": "spo_044",
        "category": "combat_sports",
        "angle": "Champion's aura meets toughest stylistic challenge yet",
        "focus": "A fight story driven by matchup theory, confidence, and legacy stakes.",
        "questions": [
            "What makes this opponent uniquely dangerous?",
            "How are both camps framing the tactical battle?",
            "What would victory mean for the winner's standing in the sport?",
        ],
    },
    {
        "id": "spo_045",
        "category": "combat_sports",
        "angle": "Controversial decision leaves the sport arguing long after the final bell",
        "focus": "A judging story about fairness, scoring, and trust in outcomes.",
        "questions": [
            "Which rounds or moments are most contested?",
            "How are fighters, promoters, and fans reacting?",
            "Does the result make a rematch unavoidable?",
        ],
    },
    {
        "id": "spo_046",
        "category": "motorsports",
        "angle": "Driver and team strategy turn chaotic race into a masterclass",
        "focus": "A race story about decision-making, adaptability, and winning under changing conditions.",
        "questions": [
            "Which strategic calls proved decisive?",
            "How did weather, safety cars, or tires shape the result?",
            "Does the win change the title race significantly?",
        ],
    },
    {
        "id": "spo_047",
        "category": "motorsports",
        "angle": "Mechanical failure devastates title hopes in cruel reminder of sport's fragility",
        "focus": "A heartbreak story about technology, preparation, and lost opportunity.",
        "questions": [
            "What went wrong technically?",
            "Could the failure have been prevented?",
            "How hard is it to recover emotionally and mathematically from this setback?",
        ],
    },
    {
        "id": "spo_048",
        "category": "olympics_and_amateur",
        "angle": "Olympic hopeful peaks at the perfect time and becomes a medal threat",
        "focus": "A preparation story about timing, discipline, and breakthrough on the world stage.",
        "questions": [
            "What has changed in the athlete's form or preparation?",
            "How strong is the field they must face?",
            "What would success mean for the athlete's career and country?",
        ],
    },
    {
        "id": "spo_049",
        "category": "olympics_and_amateur",
        "angle": "Selection controversy leaves deserving athlete on the outside",
        "focus": "A heartbreak and governance story about criteria, fairness, and public reaction.",
        "questions": [
            "What standards or process drove the selection choice?",
            "How are coaches and officials defending it?",
            "Could the controversy force future changes?",
        ],
    },
    {
        "id": "spo_050",
        "category": "governance",
        "angle": "League rule change sparks argument over whether the sport is losing its soul",
        "focus": "A philosophy story about modernization, safety, entertainment, and tradition.",
        "questions": [
            "What exactly is changing and why now?",
            "Who benefits most from the rule adjustment?",
            "Do fans and players see the change as necessary or corrosive?",
        ],
    },
    {
        "id": "spo_051",
        "category": "governance",
        "angle": "Commissioner or league office faces criticism over consistency and credibility",
        "focus": "An institutional story about discipline, communication, and trust in leadership.",
        "questions": [
            "What decision triggered the backlash?",
            "How do teams and players view the league's authority right now?",
            "Can credibility be restored once fairness is questioned?",
        ],
    },
    {
        "id": "spo_052",
        "category": "governance",
        "angle": "Scheduling congestion reveals how commercial growth strains competitive integrity",
        "focus": "A system story about TV money, travel, recovery time, and athlete welfare.",
        "questions": [
            "Who benefits from the packed calendar?",
            "What are players and coaches saying about the toll?",
            "How does fatigue affect the quality of the product?",
        ],
    },
    {
        "id": "spo_053",
        "category": "money_and_business",
        "angle": "Record contract shows how star power and scarcity drive modern sports economics",
        "focus": "A business story about valuation, leverage, and what teams are willing to pay for certainty.",
        "questions": [
            "Why is this athlete worth this level of commitment?",
            "How much risk is baked into the contract?",
            "What does the deal mean for future negotiations across the league?",
        ],
    },
    {
        "id": "spo_054",
        "category": "money_and_business",
        "angle": "Salary cap or payroll squeeze forces painful choices for contenders",
        "focus": "A roster economics story about keeping a core together under financial constraints.",
        "questions": [
            "Which player decisions are becoming hardest to manage?",
            "How are teams trying to stay competitive within the rules?",
            "What sacrifices usually come first when cap pressure builds?",
        ],
    },
    {
        "id": "spo_055",
        "category": "money_and_business",
        "angle": "Broadcast rights fight shows live sports remain one of media's last sure bets",
        "focus": "A business-media story about why sports are still premium content.",
        "questions": [
            "Why are rights fees still so valuable?",
            "How are networks and streaming platforms changing the viewing landscape?",
            "What does the rights battle mean for fans' access and cost?",
        ],
    },
    {
        "id": "spo_056",
        "category": "fans_and_culture",
        "angle": "Crowd atmosphere becomes a real competitive advantage",
        "focus": "A fan culture story about noise, identity, and emotional momentum.",
        "questions": [
            "What makes this venue or fan base especially influential?",
            "How do players describe the difference the crowd makes?",
            "Can atmosphere truly shift outcomes at the margins?",
        ],
    },
    {
        "id": "spo_057",
        "category": "fans_and_culture",
        "angle": "Fan protest against ownership shows loyalty can turn into organized pressure",
        "focus": "A civic sports story about supporters demanding more than symbolic gestures.",
        "questions": [
            "What specifically are fans protesting?",
            "How is ownership responding publicly and privately?",
            "When do supporter movements actually force change?",
        ],
    },
    {
        "id": "spo_058",
        "category": "fans_and_culture",
        "angle": "Rivalry game reminds everyone why sports can still feel tribal and communal",
        "focus": "An emotion-rich story about history, local identity, and inherited meaning.",
        "questions": [
            "What makes this rivalry endure across generations?",
            "How do players handle the different emotional weight?",
            "Why do rivalry games often feel bigger than standings alone?",
        ],
    },
    {
        "id": "spo_059",
        "category": "off_field",
        "angle": "Athlete's off-field controversy forces team and sponsors into damage control",
        "focus": "A reputation story about accountability, branding, and competing loyalties.",
        "questions": [
            "What exactly happened off the field?",
            "How are the team and commercial partners responding?",
            "Can performance insulate an athlete from reputational fallout?",
        ],
    },
    {
        "id": "spo_060",
        "category": "off_field",
        "angle": "Legal trouble or investigation threatens to overshadow a promising season",
        "focus": "A difficult story where law, discipline, and competitive goals collide.",
        "questions": [
            "What is known factually and what remains uncertain?",
            "How quickly might the league or team act?",
            "What happens when unresolved cases hang over a season?",
        ],
    },
    {
        "id": "spo_061",
        "category": "integrity_and_doping",
        "angle": "Doping case shocks sport already struggling to defend credibility",
        "focus": "An integrity story about trust, science, and the fear of tainted results.",
        "questions": [
            "What substance or method is at the center of the case?",
            "How are officials and rivals responding?",
            "What damage does the case do to faith in the sport?",
        ],
    },
    {
        "id": "spo_062",
        "category": "integrity_and_doping",
        "angle": "Betting scandal raises old fears about whether competition can be trusted",
        "focus": "A legitimacy story about gambling, access to information, and sport's credibility.",
        "questions": [
            "What conduct is under suspicion?",
            "How vulnerable is the sport to betting-related manipulation?",
            "What safeguards clearly failed or may need tightening?",
        ],
    },
    {
        "id": "spo_063",
        "category": "analytics",
        "angle": "Data-driven approach transforms how a team wins",
        "focus": "A strategy story about analytics moving from theory into visible competitive edge.",
        "questions": [
            "What decisions are being most shaped by data?",
            "How are coaches balancing numbers with instinct?",
            "Does the success make the approach look inevitable to copycats?",
        ],
    },
    {
        "id": "spo_064",
        "category": "analytics",
        "angle": "Old-school critics push back as analytics-heavy tactics frustrate traditionalists",
        "focus": "A culture-within-sport story about what gets valued and what gets lost.",
        "questions": [
            "What style of play is drawing criticism?",
            "Are numbers optimizing wins at the expense of entertainment?",
            "How do players feel caught between philosophy camps?",
        ],
    },
    {
        "id": "spo_065",
        "category": "human_interest",
        "angle": "Athlete's personal journey makes victory mean more than the standings",
        "focus": "A human-centered story about adversity, sacrifice, and emotional resonance.",
        "questions": [
            "What obstacles shaped this athlete's path?",
            "Why did this moment connect so strongly with audiences?",
            "How does the story change how the performance is understood?",
        ],
    },
    {
        "id": "spo_066",
        "category": "human_interest",
        "angle": "Hometown hero returns and carries the weight of local expectation",
        "focus": "A belonging story about place, symbolism, and public emotion.",
        "questions": [
            "Why does this homecoming matter so much to the community?",
            "How is the athlete handling the added spotlight?",
            "What happens if the return does not match the dream?",
        ],
    },
    {
        "id": "spo_067",
        "category": "weather_and_conditions",
        "angle": "Extreme weather turns game or race into a survival and strategy test",
        "focus": "A conditions story where environment becomes one of the main competitors.",
        "questions": [
            "How did weather change tactics and performance?",
            "Were safety concerns handled credibly?",
            "Which athletes adapted best to the conditions?",
        ],
    },
    {
        "id": "spo_068",
        "category": "weather_and_conditions",
        "angle": "Venue issues or playing surface controversy sparks concern after injuries or poor play",
        "focus": "A practical infrastructure story about what should count as acceptable competitive conditions.",
        "questions": [
            "What problems did players or coaches highlight?",
            "Did the surface or venue affect outcome and safety?",
            "Could the controversy force changes going forward?",
        ],
    },
    {
        "id": "spo_069",
        "category": "expansion_and_relocation",
        "angle": "Expansion bid promises growth, but not everyone believes the sport should spread further",
        "focus": "A business and geography story about ambition, market logic, and dilution fears.",
        "questions": [
            "Why is expansion being considered now?",
            "What market or ownership case is being made?",
            "Could adding teams weaken competitive quality?",
        ],
    },
    {
        "id": "spo_070",
        "category": "expansion_and_relocation",
        "angle": "Relocation threat puts city identity and sports loyalty on the line",
        "focus": "A civic story about belonging, leverage, and the business reality of team movement.",
        "questions": [
            "Why is the franchise considering a move?",
            "How are local fans and politicians responding?",
            "What does losing a team mean beyond the economic argument?",
        ],
    },
    {
        "id": "spo_071",
        "category": "youth_and_development",
        "angle": "Academy or farm system starts producing talent faster than expected",
        "focus": "A development story about scouting, patience, and institutional advantage.",
        "questions": [
            "What is this system doing better than others?",
            "Which prospects look ready to matter soon?",
            "How much can internal development change a franchise's future?",
        ],
    },
    {
        "id": "spo_072",
        "category": "youth_and_development",
        "angle": "Burnout concerns grow as youth sports chase elite performance earlier and earlier",
        "focus": "A culture story about ambition, pressure, and the cost of specialization.",
        "questions": [
            "What signs of burnout or overuse are emerging?",
            "How are coaches and parents balancing aspiration with well-being?",
            "Does early intensity really improve long-term outcomes?",
        ],
    },
    {
        "id": "spo_073",
        "category": "sports_science",
        "angle": "Recovery, nutrition, and sleep become competitive weapons",
        "focus": "A modern performance story about marginal gains turning into meaningful edges.",
        "questions": [
            "What recovery methods are athletes relying on most?",
            "How much difference can small physical optimizations make?",
            "Which teams are most advanced in sports science?",
        ],
    },
    {
        "id": "spo_074",
        "category": "sports_science",
        "angle": "Load management debate exposes tension between health and entertainment",
        "focus": "A fan-versus-athlete welfare story about availability, preservation, and expectations.",
        "questions": [
            "Why are teams choosing to rest stars more aggressively?",
            "How do fans react when paying to see absent players?",
            "Can leagues protect both health and spectacle?",
        ],
    },
    {
        "id": "spo_075",
        "category": "media_and_narrative",
        "angle": "Sports media turns one quote into a week-long drama cycle",
        "focus": "A coverage story about how narratives can grow larger than the actual games.",
        "questions": [
            "What was said and why did it land so hard?",
            "Who is amplifying the quote and to what end?",
            "How much does the noise affect the athletes involved?",
        ],
    },
    {
        "id": "spo_076",
        "category": "media_and_narrative",
        "angle": "Documentary, mic'd-up clips, and behind-the-scenes access reshape fan connection",
        "focus": "A storytelling story about how sports are consumed as character drama as well as competition.",
        "questions": [
            "What kind of access do fans now expect?",
            "How does behind-the-scenes storytelling affect athlete image?",
            "Does more access deepen understanding or just create more noise?",
        ],
    },
    {
        "id": "spo_077",
        "category": "social_and_political",
        "angle": "Athlete activism sparks debate over what role sports figures should play in public life",
        "focus": "A culture story about platform, responsibility, and audience division.",
        "questions": [
            "What issue is the athlete speaking on?",
            "How are fans, teammates, and sponsors reacting?",
            "Can athletes separate performance from public voice anymore?",
        ],
    },
    {
        "id": "spo_078",
        "category": "social_and_political",
        "angle": "National anthem, protest, or symbolic gesture becomes the lead story around the event",
        "focus": "A moment story where ceremony and politics briefly overshadow competition.",
        "questions": [
            "What happened and why did it resonate so strongly?",
            "How are organizers and participants explaining the gesture?",
            "Will the moment have lasting impact beyond a single event?",
        ],
    },
    {
        "id": "spo_079",
        "category": "historic_perspective",
        "angle": "Team or athlete is chasing not just wins, but a place in history",
        "focus": "A big-picture story about comparison across eras and what makes greatness endure.",
        "questions": [
            "What historical company is now in view?",
            "How fair are cross-era comparisons in this sport?",
            "What intangible qualities make a run feel historic?",
        ],
    },
    {
        "id": "spo_080",
        "category": "historic_perspective",
        "angle": "Anniversary of an iconic sports moment reminds fans why memory is part of the game",
        "focus": "A retrospective story about nostalgia, legacy, and intergenerational storytelling.",
        "questions": [
            "Why does this moment still matter?",
            "How has the event been mythologized over time?",
            "What does revisiting it reveal about today's version of the sport?",
        ],
    },
    {
        "id": "spo_081",
        "category": "meta_sports",
        "angle": "The real story is no longer just who wins, but who handles pressure, attention, and expectation best",
        "focus": "A high-level framing story about modern sports as performance, media, and psychology all at once.",
        "questions": [
            "Which teams or athletes are thriving under the spotlight?",
            "How much do narrative and pressure shape actual outcomes?",
            "What does modern success require beyond talent alone?",
        ],
    },
    {
        "id": "spo_082",
        "category": "meta_sports",
        "angle": "Sports increasingly function as a 12-month drama, not just a schedule of games",
        "focus": "A broad industry-and-culture story about trades, rumors, media, and constant engagement.",
        "questions": [
            "What keeps fans invested even when games are not being played?",
            "How do leagues and media monetize nonstop attention?",
            "Has the off-field narrative become as important as the competition itself?",
        ],
    },
]
