from synthnews.prompts import Entity

ENTITIES: list[Entity] = [
    {
        "name": "Homicide",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Murder",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "First-degree murder",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Second-degree murder",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Felony murder",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Manslaughter",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Voluntary manslaughter",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Involuntary manslaughter",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Attempted murder",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Aggravated assault",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Assault",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Battery",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Domestic violence",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Sexual assault",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Rape",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Indecent assault",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Child abuse",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Elder abuse",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Kidnapping",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "False imprisonment",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Human trafficking",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Stalking",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Harassment",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Criminal threats",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Hate crime",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Terrorism",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Weapons trafficking",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Unlawful possession of a firearm",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Armed robbery",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Robbery",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Carjacking",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Burglary",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Breaking and entering",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Theft",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Grand theft auto",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Motor vehicle theft",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Petty larceny",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Grand larceny",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Shoplifting",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Possession of stolen property",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Criminal mischief",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Vandalism",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Arson",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Trespassing",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Drug possession",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Drug trafficking",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Drug distribution",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Manufacture of controlled substances",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Possession with intent to distribute",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Fraud",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Wire fraud",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Mail fraud",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Bank fraud",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Identity theft",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Credit card fraud",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Insurance fraud",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Mortgage fraud",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Securities fraud",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Insider trading",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Embezzlement",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Extortion",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Blackmail",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Bribery",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Public corruption",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Money laundering",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Tax evasion",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Racketeering (RICO)",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Conspiracy",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Obstruction of justice",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Perjury",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Contempt of court",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Witness tampering",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Evidence tampering",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Cybercrime",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Hacking",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Unauthorized access",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Phishing",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Ransomware attack",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Distributed denial-of-service (DDoS)",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Online harassment",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Driving under the influence (DUI)",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Impaired driving",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Reckless driving",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Hit and run",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Vehicular manslaughter",
        "entity_type": "crime_type",
        "country_or_region": "General",
        "notes": "Offence category / charge label used in crime reporting",
    },
    {
        "name": "Investigation",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Criminal complaint",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Police report",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Witness interview",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Interrogation",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Lineup",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Search warrant",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Arrest warrant",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Bench warrant",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "No-knock warrant",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Raid",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Search and seizure",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Probable cause",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Reasonable suspicion",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Miranda warning",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Charter rights (Canada)",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Bail",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Bail hearing",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Detention hearing",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Release conditions",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Protective order",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Restraining order",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Booking",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Charges filed",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Arraignment",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "First appearance",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Initial appearance",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Preliminary hearing",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Probable cause hearing",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Grand jury",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Indictment",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Information (criminal charging document)",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Summons",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Plea deal",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Plea bargain",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Plea hearing",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "No contest plea",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Guilty plea",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Not guilty plea",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Motion to dismiss",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Motion to suppress",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Suppression hearing",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Discovery",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Disclosure (Canada)",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Pretrial conference",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Voir dire",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Change of venue",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Jury selection",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Jury trial",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Bench trial",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Opening statements",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Direct examination",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Cross-examination",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Redirect examination",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Rebuttal",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Expert witness",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Closing arguments",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Jury instructions",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Deliberations",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Verdict",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Hung jury",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Mistrial",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Acquittal",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Conviction",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Sentencing",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Pre-sentence report",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Victim impact statement",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Restitution",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Probation",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Parole",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Time served",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Appeal",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Notice of appeal",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Appellate brief",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Oral argument",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Supreme Court review",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Habeas corpus",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Extradition",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Deportation proceedings",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Evidence",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Chain of custody",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "DNA evidence",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Fingerprints",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Ballistics",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Forensic analysis",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Autopsy",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Toxicology report",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Body camera footage",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Surveillance footage",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Cell-site location data",
        "entity_type": "procedure_or_legal_term",
        "country_or_region": "General",
        "notes": "Criminal justice process / courtroom term",
    },
    {
        "name": "Service de police de la Ville de Montréal (SPVM)",
        "entity_type": "law_enforcement",
        "country_or_region": "Canada (Quebec / Montreal)",
        "notes": "Municipal police service for Montreal",
    },
    {
        "name": "Sûreté du Québec (SQ)",
        "entity_type": "law_enforcement",
        "country_or_region": "Canada (Quebec)",
        "notes": "Provincial police service of Quebec",
    },
    {
        "name": "Royal Canadian Mounted Police (RCMP)",
        "entity_type": "law_enforcement",
        "country_or_region": "Canada",
        "notes": "Federal and national police service",
    },
    {
        "name": "Ontario Provincial Police (OPP)",
        "entity_type": "law_enforcement",
        "country_or_region": "Canada (Ontario)",
        "notes": "Provincial police service of Ontario",
    },
    {
        "name": "Toronto Police Service",
        "entity_type": "law_enforcement",
        "country_or_region": "Canada (Ontario / Toronto)",
        "notes": "Municipal police service for Toronto",
    },
    {
        "name": "Vancouver Police Department",
        "entity_type": "law_enforcement",
        "country_or_region": "Canada (British Columbia / Vancouver)",
        "notes": "Municipal police service for Vancouver",
    },
    {
        "name": "Canada Border Services Agency (CBSA)",
        "entity_type": "law_enforcement",
        "country_or_region": "Canada",
        "notes": "Border enforcement and immigration-related enforcement",
    },
    {
        "name": "Public Prosecution Service of Canada (PPSC)",
        "entity_type": "prosecution_service",
        "country_or_region": "Canada",
        "notes": "Federal prosecution service",
    },
    {
        "name": "Directeur des poursuites criminelles et pénales (DPCP)",
        "entity_type": "prosecution_service",
        "country_or_region": "Canada (Quebec)",
        "notes": "Quebec prosecution service",
    },
    {
        "name": "New York City Police Department (NYPD)",
        "entity_type": "law_enforcement",
        "country_or_region": "United States (New York)",
        "notes": "Municipal police department",
    },
    {
        "name": "Los Angeles Police Department (LAPD)",
        "entity_type": "law_enforcement",
        "country_or_region": "United States (California / Los Angeles)",
        "notes": "Municipal police department",
    },
    {
        "name": "Chicago Police Department (CPD)",
        "entity_type": "law_enforcement",
        "country_or_region": "United States (Illinois / Chicago)",
        "notes": "Municipal police department",
    },
    {
        "name": "Federal Bureau of Investigation (FBI)",
        "entity_type": "law_enforcement",
        "country_or_region": "United States",
        "notes": "Federal law enforcement and intelligence agency",
    },
    {
        "name": "Drug Enforcement Administration (DEA)",
        "entity_type": "law_enforcement",
        "country_or_region": "United States",
        "notes": "Federal drug law enforcement",
    },
    {
        "name": "Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF)",
        "entity_type": "law_enforcement",
        "country_or_region": "United States",
        "notes": "Federal law enforcement agency",
    },
    {
        "name": "United States Marshals Service",
        "entity_type": "law_enforcement",
        "country_or_region": "United States",
        "notes": "Federal law enforcement agency",
    },
    {
        "name": "United States Department of Justice (DOJ)",
        "entity_type": "justice_ministry",
        "country_or_region": "United States",
        "notes": "Federal executive department for law enforcement and justice",
    },
    {
        "name": "United States Attorney's Office",
        "entity_type": "prosecution_service",
        "country_or_region": "United States",
        "notes": "Federal prosecutors (U.S. Attorneys) in each federal district",
    },
    {
        "name": "District Attorney's Office",
        "entity_type": "prosecution_service",
        "country_or_region": "United States",
        "notes": "County/local prosecutors (varies by jurisdiction)",
    },
    {
        "name": "Public Defender's Office",
        "entity_type": "legal_aid",
        "country_or_region": "United States",
        "notes": "Government-funded criminal defense counsel",
    },
    {
        "name": "Metropolitan Police Service",
        "entity_type": "law_enforcement",
        "country_or_region": "United Kingdom (London)",
        "notes": "Police service for Greater London (excl. City of London)",
    },
    {
        "name": "City of London Police",
        "entity_type": "law_enforcement",
        "country_or_region": "United Kingdom (London)",
        "notes": "Police service for the City of London; known for economic crime focus",
    },
    {
        "name": "National Crime Agency (NCA)",
        "entity_type": "law_enforcement",
        "country_or_region": "United Kingdom",
        "notes": "National agency tackling serious and organized crime",
    },
    {
        "name": "Crown Prosecution Service (CPS)",
        "entity_type": "prosecution_service",
        "country_or_region": "United Kingdom (England and Wales)",
        "notes": "Prosecutes criminal cases investigated by police",
    },
    {
        "name": "Crown Office and Procurator Fiscal Service",
        "entity_type": "prosecution_service",
        "country_or_region": "United Kingdom (Scotland)",
        "notes": "Scottish prosecution service",
    },
    {
        "name": "INTERPOL",
        "entity_type": "international_organization",
        "country_or_region": "International",
        "notes": "International Criminal Police Organization",
    },
    {
        "name": "Europol",
        "entity_type": "international_organization",
        "country_or_region": "European Union",
        "notes": "EU agency for law enforcement cooperation",
    },
    {
        "name": "International Criminal Court (ICC)",
        "entity_type": "international_court",
        "country_or_region": "International (The Hague)",
        "notes": "International court established by the Rome Statute",
    },
    {
        "name": "Municipal court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "Magistrates' court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "Provincial court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "State court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "Superior court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "County court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "District court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "Crown Court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "High Court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "Court of Appeal",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "Supreme Court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "Federal court",
        "entity_type": "court_level",
        "country_or_region": "General",
        "notes": "Court level/type",
    },
    {
        "name": "U.S. District Court",
        "entity_type": "court_level",
        "country_or_region": "United States",
        "notes": "Federal trial court",
    },
    {
        "name": "U.S. Court of Appeals",
        "entity_type": "court_level",
        "country_or_region": "United States",
        "notes": "Federal appellate court",
    },
    {
        "name": "U.S. Supreme Court",
        "entity_type": "court",
        "country_or_region": "United States",
        "notes": "Highest court in the United States",
    },
    {
        "name": "Supreme Court of Canada",
        "entity_type": "court",
        "country_or_region": "Canada",
        "notes": "Highest court in Canada",
    },
    {
        "name": "UK Supreme Court",
        "entity_type": "court",
        "country_or_region": "United Kingdom",
        "notes": "Highest court in the United Kingdom",
    },
    {
        "name": "Quebec Court of Appeal",
        "entity_type": "court",
        "country_or_region": "Canada (Quebec)",
        "notes": "Appellate court in Quebec",
    },
    {
        "name": "Quebec Superior Court",
        "entity_type": "court",
        "country_or_region": "Canada (Quebec)",
        "notes": "Superior trial court in Quebec",
    },
    {
        "name": "Supreme Court Building (United States)",
        "entity_type": "building",
        "country_or_region": "United States (Washington, D.C.)",
        "notes": "Building housing the U.S. Supreme Court",
    },
    {
        "name": "Supreme Court of Canada Building",
        "entity_type": "building",
        "country_or_region": "Canada (Ottawa)",
        "notes": "Building housing the Supreme Court of Canada",
    },
    {
        "name": "Old Bailey (Central Criminal Court)",
        "entity_type": "building",
        "country_or_region": "United Kingdom (London)",
        "notes": "Historic criminal court building",
    },
    {
        "name": "Palais de justice de Montréal",
        "entity_type": "building",
        "country_or_region": "Canada (Quebec / Montreal)",
        "notes": "Major courthouse complex in Montreal",
    },
    {
        "name": "Manhattan Criminal Courthouse",
        "entity_type": "building",
        "country_or_region": "United States (New York City)",
        "notes": "Courthouse frequently referenced in NYC criminal cases",
    },
    {
        "name": "John G. Roberts, Jr.",
        "entity_type": "judge",
        "country_or_region": "United States",
        "notes": "Chief Justice of the United States",
    },
    {
        "name": "Clarence Thomas",
        "entity_type": "judge",
        "country_or_region": "United States",
        "notes": "Associate Justice of the Supreme Court of the United States",
    },
    {
        "name": "Samuel A. Alito, Jr.",
        "entity_type": "judge",
        "country_or_region": "United States",
        "notes": "Associate Justice of the Supreme Court of the United States",
    },
    {
        "name": "Sonia Sotomayor",
        "entity_type": "judge",
        "country_or_region": "United States",
        "notes": "Associate Justice of the Supreme Court of the United States",
    },
    {
        "name": "Elena Kagan",
        "entity_type": "judge",
        "country_or_region": "United States",
        "notes": "Associate Justice of the Supreme Court of the United States",
    },
    {
        "name": "Neil M. Gorsuch",
        "entity_type": "judge",
        "country_or_region": "United States",
        "notes": "Associate Justice of the Supreme Court of the United States",
    },
    {
        "name": "Brett M. Kavanaugh",
        "entity_type": "judge",
        "country_or_region": "United States",
        "notes": "Associate Justice of the Supreme Court of the United States",
    },
    {
        "name": "Amy Coney Barrett",
        "entity_type": "judge",
        "country_or_region": "United States",
        "notes": "Associate Justice of the Supreme Court of the United States",
    },
    {
        "name": "Ketanji Brown Jackson",
        "entity_type": "judge",
        "country_or_region": "United States",
        "notes": "Associate Justice of the Supreme Court of the United States",
    },
    {
        "name": "Richard Wagner",
        "entity_type": "judge",
        "country_or_region": "Canada",
        "notes": "Chief Justice of Canada",
    },
    {
        "name": "Andromache Karakatsanis",
        "entity_type": "judge",
        "country_or_region": "Canada",
        "notes": "Puisne Justice of the Supreme Court of Canada",
    },
    {
        "name": "Suzanne Côté",
        "entity_type": "judge",
        "country_or_region": "Canada",
        "notes": "Puisne Justice of the Supreme Court of Canada",
    },
    {
        "name": "Sheilah L. Martin",
        "entity_type": "judge",
        "country_or_region": "Canada",
        "notes": "Puisne Justice of the Supreme Court of Canada",
    },
    {
        "name": "Malcolm Rowe",
        "entity_type": "judge",
        "country_or_region": "Canada",
        "notes": "Puisne Justice of the Supreme Court of Canada",
    },
    {
        "name": "Michelle O’Bonsawin",
        "entity_type": "judge",
        "country_or_region": "Canada",
        "notes": "Puisne Justice of the Supreme Court of Canada",
    },
    {
        "name": "Nicholas Kasirer",
        "entity_type": "judge",
        "country_or_region": "Canada",
        "notes": "Puisne Justice of the Supreme Court of Canada",
    },
    {
        "name": "Mahmud Jamal",
        "entity_type": "judge",
        "country_or_region": "Canada",
        "notes": "Puisne Justice of the Supreme Court of Canada",
    },
    {
        "name": "Mary T. Moreau",
        "entity_type": "judge",
        "country_or_region": "Canada",
        "notes": "Puisne Justice of the Supreme Court of Canada",
    },
    {
        "name": "Clarence Darrow",
        "entity_type": "lawyer",
        "country_or_region": "United States",
        "notes": "American lawyer; notable trial advocate (historical)",
    },
    {
        "name": "Thurgood Marshall",
        "entity_type": "lawyer",
        "country_or_region": "United States",
        "notes": "Civil rights lawyer and jurist (historical)",
    },
    {
        "name": "Ruth Bader Ginsburg",
        "entity_type": "lawyer",
        "country_or_region": "United States",
        "notes": "Lawyer and jurist (historical)",
    },
    {
        "name": "Bryan Stevenson",
        "entity_type": "lawyer",
        "country_or_region": "United States",
        "notes": "Attorney and legal advocate",
    },
    {
        "name": "Amal Clooney",
        "entity_type": "lawyer",
        "country_or_region": "United Kingdom / International",
        "notes": "Barrister and international human rights lawyer",
    },
    {
        "name": "Gloria Allred",
        "entity_type": "lawyer",
        "country_or_region": "United States",
        "notes": "Attorney",
    },
    {
        "name": "Johnnie Cochran",
        "entity_type": "lawyer",
        "country_or_region": "United States",
        "notes": "Trial lawyer (historical)",
    },
    {
        "name": "F. Lee Bailey",
        "entity_type": "lawyer",
        "country_or_region": "United States",
        "notes": "Trial lawyer (historical)",
    },
    {
        "name": "David Boies",
        "entity_type": "lawyer",
        "country_or_region": "United States",
        "notes": "Litigator",
    },
    {
        "name": "Theodore B. Olson",
        "entity_type": "lawyer",
        "country_or_region": "United States",
        "notes": "Attorney (historical/public law)",
    },
    {
        "name": "Ted Bundy",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Convicted serial killer (historical)",
    },
    {
        "name": "Jeffrey Dahmer",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Convicted serial killer (historical)",
    },
    {
        "name": "John Wayne Gacy",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Convicted serial killer (historical)",
    },
    {
        "name": "Aileen Wuornos",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Convicted serial killer (historical)",
    },
    {
        "name": "Dennis Rader (BTK)",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Serial killer who was convicted; BTK moniker",
    },
    {
        "name": "David Berkowitz (Son of Sam)",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Serial killer who was convicted; Son of Sam moniker",
    },
    {
        "name": "Gary Ridgway (Green River Killer)",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Serial killer who was convicted; Green River Killer moniker",
    },
    {
        "name": "Joseph James DeAngelo (Golden State Killer)",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Serial offender who pleaded guilty/was convicted; Golden State Killer moniker",
    },
    {
        "name": "Ted Kaczynski (Unabomber)",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Domestic terrorist; convicted (historical)",
    },
    {
        "name": "Charles Manson",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Cult leader; convicted (historical)",
    },
    {
        "name": "Al Capone",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Organized crime figure; convicted (historical)",
    },
    {
        "name": "Bonnie Parker",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Outlaw (historical)",
    },
    {
        "name": "Clyde Barrow",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Outlaw (historical)",
    },
    {
        "name": "John Dillinger",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Bank robber/outlaw (historical)",
    },
    {
        "name": "Pablo Escobar",
        "entity_type": "person",
        "country_or_region": "Colombia",
        "notes": "Drug trafficker (historical)",
    },
    {
        "name": "Zodiac Killer",
        "entity_type": "person_or_alias",
        "country_or_region": "United States (California)",
        "notes": "Unidentified serial killer moniker",
    },
    {
        "name": "Jack the Ripper",
        "entity_type": "person_or_alias",
        "country_or_region": "United Kingdom (London)",
        "notes": "Unidentified serial killer moniker",
    },
]
