from synthnews.prompts.entities import Entity


ENTITIES: list[Entity] = [
    {
        "name": "Tim Cook",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; CEO of Apple",
    },
    {
        "name": "Satya Nadella",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; Chairman and CEO of Microsoft",
    },
    {
        "name": "Jensen Huang",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; Founder, President and CEO of NVIDIA",
    },
    {
        "name": "Sundar Pichai",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; CEO of Alphabet and Google",
    },
    {
        "name": "Andy Jassy",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; President and CEO of Amazon",
    },
    {
        "name": "Elon Musk",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; CEO of Tesla",
    },
    {
        "name": "Jamie Dimon",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Banker; Chairman and CEO of JPMorgan Chase",
    },
    {
        "name": "Larry Fink",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Investor and executive; Chairman and CEO of BlackRock",
    },
    {
        "name": "Greg Abel",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; President and CEO of Berkshire Hathaway",
    },
    {
        "name": "Warren Buffett",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Investor; Chairman of Berkshire Hathaway",
    },
    {
        "name": "Jerome Powell",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Central banker; Chair of the Federal Reserve",
    },
    {
        "name": "Christine Lagarde",
        "entity_type": "person",
        "country_or_region": "European Union",
        "notes": "Central banker; President of the European Central Bank",
    },
    {
        "name": "Tiff Macklem",
        "entity_type": "person",
        "country_or_region": "Canada",
        "notes": "Central banker; Governor of the Bank of Canada",
    },
    {
        "name": "Andrew Bailey",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Central banker; Governor of the Bank of England",
    },
    {
        "name": "Kazuo Ueda",
        "entity_type": "person",
        "country_or_region": "Japan",
        "notes": "Central banker; Governor of the Bank of Japan",
    },
    {
        "name": "Kristalina Georgieva",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Economist and policymaker; Managing Director of the IMF",
    },
    {
        "name": "Ngozi Okonjo-Iweala",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Economist and policymaker; Director-General of the WTO",
    },
    {
        "name": "Ajay Banga",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Business executive and policymaker; President of the World Bank Group",
    },
    {
        "name": "Pablo Hernández de Cos",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Central banker; General Manager of the BIS",
    },
    {
        "name": "Ray Dalio",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Investor; founder associated with Bridgewater Associates",
    },
    {
        "name": "Carl Icahn",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Investor and corporate raider",
    },
    {
        "name": "Cathie Wood",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Investor; founder and CEO associated with ARK Invest",
    },
    {
        "name": "George Soros",
        "entity_type": "person",
        "country_or_region": "United States / Hungary",
        "notes": "Investor and philanthropist",
    },
    {
        "name": "Bill Ackman",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Investor; hedge fund manager",
    },
    {
        "name": "Ken Griffin",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Investor; founder associated with Citadel",
    },
    {
        "name": "Stephen Schwarzman",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Investor and executive; associated with Blackstone",
    },
    {
        "name": "Mukesh Ambani",
        "entity_type": "person",
        "country_or_region": "India",
        "notes": "Business magnate; associated with Reliance Industries",
    },
    {
        "name": "Gautam Adani",
        "entity_type": "person",
        "country_or_region": "India",
        "notes": "Business magnate; associated with Adani Group",
    },
    {
        "name": "Bernard Arnault",
        "entity_type": "person",
        "country_or_region": "France",
        "notes": "Business magnate; associated with LVMH",
    },
    {
        "name": "Mary Barra",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; associated with General Motors",
    },
    {
        "name": "David Solomon",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Banker; associated with Goldman Sachs",
    },
    {
        "name": "Jane Fraser",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Banker; associated with Citigroup",
    },
    {
        "name": "Brian Moynihan",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Banker; associated with Bank of America",
    },
    {
        "name": "Ana Botín",
        "entity_type": "person",
        "country_or_region": "Spain",
        "notes": "Banker; associated with Banco Santander",
    },
    {
        "name": "Shantanu Narayen",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; associated with Adobe",
    },
    {
        "name": "Dara Khosrowshahi",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Business executive; associated with Uber",
    },
    {
        "name": "Apple",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Technology company",
    },
    {
        "name": "Microsoft",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Technology company",
    },
    {
        "name": "NVIDIA",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Semiconductor and AI computing company",
    },
    {
        "name": "Alphabet",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Technology holding company",
    },
    {
        "name": "Google",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Technology and advertising company",
    },
    {
        "name": "Amazon",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "E-commerce and cloud computing company",
    },
    {
        "name": "Tesla",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Electric vehicle and energy company",
    },
    {
        "name": "Meta Platforms",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Technology and social media company",
    },
    {
        "name": "OpenAI",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Artificial intelligence company",
    },
    {
        "name": "JPMorgan Chase",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Banking and financial services company",
    },
    {
        "name": "Goldman Sachs",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Investment bank",
    },
    {
        "name": "Morgan Stanley",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Investment bank and wealth manager",
    },
    {
        "name": "Bank of America",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Banking company",
    },
    {
        "name": "Citigroup",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Banking company",
    },
    {
        "name": "Wells Fargo",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Banking company",
    },
    {
        "name": "BlackRock",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Asset management company",
    },
    {
        "name": "Blackstone",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Alternative asset manager",
    },
    {
        "name": "Berkshire Hathaway",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Conglomerate holding company",
    },
    {
        "name": "Visa",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Payments company",
    },
    {
        "name": "Mastercard",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Payments company",
    },
    {
        "name": "PayPal",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Payments company",
    },
    {
        "name": "American Express",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Payments and financial services company",
    },
    {
        "name": "Samsung Electronics",
        "entity_type": "company",
        "country_or_region": "South Korea",
        "notes": "Electronics company",
    },
    {
        "name": "TSMC",
        "entity_type": "company",
        "country_or_region": "Taiwan",
        "notes": "Semiconductor manufacturer",
    },
    {
        "name": "Intel",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Semiconductor company",
    },
    {
        "name": "AMD",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Semiconductor company",
    },
    {
        "name": "Qualcomm",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Semiconductor and telecom company",
    },
    {
        "name": "Toyota",
        "entity_type": "company",
        "country_or_region": "Japan",
        "notes": "Automotive manufacturer",
    },
    {
        "name": "Volkswagen Group",
        "entity_type": "company",
        "country_or_region": "Germany",
        "notes": "Automotive manufacturer",
    },
    {
        "name": "General Motors",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Automotive manufacturer",
    },
    {
        "name": "Ford Motor Company",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Automotive manufacturer",
    },
    {
        "name": "BYD",
        "entity_type": "company",
        "country_or_region": "China",
        "notes": "Automotive and battery company",
    },
    {
        "name": "ExxonMobil",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Oil and gas company",
    },
    {
        "name": "Chevron",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Oil and gas company",
    },
    {
        "name": "Shell",
        "entity_type": "company",
        "country_or_region": "United Kingdom / Netherlands",
        "notes": "Oil and gas company",
    },
    {
        "name": "BP",
        "entity_type": "company",
        "country_or_region": "United Kingdom",
        "notes": "Oil and gas company",
    },
    {
        "name": "Saudi Aramco",
        "entity_type": "company",
        "country_or_region": "Saudi Arabia",
        "notes": "State-backed oil company",
    },
    {
        "name": "Rio Tinto",
        "entity_type": "company",
        "country_or_region": "United Kingdom / Australia",
        "notes": "Mining company",
    },
    {
        "name": "BHP",
        "entity_type": "company",
        "country_or_region": "Australia",
        "notes": "Mining company",
    },
    {
        "name": "Glencore",
        "entity_type": "company",
        "country_or_region": "Switzerland",
        "notes": "Commodity trader and mining company",
    },
    {
        "name": "Walmart",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Retail company",
    },
    {
        "name": "Costco",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Retail company",
    },
    {
        "name": "IKEA",
        "entity_type": "company",
        "country_or_region": "Sweden / Netherlands",
        "notes": "Retail company",
    },
    {
        "name": "Boeing",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Aerospace manufacturer",
    },
    {
        "name": "Airbus",
        "entity_type": "company",
        "country_or_region": "France / Europe",
        "notes": "Aerospace manufacturer",
    },
    {
        "name": "LVMH",
        "entity_type": "company",
        "country_or_region": "France",
        "notes": "Luxury goods company",
    },
    {
        "name": "Reliance Industries",
        "entity_type": "company",
        "country_or_region": "India",
        "notes": "Conglomerate",
    },
    {
        "name": "Adani Group",
        "entity_type": "company",
        "country_or_region": "India",
        "notes": "Conglomerate",
    },
    {
        "name": "Tencent",
        "entity_type": "company",
        "country_or_region": "China",
        "notes": "Technology company",
    },
    {
        "name": "Alibaba",
        "entity_type": "company",
        "country_or_region": "China",
        "notes": "Technology and e-commerce company",
    },
    {
        "name": "HSBC",
        "entity_type": "company",
        "country_or_region": "United Kingdom",
        "notes": "Banking company",
    },
    {
        "name": "UBS",
        "entity_type": "company",
        "country_or_region": "Switzerland",
        "notes": "Banking and wealth management company",
    },
    {
        "name": "Credit Suisse",
        "entity_type": "company",
        "country_or_region": "Switzerland",
        "notes": "Historic banking brand often referenced in business news",
    },
    {
        "name": "Deutsche Bank",
        "entity_type": "company",
        "country_or_region": "Germany",
        "notes": "Banking company",
    },
    {
        "name": "Banco Santander",
        "entity_type": "company",
        "country_or_region": "Spain",
        "notes": "Banking company",
    },
    {
        "name": "BNP Paribas",
        "entity_type": "company",
        "country_or_region": "France",
        "notes": "Banking company",
    },
    {
        "name": "Société Générale",
        "entity_type": "company",
        "country_or_region": "France",
        "notes": "Banking company",
    },
    {
        "name": "ING",
        "entity_type": "company",
        "country_or_region": "Netherlands",
        "notes": "Banking company",
    },
    {
        "name": "Siemens",
        "entity_type": "company",
        "country_or_region": "Germany",
        "notes": "Industrial company",
    },
    {
        "name": "GE Aerospace",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Industrial and aerospace company",
    },
    {
        "name": "Pfizer",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Pharmaceutical company",
    },
    {
        "name": "Johnson & Johnson",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Healthcare and pharmaceutical company",
    },
    {
        "name": "Novo Nordisk",
        "entity_type": "company",
        "country_or_region": "Denmark",
        "notes": "Pharmaceutical company",
    },
    {
        "name": "McDonald's",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Restaurant company",
    },
    {
        "name": "Starbucks",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Restaurant and consumer company",
    },
    {
        "name": "Uber",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Transportation platform company",
    },
    {
        "name": "Lyft",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Transportation platform company",
    },
    {
        "name": "Federal Reserve",
        "entity_type": "central_bank",
        "country_or_region": "United States",
        "notes": "Central bank of the United States",
    },
    {
        "name": "Federal Open Market Committee",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "Federal Reserve monetary policy committee",
    },
    {
        "name": "Federal Reserve Bank of New York",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "Important regional Federal Reserve Bank in financial-market operations",
    },
    {
        "name": "U.S. Treasury",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "Department overseeing federal finances and debt issuance",
    },
    {
        "name": "Securities and Exchange Commission",
        "entity_type": "regulator",
        "country_or_region": "United States",
        "notes": "U.S. securities regulator",
    },
    {
        "name": "Commodity Futures Trading Commission",
        "entity_type": "regulator",
        "country_or_region": "United States",
        "notes": "U.S. derivatives regulator",
    },
    {
        "name": "Federal Deposit Insurance Corporation",
        "entity_type": "regulator",
        "country_or_region": "United States",
        "notes": "U.S. bank deposit insurer and regulator",
    },
    {
        "name": "Office of the Comptroller of the Currency",
        "entity_type": "regulator",
        "country_or_region": "United States",
        "notes": "U.S. bank regulator",
    },
    {
        "name": "Consumer Financial Protection Bureau",
        "entity_type": "regulator",
        "country_or_region": "United States",
        "notes": "U.S. consumer finance regulator",
    },
    {
        "name": "Department of Commerce",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "U.S. department involved in trade and economic policy",
    },
    {
        "name": "Bank of Canada",
        "entity_type": "central_bank",
        "country_or_region": "Canada",
        "notes": "Central bank of Canada",
    },
    {
        "name": "Department of Finance Canada",
        "entity_type": "institution",
        "country_or_region": "Canada",
        "notes": "Federal finance department",
    },
    {
        "name": "Office of the Superintendent of Financial Institutions",
        "entity_type": "regulator",
        "country_or_region": "Canada",
        "notes": "Canadian prudential regulator",
    },
    {
        "name": "Canada Revenue Agency",
        "entity_type": "institution",
        "country_or_region": "Canada",
        "notes": "Canadian federal tax authority",
    },
    {
        "name": "European Central Bank",
        "entity_type": "central_bank",
        "country_or_region": "European Union",
        "notes": "Central bank for the euro area",
    },
    {
        "name": "European Commission",
        "entity_type": "institution",
        "country_or_region": "European Union",
        "notes": "Executive institution of the European Union",
    },
    {
        "name": "Eurogroup",
        "entity_type": "institution",
        "country_or_region": "European Union",
        "notes": "Meeting of euro area finance ministers",
    },
    {
        "name": "Directorate-General for Competition",
        "entity_type": "regulator",
        "country_or_region": "European Union",
        "notes": "EU competition authority within the European Commission",
    },
    {
        "name": "Bank of England",
        "entity_type": "central_bank",
        "country_or_region": "United Kingdom",
        "notes": "Central bank of the United Kingdom",
    },
    {
        "name": "Financial Conduct Authority",
        "entity_type": "regulator",
        "country_or_region": "United Kingdom",
        "notes": "UK financial services regulator",
    },
    {
        "name": "Prudential Regulation Authority",
        "entity_type": "regulator",
        "country_or_region": "United Kingdom",
        "notes": "UK prudential regulator",
    },
    {
        "name": "HM Treasury",
        "entity_type": "institution",
        "country_or_region": "United Kingdom",
        "notes": "UK finance ministry",
    },
    {
        "name": "Bank of Japan",
        "entity_type": "central_bank",
        "country_or_region": "Japan",
        "notes": "Central bank of Japan",
    },
    {
        "name": "Ministry of Economy, Trade and Industry",
        "entity_type": "institution",
        "country_or_region": "Japan",
        "notes": "Japanese ministry involved in industrial and trade policy",
    },
    {
        "name": "People's Bank of China",
        "entity_type": "central_bank",
        "country_or_region": "China",
        "notes": "Central bank of China",
    },
    {
        "name": "State Administration of Foreign Exchange",
        "entity_type": "regulator",
        "country_or_region": "China",
        "notes": "Chinese foreign-exchange authority",
    },
    {
        "name": "International Monetary Fund",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Multilateral lender and macroeconomic institution",
    },
    {
        "name": "World Bank Group",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Multilateral development finance institution",
    },
    {
        "name": "World Trade Organization",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Global trade rules institution",
    },
    {
        "name": "Bank for International Settlements",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Forum and bank for central banks",
    },
    {
        "name": "Financial Stability Board",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "International body for financial stability coordination",
    },
    {
        "name": "Organisation for Economic Co-operation and Development",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Economic policy organization",
    },
    {
        "name": "G7",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Group of Seven advanced economies",
    },
    {
        "name": "G20",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Group of Twenty major economies",
    },
    {
        "name": "Asian Infrastructure Investment Bank",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Multilateral development bank",
    },
    {
        "name": "European Bank for Reconstruction and Development",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Multilateral development bank",
    },
    {
        "name": "African Development Bank",
        "entity_type": "institution",
        "country_or_region": "International / Africa",
        "notes": "Regional development bank",
    },
    {
        "name": "Asian Development Bank",
        "entity_type": "institution",
        "country_or_region": "International / Asia",
        "notes": "Regional development bank",
    },
    {
        "name": "Inter-American Development Bank",
        "entity_type": "institution",
        "country_or_region": "International / Americas",
        "notes": "Regional development bank",
    },
    {
        "name": "International Labour Organization",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "UN agency focused on labour and employment",
    },
    {
        "name": "UN Trade and Development",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "UN body focused on trade and development",
    },
    {
        "name": "International Energy Agency",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Energy market and policy organization",
    },
    {
        "name": "Wall Street",
        "entity_type": "place",
        "country_or_region": "United States",
        "notes": "Financial district street in New York often used as a metonym for finance",
    },
    {
        "name": "New York Stock Exchange Building",
        "entity_type": "building",
        "country_or_region": "United States",
        "notes": "Iconic exchange building on Wall Street",
    },
    {
        "name": "Nasdaq MarketSite",
        "entity_type": "building",
        "country_or_region": "United States",
        "notes": "Nasdaq media and market site in Times Square",
    },
    {
        "name": "Eccles Building",
        "entity_type": "building",
        "country_or_region": "United States",
        "notes": "Main headquarters building of the Federal Reserve Board in Washington, D.C.",
    },
    {
        "name": "U.S. Treasury Building",
        "entity_type": "building",
        "country_or_region": "United States",
        "notes": "Headquarters of the U.S. Treasury",
    },
    {
        "name": "ECB Main Building",
        "entity_type": "building",
        "country_or_region": "Germany / European Union",
        "notes": "Main headquarters building of the European Central Bank in Frankfurt",
    },
    {
        "name": "Bank of England",
        "entity_type": "building",
        "country_or_region": "United Kingdom",
        "notes": "Historic Threadneedle Street headquarters often referenced in business reporting",
    },
    {
        "name": "Threadneedle Street",
        "entity_type": "place",
        "country_or_region": "United Kingdom",
        "notes": "Metonym for the Bank of England and UK monetary policy",
    },
    {
        "name": "City of London",
        "entity_type": "place",
        "country_or_region": "United Kingdom",
        "notes": "Historic financial district of London",
    },
    {
        "name": "Canary Wharf",
        "entity_type": "place",
        "country_or_region": "United Kingdom",
        "notes": "Major London business and banking district",
    },
    {
        "name": "Bay Street",
        "entity_type": "place",
        "country_or_region": "Canada",
        "notes": "Toronto financial district and metonym for Canadian finance",
    },
    {
        "name": "Silicon Valley",
        "entity_type": "place",
        "country_or_region": "United States",
        "notes": "Technology and venture-capital hub",
    },
    {
        "name": "Shenzhen",
        "entity_type": "place",
        "country_or_region": "China",
        "notes": "Manufacturing and technology hub",
    },
    {
        "name": "Pudong",
        "entity_type": "place",
        "country_or_region": "China",
        "notes": "Financial district of Shanghai",
    },
    {
        "name": "Davos",
        "entity_type": "place",
        "country_or_region": "Switzerland",
        "notes": "Conference city associated with the World Economic Forum",
    },
    {
        "name": "Frankfurt",
        "entity_type": "place",
        "country_or_region": "Germany",
        "notes": "Major European financial centre",
    },
    {
        "name": "Geneva",
        "entity_type": "place",
        "country_or_region": "Switzerland",
        "notes": "International city associated with trade and global institutions",
    },
    {
        "name": "Hong Kong",
        "entity_type": "place",
        "country_or_region": "Hong Kong",
        "notes": "Major international financial centre",
    },
    {
        "name": "Singapore",
        "entity_type": "place",
        "country_or_region": "Singapore",
        "notes": "Major international financial centre",
    },
    {
        "name": "Zurich",
        "entity_type": "place",
        "country_or_region": "Switzerland",
        "notes": "Financial centre",
    },
    {
        "name": "New York Stock Exchange",
        "entity_type": "market",
        "country_or_region": "United States",
        "notes": "Major stock exchange",
    },
    {
        "name": "Nasdaq",
        "entity_type": "market",
        "country_or_region": "United States",
        "notes": "Major stock exchange and market operator",
    },
    {
        "name": "Toronto Stock Exchange",
        "entity_type": "market",
        "country_or_region": "Canada",
        "notes": "Major Canadian stock exchange",
    },
    {
        "name": "TSX Venture Exchange",
        "entity_type": "market",
        "country_or_region": "Canada",
        "notes": "Canadian public venture market",
    },
    {
        "name": "London Stock Exchange",
        "entity_type": "market",
        "country_or_region": "United Kingdom",
        "notes": "Major stock exchange",
    },
    {
        "name": "Euronext",
        "entity_type": "market",
        "country_or_region": "Europe",
        "notes": "Pan-European exchange group",
    },
    {
        "name": "Deutsche Börse",
        "entity_type": "market",
        "country_or_region": "Germany",
        "notes": "Exchange operator",
    },
    {
        "name": "Xetra",
        "entity_type": "market",
        "country_or_region": "Germany",
        "notes": "Electronic trading venue operated by Deutsche Börse",
    },
    {
        "name": "SIX Swiss Exchange",
        "entity_type": "market",
        "country_or_region": "Switzerland",
        "notes": "Swiss stock exchange",
    },
    {
        "name": "Japan Exchange Group",
        "entity_type": "market",
        "country_or_region": "Japan",
        "notes": "Exchange group operating Japanese markets",
    },
    {
        "name": "Tokyo Stock Exchange",
        "entity_type": "market",
        "country_or_region": "Japan",
        "notes": "Major stock exchange",
    },
    {
        "name": "Shanghai Stock Exchange",
        "entity_type": "market",
        "country_or_region": "China",
        "notes": "Major stock exchange",
    },
    {
        "name": "Shenzhen Stock Exchange",
        "entity_type": "market",
        "country_or_region": "China",
        "notes": "Major stock exchange",
    },
    {
        "name": "Hong Kong Exchanges and Clearing",
        "entity_type": "market",
        "country_or_region": "Hong Kong",
        "notes": "Exchange and clearing operator",
    },
    {
        "name": "Bombay Stock Exchange",
        "entity_type": "market",
        "country_or_region": "India",
        "notes": "Indian stock exchange",
    },
    {
        "name": "National Stock Exchange of India",
        "entity_type": "market",
        "country_or_region": "India",
        "notes": "Indian stock exchange",
    },
    {
        "name": "Saudi Exchange",
        "entity_type": "market",
        "country_or_region": "Saudi Arabia",
        "notes": "Saudi stock exchange, also known as Tadawul",
    },
    {
        "name": "Australian Securities Exchange",
        "entity_type": "market",
        "country_or_region": "Australia",
        "notes": "Australian stock exchange",
    },
    {
        "name": "B3",
        "entity_type": "market",
        "country_or_region": "Brazil",
        "notes": "Brazilian exchange operator",
    },
    {
        "name": "CME Group",
        "entity_type": "market",
        "country_or_region": "United States",
        "notes": "Derivatives marketplace operator",
    },
    {
        "name": "Chicago Mercantile Exchange",
        "entity_type": "market",
        "country_or_region": "United States",
        "notes": "Futures exchange",
    },
    {
        "name": "Chicago Board of Trade",
        "entity_type": "market",
        "country_or_region": "United States",
        "notes": "Futures and commodity exchange",
    },
    {
        "name": "New York Mercantile Exchange",
        "entity_type": "market",
        "country_or_region": "United States",
        "notes": "Commodity and energy exchange",
    },
    {
        "name": "COMEX",
        "entity_type": "market",
        "country_or_region": "United States",
        "notes": "Metals futures market",
    },
    {
        "name": "Intercontinental Exchange",
        "entity_type": "market",
        "country_or_region": "United States / International",
        "notes": "Exchange and market infrastructure operator",
    },
    {
        "name": "London Metal Exchange",
        "entity_type": "market",
        "country_or_region": "United Kingdom",
        "notes": "Industrial metals exchange",
    },
    {
        "name": "Cboe Global Markets",
        "entity_type": "market",
        "country_or_region": "United States",
        "notes": "Exchange operator",
    },
    {
        "name": "Dubai Mercantile Exchange",
        "entity_type": "market",
        "country_or_region": "United Arab Emirates",
        "notes": "Energy futures market",
    },
    {
        "name": "Singapore Exchange",
        "entity_type": "market",
        "country_or_region": "Singapore",
        "notes": "Exchange operator",
    },
    {
        "name": "Korea Exchange",
        "entity_type": "market",
        "country_or_region": "South Korea",
        "notes": "South Korean exchange operator",
    },
    {
        "name": "ICE Futures Europe",
        "entity_type": "market",
        "country_or_region": "United Kingdom",
        "notes": "Futures market including energy contracts",
    },
    {
        "name": "ICE Brent",
        "entity_type": "commodity_benchmark",
        "country_or_region": "International",
        "notes": "Brent crude oil benchmark traded via ICE",
    },
    {
        "name": "WTI Crude",
        "entity_type": "commodity_benchmark",
        "country_or_region": "United States",
        "notes": "West Texas Intermediate crude benchmark",
    },
    {
        "name": "Henry Hub",
        "entity_type": "commodity_benchmark",
        "country_or_region": "United States",
        "notes": "Natural gas benchmark",
    },
    {
        "name": "TTF Gas",
        "entity_type": "commodity_benchmark",
        "country_or_region": "Netherlands / Europe",
        "notes": "European natural gas benchmark",
    },
    {
        "name": "COMEX Gold",
        "entity_type": "commodity_benchmark",
        "country_or_region": "United States",
        "notes": "Gold futures benchmark market",
    },
    {
        "name": "AFL-CIO",
        "entity_type": "labor_union",
        "country_or_region": "United States",
        "notes": "National federation of labor unions",
    },
    {
        "name": "International Brotherhood of Teamsters",
        "entity_type": "labor_union",
        "country_or_region": "United States / Canada",
        "notes": "Large labor union also known as the Teamsters",
    },
    {
        "name": "United Auto Workers",
        "entity_type": "labor_union",
        "country_or_region": "United States / Canada",
        "notes": "Industrial labor union also known as the UAW",
    },
    {
        "name": "Service Employees International Union",
        "entity_type": "labor_union",
        "country_or_region": "United States / Canada",
        "notes": "Large labor union also known as SEIU",
    },
    {
        "name": "Unifor",
        "entity_type": "labor_union",
        "country_or_region": "Canada",
        "notes": "Canadian labor union",
    },
    {
        "name": "United Steelworkers",
        "entity_type": "labor_union",
        "country_or_region": "United States / Canada",
        "notes": "Industrial labor union",
    },
    {
        "name": "Unite the Union",
        "entity_type": "labor_union",
        "country_or_region": "United Kingdom / Ireland",
        "notes": "Labour union",
    },
    {
        "name": "IG Metall",
        "entity_type": "labor_union",
        "country_or_region": "Germany",
        "notes": "German metalworkers' union",
    },
    {
        "name": "ver.di",
        "entity_type": "labor_union",
        "country_or_region": "Germany",
        "notes": "German services union",
    },
    {
        "name": "Retail, Wholesale and Department Store Union",
        "entity_type": "labor_union",
        "country_or_region": "United States",
        "notes": "U.S. labor union often referenced in retail and warehouse organizing",
    },
    {
        "name": "International Longshore and Warehouse Union",
        "entity_type": "labor_union",
        "country_or_region": "United States / Canada",
        "notes": "Dockworker and warehouse labor union",
    },
    {
        "name": "OPEC",
        "entity_type": "cartel",
        "country_or_region": "International",
        "notes": "Organization of the Petroleum Exporting Countries",
    },
    {
        "name": "OPEC+",
        "entity_type": "cartel",
        "country_or_region": "International",
        "notes": "Expanded oil-producer coordination group centered on OPEC members plus partners",
    },
    {
        "name": "OAPEC",
        "entity_type": "institution",
        "country_or_region": "Middle East / North Africa",
        "notes": "Organization of Arab Petroleum Exporting Countries",
    },
    {
        "name": "Gas Exporting Countries Forum",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Gas producer coordination forum",
    },
    {
        "name": "NAFTA",
        "entity_type": "trade_agreement",
        "country_or_region": "North America",
        "notes": "North American Free Trade Agreement",
    },
    {
        "name": "USMCA",
        "entity_type": "trade_agreement",
        "country_or_region": "United States / Mexico / Canada",
        "notes": "United States-Mexico-Canada Agreement",
    },
    {
        "name": "CUSMA",
        "entity_type": "trade_agreement",
        "country_or_region": "Canada / United States / Mexico",
        "notes": "Canadian name for the USMCA",
    },
    {
        "name": "Canada-United States-Mexico Agreement",
        "entity_type": "trade_agreement",
        "country_or_region": "Canada / United States / Mexico",
        "notes": "Formal name often shortened to CUSMA or USMCA",
    },
    {
        "name": "Comprehensive and Progressive Agreement for Trans-Pacific Partnership",
        "entity_type": "trade_agreement",
        "country_or_region": "Indo-Pacific",
        "notes": "Free trade agreement usually shortened to CPTPP",
    },
    {
        "name": "CPTPP",
        "entity_type": "trade_agreement",
        "country_or_region": "Indo-Pacific",
        "notes": "Abbreviation for the Comprehensive and Progressive Agreement for Trans-Pacific "
        "Partnership",
    },
    {
        "name": "Trans-Pacific Partnership",
        "entity_type": "trade_agreement",
        "country_or_region": "Indo-Pacific",
        "notes": "Trade agreement project usually shortened to TPP",
    },
    {
        "name": "TPP",
        "entity_type": "trade_agreement",
        "country_or_region": "Indo-Pacific",
        "notes": "Abbreviation for the Trans-Pacific Partnership",
    },
    {
        "name": "Regional Comprehensive Economic Partnership",
        "entity_type": "trade_agreement",
        "country_or_region": "Asia-Pacific",
        "notes": "Free trade agreement usually shortened to RCEP",
    },
    {
        "name": "RCEP",
        "entity_type": "trade_agreement",
        "country_or_region": "Asia-Pacific",
        "notes": "Abbreviation for the Regional Comprehensive Economic Partnership",
    },
    {
        "name": "Comprehensive Economic and Trade Agreement",
        "entity_type": "trade_agreement",
        "country_or_region": "Canada / European Union",
        "notes": "Trade agreement usually shortened to CETA",
    },
    {
        "name": "CETA",
        "entity_type": "trade_agreement",
        "country_or_region": "Canada / European Union",
        "notes": "Abbreviation for the Comprehensive Economic and Trade Agreement",
    },
    {
        "name": "African Continental Free Trade Area",
        "entity_type": "trade_agreement",
        "country_or_region": "Africa",
        "notes": "Pan-African trade agreement usually shortened to AfCFTA",
    },
    {
        "name": "AfCFTA",
        "entity_type": "trade_agreement",
        "country_or_region": "Africa",
        "notes": "Abbreviation for the African Continental Free Trade Area",
    },
    {
        "name": "Mercosur",
        "entity_type": "economic_bloc",
        "country_or_region": "South America",
        "notes": "Southern Common Market",
    },
    {
        "name": "European Single Market",
        "entity_type": "economic_bloc",
        "country_or_region": "European Union",
        "notes": "EU internal market",
    },
    {
        "name": "ASEAN Free Trade Area",
        "entity_type": "trade_agreement",
        "country_or_region": "Southeast Asia",
        "notes": "Regional trade arrangement usually shortened to AFTA",
    },
    {
        "name": "AFTA",
        "entity_type": "trade_agreement",
        "country_or_region": "Southeast Asia",
        "notes": "Abbreviation for the ASEAN Free Trade Area",
    },
    {
        "name": "EU-UK Trade and Cooperation Agreement",
        "entity_type": "trade_agreement",
        "country_or_region": "European Union / United Kingdom",
        "notes": "Post-Brexit trade agreement",
    },
    {
        "name": "CAFTA-DR",
        "entity_type": "trade_agreement",
        "country_or_region": "Central America / United States / Dominican Republic",
        "notes": "Dominican Republic-Central America Free Trade Agreement",
    },
    {
        "name": "KORUS FTA",
        "entity_type": "trade_agreement",
        "country_or_region": "United States / South Korea",
        "notes": "United States-Korea Free Trade Agreement",
    },
    {
        "name": "Pacific Alliance",
        "entity_type": "economic_bloc",
        "country_or_region": "Latin America",
        "notes": "Latin American trade bloc",
    },
    {
        "name": "General Agreement on Tariffs and Trade",
        "entity_type": "trade_agreement",
        "country_or_region": "International",
        "notes": "Historic multilateral trade agreement usually shortened to GATT",
    },
    {
        "name": "GATT",
        "entity_type": "trade_agreement",
        "country_or_region": "International",
        "notes": "Abbreviation for the General Agreement on Tariffs and Trade",
    },
    {
        "name": "Agreement Establishing the World Trade Organization",
        "entity_type": "trade_agreement",
        "country_or_region": "International",
        "notes": "Foundational WTO agreement",
    },
    {
        "name": "TRIPS Agreement",
        "entity_type": "trade_agreement",
        "country_or_region": "International",
        "notes": "Trade-Related Aspects of Intellectual Property Rights",
    },
    {
        "name": "US-China Phase One Trade Agreement",
        "entity_type": "trade_agreement",
        "country_or_region": "United States / China",
        "notes": "Bilateral trade agreement",
    },
]
