from synthnews.prompts.entities import Entity

ENTITIES: list[Entity] = [
    {
        "name": "Academy of Motion Picture Arts and Sciences",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "Organization behind the Academy Awards (Oscars)",
    },
    {
        "name": "Academy Awards (Oscars)",
        "entity_type": "award_show",
        "country_or_region": "United States",
        "notes": "Annual film awards",
    },
    {
        "name": "The Recording Academy",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "Organization behind the GRAMMY Awards",
    },
    {
        "name": "GRAMMY Awards",
        "entity_type": "award_show",
        "country_or_region": "United States",
        "notes": "Annual music awards",
    },
    {
        "name": "Golden Globe Awards",
        "entity_type": "award_show",
        "country_or_region": "United States",
        "notes": "Film and TV awards",
    },
    {
        "name": "British Academy Film Awards (BAFTA)",
        "entity_type": "award_show",
        "country_or_region": "United Kingdom",
        "notes": "Film awards",
    },
    {
        "name": "Primetime Emmy Awards",
        "entity_type": "award_show",
        "country_or_region": "United States",
        "notes": "Television awards",
    },
    {
        "name": "Tony Awards",
        "entity_type": "award_show",
        "country_or_region": "United States",
        "notes": "Theatre awards",
    },
    {
        "name": "Screen Actors Guild Awards (SAG Awards)",
        "entity_type": "award_show",
        "country_or_region": "United States",
        "notes": "Acting awards",
    },
    {
        "name": "Cannes Film Festival (Festival de Cannes)",
        "entity_type": "festival",
        "country_or_region": "France",
        "notes": "International film festival",
    },
    {
        "name": "Sundance Film Festival",
        "entity_type": "festival",
        "country_or_region": "United States",
        "notes": "Independent film festival",
    },
    {
        "name": "Toronto International Film Festival (TIFF)",
        "entity_type": "festival",
        "country_or_region": "Canada",
        "notes": "Major film festival",
    },
    {
        "name": "Venice Film Festival",
        "entity_type": "festival",
        "country_or_region": "Italy",
        "notes": "International film festival",
    },
    {
        "name": "Berlin International Film Festival (Berlinale)",
        "entity_type": "festival",
        "country_or_region": "Germany",
        "notes": "International film festival",
    },
    {
        "name": "South by Southwest (SXSW)",
        "entity_type": "festival",
        "country_or_region": "United States",
        "notes": "Music/film/interactive festival",
    },
    {
        "name": "Coachella Valley Music and Arts Festival",
        "entity_type": "festival",
        "country_or_region": "United States",
        "notes": "Music and arts festival",
    },
    {
        "name": "Glastonbury Festival",
        "entity_type": "festival",
        "country_or_region": "United Kingdom",
        "notes": "Music festival",
    },
    {
        "name": "Lollapalooza",
        "entity_type": "festival",
        "country_or_region": "United States",
        "notes": "Music festival brand",
    },
    {
        "name": "Tomorrowland",
        "entity_type": "festival",
        "country_or_region": "Belgium",
        "notes": "Electronic music festival",
    },
    {
        "name": "Rock in Rio",
        "entity_type": "festival",
        "country_or_region": "Brazil",
        "notes": "Music festival brand",
    },
    {
        "name": "The Walt Disney Company",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Entertainment company",
    },
    {
        "name": "Walt Disney Studios",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Film studio",
    },
    {
        "name": "Pixar Animation Studios",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Animation studio",
    },
    {
        "name": "Marvel Studios",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Film/TV studio",
    },
    {
        "name": "Lucasfilm",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Film/TV studio",
    },
    {
        "name": "Warner Bros.",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Film/TV studio",
    },
    {
        "name": "Universal Pictures",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Film studio",
    },
    {
        "name": "Paramount Pictures",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Film studio",
    },
    {
        "name": "Sony Pictures Entertainment",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Film/TV production and distribution",
    },
    {
        "name": "Columbia Pictures",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Film studio",
    },
    {
        "name": "20th Century Studios",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Film studio",
    },
    {
        "name": "A24",
        "entity_type": "studio",
        "country_or_region": "United States",
        "notes": "Independent studio",
    },
    {
        "name": "Netflix",
        "entity_type": "streaming_platform",
        "country_or_region": "United States",
        "notes": "Streaming service",
    },
    {
        "name": "Prime Video",
        "entity_type": "streaming_platform",
        "country_or_region": "United States",
        "notes": "Streaming service",
    },
    {
        "name": "Apple TV+",
        "entity_type": "streaming_platform",
        "country_or_region": "United States",
        "notes": "Streaming service",
    },
    {
        "name": "HBO",
        "entity_type": "tv_network",
        "country_or_region": "United States",
        "notes": "Television network",
    },
    {
        "name": "Max",
        "entity_type": "streaming_platform",
        "country_or_region": "United States",
        "notes": "Streaming service",
    },
    {
        "name": "Disney+",
        "entity_type": "streaming_platform",
        "country_or_region": "United States",
        "notes": "Streaming service",
    },
    {
        "name": "Hulu",
        "entity_type": "streaming_platform",
        "country_or_region": "United States",
        "notes": "Streaming service",
    },
    {
        "name": "Peacock",
        "entity_type": "streaming_platform",
        "country_or_region": "United States",
        "notes": "Streaming service",
    },
    {
        "name": "Paramount+",
        "entity_type": "streaming_platform",
        "country_or_region": "United States",
        "notes": "Streaming service",
    },
    {
        "name": "YouTube",
        "entity_type": "platform",
        "country_or_region": "United States",
        "notes": "Video platform",
    },
    {
        "name": "Spotify",
        "entity_type": "platform",
        "country_or_region": "Sweden / International",
        "notes": "Music streaming platform",
    },
    {
        "name": "Apple Music",
        "entity_type": "platform",
        "country_or_region": "United States / International",
        "notes": "Music streaming platform",
    },
    {
        "name": "Universal Music Group",
        "entity_type": "record_label",
        "country_or_region": "International",
        "notes": "Major record label group",
    },
    {
        "name": "Sony Music Entertainment",
        "entity_type": "record_label",
        "country_or_region": "International",
        "notes": "Major record label group",
    },
    {
        "name": "Warner Music Group",
        "entity_type": "record_label",
        "country_or_region": "International",
        "notes": "Major record label group",
    },
    {
        "name": "Live Nation Entertainment",
        "entity_type": "company",
        "country_or_region": "United States",
        "notes": "Concert promotion",
    },
    {
        "name": "Ticketmaster",
        "entity_type": "company",
        "country_or_region": "United States / International",
        "notes": "Ticketing platform",
    },
    {
        "name": "Creative Artists Agency (CAA)",
        "entity_type": "talent_agency",
        "country_or_region": "United States",
        "notes": "Talent agency",
    },
    {
        "name": "WME (William Morris Endeavor)",
        "entity_type": "talent_agency",
        "country_or_region": "United States",
        "notes": "Talent agency",
    },
    {
        "name": "United Talent Agency (UTA)",
        "entity_type": "talent_agency",
        "country_or_region": "United States",
        "notes": "Talent agency",
    },
    {
        "name": "The Eras Tour",
        "entity_type": "tour",
        "country_or_region": "International",
        "notes": "Concert tour by Taylor Swift",
    },
    {
        "name": "Renaissance World Tour",
        "entity_type": "tour",
        "country_or_region": "International",
        "notes": "Concert tour by Beyoncé",
    },
    {
        "name": "Music of the Spheres World Tour",
        "entity_type": "tour",
        "country_or_region": "International",
        "notes": "Concert tour by Coldplay",
    },
    {
        "name": "U2:UV Achtung Baby Live at Sphere",
        "entity_type": "residency",
        "country_or_region": "United States (Nevada)",
        "notes": "Concert residency by U2 at Sphere",
    },
    {
        "name": "After Hours til Dawn Tour",
        "entity_type": "tour",
        "country_or_region": "International",
        "notes": "Concert tour by the Weeknd",
    },
    {
        "name": "+−=÷× Tour (The Mathematics Tour)",
        "entity_type": "tour",
        "country_or_region": "International",
        "notes": "Concert tour by Ed Sheeran",
    },
    {
        "name": "Farewell Yellow Brick Road",
        "entity_type": "tour",
        "country_or_region": "International",
        "notes": "Concert tour by Elton John",
    },
    {
        "name": "Love On Tour",
        "entity_type": "tour",
        "country_or_region": "International",
        "notes": "Concert tour by Harry Styles",
    },
    {
        "name": "Madison Square Garden",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "New York City arena",
    },
    {
        "name": "Radio City Music Hall",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "New York City theater",
    },
    {
        "name": "Carnegie Hall",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "New York City concert venue",
    },
    {
        "name": "The Apollo Theater",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Harlem theater",
    },
    {
        "name": "Hollywood Bowl",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Los Angeles amphitheatre",
    },
    {
        "name": "Dolby Theatre",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Hollywood theater (Oscars venue)",
    },
    {
        "name": "TCL Chinese Theatre",
        "entity_type": "cinema",
        "country_or_region": "United States",
        "notes": "Hollywood movie theater",
    },
    {
        "name": "The Greek Theatre (Los Angeles)",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Los Angeles amphitheatre",
    },
    {
        "name": "Red Rocks Amphitheatre",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Colorado amphitheatre",
    },
    {
        "name": "Crypto.com Arena",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Los Angeles arena",
    },
    {
        "name": "Kia Forum",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Inglewood arena",
    },
    {
        "name": "SoFi Stadium",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Inglewood stadium",
    },
    {
        "name": "Allegiant Stadium",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Las Vegas stadium",
    },
    {
        "name": "Sphere",
        "entity_type": "venue",
        "country_or_region": "United States",
        "notes": "Las Vegas Valley venue",
    },
    {
        "name": "Bell Centre",
        "entity_type": "venue",
        "country_or_region": "Canada",
        "notes": "Montreal arena",
    },
    {
        "name": "Scotiabank Arena",
        "entity_type": "venue",
        "country_or_region": "Canada",
        "notes": "Toronto arena",
    },
    {
        "name": "Place Bell",
        "entity_type": "venue",
        "country_or_region": "Canada",
        "notes": "Laval arena",
    },
    {
        "name": "Cineplex Cinemas",
        "entity_type": "cinema_chain",
        "country_or_region": "Canada",
        "notes": "Cinema chain",
    },
    {
        "name": "AMC Theatres",
        "entity_type": "cinema_chain",
        "country_or_region": "United States",
        "notes": "Cinema chain",
    },
    {
        "name": "Regal Cinemas",
        "entity_type": "cinema_chain",
        "country_or_region": "United States",
        "notes": "Cinema chain",
    },
    {
        "name": "The O2 Arena",
        "entity_type": "venue",
        "country_or_region": "United Kingdom",
        "notes": "London arena",
    },
    {
        "name": "Royal Albert Hall",
        "entity_type": "venue",
        "country_or_region": "United Kingdom",
        "notes": "London concert hall",
    },
    {
        "name": "Wembley Stadium",
        "entity_type": "venue",
        "country_or_region": "United Kingdom",
        "notes": "London stadium",
    },
    {
        "name": "Odeon Luxe Leicester Square",
        "entity_type": "cinema",
        "country_or_region": "United Kingdom",
        "notes": "London cinema",
    },
    {
        "name": "Palais des Festivals et des Congrès",
        "entity_type": "venue",
        "country_or_region": "France",
        "notes": "Cannes festival venue",
    },
    {
        "name": "Accor Arena",
        "entity_type": "venue",
        "country_or_region": "France",
        "notes": "Paris arena",
    },
    {
        "name": "La Scala (Teatro alla Scala)",
        "entity_type": "venue",
        "country_or_region": "Italy",
        "notes": "Milan opera house",
    },
    {
        "name": "Sydney Opera House",
        "entity_type": "venue",
        "country_or_region": "Australia",
        "notes": "Sydney performing arts venue",
    },
    {
        "name": "Rod Laver Arena",
        "entity_type": "venue",
        "country_or_region": "Australia",
        "notes": "Melbourne arena",
    },
    {
        "name": "Tokyo Dome",
        "entity_type": "venue",
        "country_or_region": "Japan",
        "notes": "Tokyo stadium/venue",
    },
    {
        "name": "Nippon Budokan",
        "entity_type": "venue",
        "country_or_region": "Japan",
        "notes": "Tokyo arena",
    },
    {
        "name": "Barbie",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Oppenheimer",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Dune",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Dune: Part Two",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Avatar",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Avatar: The Way of Water",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Titanic",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Godfather",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Godfather Part II",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Pulp Fiction",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Dark Knight",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Inception",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Interstellar",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Lord of the Rings: The Fellowship of the Ring",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Lord of the Rings: The Two Towers",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Lord of the Rings: The Return of the King",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Harry Potter and the Sorcerer's Stone",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Harry Potter and the Deathly Hallows – Part 2",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Star Wars: A New Hope",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Star Wars: The Empire Strikes Back",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Rogue One: A Star Wars Story",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Avengers",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Avengers: Endgame",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Black Panther",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Spider-Man: No Way Home",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Jurassic Park",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Lion King",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Frozen",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Toy Story",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Inside Out",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Matrix",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Forrest Gump",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Shawshank Redemption",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "The Silence of the Lambs",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Gladiator",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "La La Land",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "A Star Is Born",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Top Gun: Maverick",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Parasite",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Spirited Away",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Get Out",
        "entity_type": "movie",
        "country_or_region": "General",
        "notes": "Film title",
    },
    {
        "name": "Game of Thrones",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "House of the Dragon",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Breaking Bad",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Better Call Saul",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Stranger Things",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "The Crown",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "The Mandalorian",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "The Last of Us",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Succession",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "The Bear",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Euphoria",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Saturday Night Live",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "The Simpsons",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Black Mirror",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Severance",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "The Boys",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "The White Lotus",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Friends",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "The Office",
        "entity_type": "tv_show",
        "country_or_region": "General",
        "notes": "Television/streaming series",
    },
    {
        "name": "Leonardo DiCaprio",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Meryl Streep",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Denzel Washington",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Tom Cruise",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Brad Pitt",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Angelina Jolie",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Scarlett Johansson",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Natalie Portman",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Jennifer Lawrence",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Emma Stone",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Ryan Gosling",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Margot Robbie",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Christian Bale",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Robert Downey Jr.",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Keanu Reeves",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Hugh Jackman",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Nicole Kidman",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Viola Davis",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Cate Blanchett",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Joaquin Phoenix",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Zendaya",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Timothée Chalamet",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Florence Pugh",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Austin Butler",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Pedro Pascal",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Harrison Ford",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Al Pacino",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Robert De Niro",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Charlize Theron",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Cillian Murphy",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Idris Elba",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Daniel Craig",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Benedict Cumberbatch",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Paul Rudd",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Ryan Reynolds",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Halle Berry",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Will Smith",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Jamie Foxx",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Jackie Chan",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Michelle Yeoh",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Actor / public figure",
    },
    {
        "name": "Christopher Nolan",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "Greta Gerwig",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "Martin Scorsese",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "Quentin Tarantino",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "Steven Spielberg",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "James Cameron",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "Denis Villeneuve",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "Bong Joon-ho",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "Wes Anderson",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "Jordan Peele",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Director / public figure",
    },
    {
        "name": "Taylor Swift",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Beyoncé",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Adele",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Ed Sheeran",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Drake",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "The Weeknd",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Billie Eilish",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Kendrick Lamar",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Rihanna",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Lady Gaga",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Bruno Mars",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Justin Bieber",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Bad Bunny",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Post Malone",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "SZA",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Doja Cat",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Olivia Rodrigo",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Harry Styles",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Dua Lipa",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Ariana Grande",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Shakira",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Karol G",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Coldplay",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Band / public figure",
    },
    {
        "name": "U2",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Band / public figure",
    },
    {
        "name": "Elton John",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "Madonna",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Musician / public figure",
    },
    {
        "name": "BTS",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Group / public figure",
    },
    {
        "name": "BLACKPINK",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Group / public figure",
    },
    {
        "name": "Metallica",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Band / public figure",
    },
    {
        "name": "Green Day",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "Band / public figure",
    },
]
