from synthnews.prompts import Entity


ENTITIES: list[Entity] = [
    # -------------------------------------------------------------------------
    # PEOPLE: current officeholders and high-profile politicians
    # -------------------------------------------------------------------------
    {
        "name": "Donald Trump",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Politician; President of the United States",
    },
    {
        "name": "JD Vance",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Politician; Vice President of the United States",
    },
    {
        "name": "Mark Carney",
        "entity_type": "person",
        "country_or_region": "Canada",
        "notes": "Politician; Prime Minister of Canada",
    },
    {
        "name": "Keir Starmer",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Politician; Prime Minister of the United Kingdom",
    },
    {
        "name": "Emmanuel Macron",
        "entity_type": "person",
        "country_or_region": "France",
        "notes": "Politician; President of France",
    },
    {
        "name": "Volodymyr Zelenskyy",
        "entity_type": "person",
        "country_or_region": "Ukraine",
        "notes": "Politician; President of Ukraine",
    },
    {
        "name": "Vladimir Putin",
        "entity_type": "person",
        "country_or_region": "Russia",
        "notes": "Politician; President of Russia",
    },
    {
        "name": "Friedrich Merz",
        "entity_type": "person",
        "country_or_region": "Germany",
        "notes": "Politician; Federal Chancellor of Germany",
    },
    {
        "name": "Narendra Modi",
        "entity_type": "person",
        "country_or_region": "India",
        "notes": "Politician; Prime Minister of India",
    },
    {
        "name": "Takaichi Sanae",
        "entity_type": "person",
        "country_or_region": "Japan",
        "notes": "Politician; Prime Minister of Japan",
    },
    {
        "name": "Anthony Albanese",
        "entity_type": "person",
        "country_or_region": "Australia",
        "notes": "Politician; Prime Minister of Australia",
    },
    {
        "name": "Claudia Sheinbaum",
        "entity_type": "person",
        "country_or_region": "Mexico",
        "notes": "Politician; President of Mexico",
    },
    {
        "name": "Luiz Inácio Lula da Silva",
        "entity_type": "person",
        "country_or_region": "Brazil",
        "notes": "Politician; President of Brazil",
    },
    {
        "name": "Xi Jinping",
        "entity_type": "person",
        "country_or_region": "China",
        "notes": "Politician; President of the People's Republic of China",
    },
    {
        "name": "Ursula von der Leyen",
        "entity_type": "person",
        "country_or_region": "European Union",
        "notes": "Politician; President of the European Commission",
    },
    {
        "name": "António Costa",
        "entity_type": "person",
        "country_or_region": "European Union",
        "notes": "Politician; President of the European Council",
    },
    {
        "name": "Roberta Metsola",
        "entity_type": "person",
        "country_or_region": "European Union",
        "notes": "Politician; President of the European Parliament",
    },
    {
        "name": "Kaja Kallas",
        "entity_type": "person",
        "country_or_region": "European Union",
        "notes": "Politician; EU High Representative for Foreign Affairs and Security Policy",
    },
    {
        "name": "António Guterres",
        "entity_type": "person",
        "country_or_region": "United Nations",
        "notes": "Diplomat; Secretary-General of the United Nations",
    },
    {
        "name": "Joe Biden",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Politician; former President of the United States",
    },
    {
        "name": "Kamala Harris",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Politician; former Vice President of the United States",
    },
    {
        "name": "Barack Obama",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Politician; former President of the United States",
    },
    {
        "name": "Hillary Clinton",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Politician; former Secretary of State and presidential candidate",
    },
    {
        "name": "Bernie Sanders",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Politician; U.S. senator",
    },
    {
        "name": "Nancy Pelosi",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Politician; former Speaker of the House",
    },
    {
        "name": "Justin Trudeau",
        "entity_type": "person",
        "country_or_region": "Canada",
        "notes": "Politician; former Prime Minister of Canada",
    },
    {
        "name": "Pierre Poilievre",
        "entity_type": "person",
        "country_or_region": "Canada",
        "notes": "Politician; prominent Canadian opposition figure",
    },
    {
        "name": "Angela Merkel",
        "entity_type": "person",
        "country_or_region": "Germany",
        "notes": "Politician; former Chancellor of Germany",
    },
    {
        "name": "Boris Johnson",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Politician; former Prime Minister of the United Kingdom",
    },
    {
        "name": "Marine Le Pen",
        "entity_type": "person",
        "country_or_region": "France",
        "notes": "Politician; major French political figure",
    },
    {
        "name": "Giorgia Meloni",
        "entity_type": "person",
        "country_or_region": "Italy",
        "notes": "Politician; major Italian political figure",
    },
    # -------------------------------------------------------------------------
    # INSTITUTIONS / LEGISLATURES / COURTS / ORGANIZATIONS
    # -------------------------------------------------------------------------
    {
        "name": "The White House",
        "entity_type": "building",
        "country_or_region": "United States",
        "notes": "Official residence and workplace of the U.S. president; Washington, D.C.",
    },
    {
        "name": "West Wing",
        "entity_type": "building",
        "country_or_region": "United States",
        "notes": "Part of the White House complex often referenced in U.S. political reporting",
    },
    {
        "name": "Eisenhower Executive Office Building",
        "entity_type": "building",
        "country_or_region": "United States",
        "notes": "Executive office building next to the White House; Washington, D.C.",
    },
    {
        "name": "Camp David",
        "entity_type": "building",
        "country_or_region": "United States",
        "notes": "Presidential country residence; Maryland",
    },
    {
        "name": "U.S. Capitol",
        "entity_type": "building",
        "country_or_region": "United States",
        "notes": "Seat of the U.S. Congress; Washington, D.C.",
    },
    {
        "name": "United States Congress",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "Federal legislature of the United States",
    },
    {
        "name": "United States Senate",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "Upper chamber of the U.S. Congress",
    },
    {
        "name": "United States House of Representatives",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "Lower chamber of the U.S. Congress",
    },
    {
        "name": "Supreme Court of the United States",
        "entity_type": "institution",
        "country_or_region": "United States",
        "notes": "Highest court in the United States",
    },
    {
        "name": "Parliament of Canada",
        "entity_type": "institution",
        "country_or_region": "Canada",
        "notes": "Federal parliament of Canada; Ottawa",
    },
    {
        "name": "Parliament Hill",
        "entity_type": "building",
        "country_or_region": "Canada",
        "notes": "Political and ceremonial centre of federal politics in Ottawa",
    },
    {
        "name": "House of Commons of Canada",
        "entity_type": "institution",
        "country_or_region": "Canada",
        "notes": "Lower chamber of the Parliament of Canada",
    },
    {
        "name": "Senate of Canada",
        "entity_type": "institution",
        "country_or_region": "Canada",
        "notes": "Upper chamber of the Parliament of Canada",
    },
    {
        "name": "Office of the Prime Minister of Canada",
        "entity_type": "institution",
        "country_or_region": "Canada",
        "notes": "Prime Minister's Office; central executive political office",
    },
    {
        "name": "UK Parliament",
        "entity_type": "institution",
        "country_or_region": "United Kingdom",
        "notes": "Parliament of the United Kingdom; Westminster, London",
    },
    {
        "name": "House of Commons",
        "entity_type": "institution",
        "country_or_region": "United Kingdom",
        "notes": "Elected lower chamber of the UK Parliament",
    },
    {
        "name": "House of Lords",
        "entity_type": "institution",
        "country_or_region": "United Kingdom",
        "notes": "Upper chamber of the UK Parliament",
    },
    {
        "name": "Palace of Westminster",
        "entity_type": "building",
        "country_or_region": "United Kingdom",
        "notes": "Home of the UK Parliament; London",
    },
    {
        "name": "Westminster",
        "entity_type": "place",
        "country_or_region": "United Kingdom",
        "notes": "Political metonym for the UK Parliament and central government",
    },
    {
        "name": "10 Downing Street",
        "entity_type": "building",
        "country_or_region": "United Kingdom",
        "notes": "Official residence and office of the UK prime minister; London",
    },
    {
        "name": "Élysée Palace",
        "entity_type": "building",
        "country_or_region": "France",
        "notes": "Official residence of the President of France; Paris",
    },
    {
        "name": "National Assembly",
        "entity_type": "institution",
        "country_or_region": "France",
        "notes": "Lower house of the French Parliament",
    },
    {
        "name": "Senate of France",
        "entity_type": "institution",
        "country_or_region": "France",
        "notes": "Upper house of the French Parliament",
    },
    {
        "name": "European Commission",
        "entity_type": "institution",
        "country_or_region": "European Union",
        "notes": "Executive institution of the European Union; Brussels",
    },
    {
        "name": "European Council",
        "entity_type": "institution",
        "country_or_region": "European Union",
        "notes": "Body bringing together EU heads of state or government",
    },
    {
        "name": "Council of the European Union",
        "entity_type": "institution",
        "country_or_region": "European Union",
        "notes": "Council where ministers from EU states meet",
    },
    {
        "name": "European Parliament",
        "entity_type": "institution",
        "country_or_region": "European Union",
        "notes": "Elected parliamentary body of the EU; Brussels / Strasbourg",
    },
    {
        "name": "Berlaymont Building",
        "entity_type": "building",
        "country_or_region": "Belgium / European Union",
        "notes": "Main headquarters building of the European Commission; Brussels",
    },
    {
        "name": "United Nations",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "Global intergovernmental organization",
    },
    {
        "name": "UN Security Council",
        "entity_type": "institution",
        "country_or_region": "United Nations",
        "notes": "Principal UN body for international peace and security",
    },
    {
        "name": "UN General Assembly",
        "entity_type": "institution",
        "country_or_region": "United Nations",
        "notes": "Main deliberative body of the United Nations",
    },
    {
        "name": "UN Headquarters",
        "entity_type": "building",
        "country_or_region": "United States / United Nations",
        "notes": "Main headquarters complex of the UN; New York City",
    },
    {
        "name": "NATO",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "North Atlantic Treaty Organization",
    },
    {
        "name": "International Criminal Court",
        "entity_type": "institution",
        "country_or_region": "International",
        "notes": "International court established by the Rome Statute; The Hague",
    },
    {
        "name": "International Court of Justice",
        "entity_type": "institution",
        "country_or_region": "United Nations",
        "notes": "Principal judicial organ of the United Nations; The Hague",
    },
    {
        "name": "Peace Palace",
        "entity_type": "building",
        "country_or_region": "Netherlands",
        "notes": "Seat of the International Court of Justice; The Hague",
    },
    {
        "name": "German Bundestag",
        "entity_type": "institution",
        "country_or_region": "Germany",
        "notes": "National parliament of Germany",
    },
    {
        "name": "Reichstag Building",
        "entity_type": "building",
        "country_or_region": "Germany",
        "notes": "Seat of the German Bundestag; Berlin",
    },
    {
        "name": "Bundesrat",
        "entity_type": "institution",
        "country_or_region": "Germany",
        "notes": "Federal council representing the German states",
    },
    {
        "name": "Federal Chancellery",
        "entity_type": "building",
        "country_or_region": "Germany",
        "notes": "Office and executive seat of the German chancellor; Berlin",
    },
    {
        "name": "Verkhovna Rada",
        "entity_type": "institution",
        "country_or_region": "Ukraine",
        "notes": "Parliament of Ukraine; Kyiv",
    },
    {
        "name": "Office of the President of Ukraine",
        "entity_type": "institution",
        "country_or_region": "Ukraine",
        "notes": "Presidential administration of Ukraine; Kyiv",
    },
    {
        "name": "Kremlin",
        "entity_type": "building",
        "country_or_region": "Russia",
        "notes": "Political metonym and seat of Russian presidential power; Moscow",
    },
    {
        "name": "Grand Kremlin Palace",
        "entity_type": "building",
        "country_or_region": "Russia",
        "notes": "Major state building used for ceremonies and meetings; Moscow",
    },
    {
        "name": "State Duma",
        "entity_type": "institution",
        "country_or_region": "Russia",
        "notes": "Lower house of the Federal Assembly of Russia",
    },
    {
        "name": "Federation Council",
        "entity_type": "institution",
        "country_or_region": "Russia",
        "notes": "Upper house of the Federal Assembly of Russia",
    },
    {
        "name": "Great Hall of the People",
        "entity_type": "building",
        "country_or_region": "China",
        "notes": "Key state building in Beijing used for major political sessions",
    },
    {
        "name": "National People's Congress",
        "entity_type": "institution",
        "country_or_region": "China",
        "notes": "National legislature of the People's Republic of China",
    },
    {
        "name": "State Council of the People's Republic of China",
        "entity_type": "institution",
        "country_or_region": "China",
        "notes": "Chief administrative authority of the PRC",
    },
    {
        "name": "Zhongnanhai",
        "entity_type": "place",
        "country_or_region": "China",
        "notes": "Political compound associated with Chinese central leadership; Beijing",
    },
    {
        "name": "Prime Minister's Office of Japan",
        "entity_type": "institution",
        "country_or_region": "Japan",
        "notes": "Prime Minister's Office; often called the Kantei",
    },
    {
        "name": "Kantei",
        "entity_type": "building",
        "country_or_region": "Japan",
        "notes": "Common shorthand for the Prime Minister's Office of Japan; Tokyo",
    },
    {
        "name": "National Diet of Japan",
        "entity_type": "institution",
        "country_or_region": "Japan",
        "notes": "Parliament of Japan",
    },
    {
        "name": "National Diet Building",
        "entity_type": "building",
        "country_or_region": "Japan",
        "notes": "Seat of Japan's legislature; Tokyo",
    },
    {
        "name": "Parliament House, Canberra",
        "entity_type": "building",
        "country_or_region": "Australia",
        "notes": "Seat of the Australian Parliament",
    },
    {
        "name": "Parliament of Australia",
        "entity_type": "institution",
        "country_or_region": "Australia",
        "notes": "Federal parliament of Australia",
    },
    {
        "name": "Planalto Palace",
        "entity_type": "building",
        "country_or_region": "Brazil",
        "notes": "Official workplace of the President of Brazil; Brasília",
    },
    {
        "name": "National Congress of Brazil",
        "entity_type": "institution",
        "country_or_region": "Brazil",
        "notes": "Federal legislature of Brazil; Brasília",
    },
    {
        "name": "Palacio Nacional",
        "entity_type": "building",
        "country_or_region": "Mexico",
        "notes": "Major seat of federal executive power in Mexico City",
    },
    {
        "name": "Congress of the Union",
        "entity_type": "institution",
        "country_or_region": "Mexico",
        "notes": "Federal legislature of Mexico",
    },
    {
        "name": "Rashtrapati Bhavan",
        "entity_type": "building",
        "country_or_region": "India",
        "notes": "Official residence of the President of India; New Delhi",
    },
    {
        "name": "Parliament of India",
        "entity_type": "institution",
        "country_or_region": "India",
        "notes": "National parliament of India",
    },
    {
        "name": "Lok Sabha",
        "entity_type": "institution",
        "country_or_region": "India",
        "notes": "Lower house of the Parliament of India",
    },
    {
        "name": "Rajya Sabha",
        "entity_type": "institution",
        "country_or_region": "India",
        "notes": "Upper house of the Parliament of India",
    },
    {
        "name": "South Block",
        "entity_type": "building",
        "country_or_region": "India",
        "notes": "Key government secretariat building in New Delhi",
    },
    {
        "name": "ASEAN",
        "entity_type": "institution",
        "country_or_region": "Southeast Asia",
        "notes": "Association of Southeast Asian Nations",
    },
    {
        "name": "Organization of American States",
        "entity_type": "institution",
        "country_or_region": "Americas",
        "notes": "Regional intergovernmental organization",
    },
    {
        "name": "African Union",
        "entity_type": "institution",
        "country_or_region": "Africa",
        "notes": "Continental intergovernmental organization",
    },
    # -------------------------------------------------------------------------
    # TREATIES / AGREEMENTS / CHARTERS
    # -------------------------------------------------------------------------
    {
        "name": "United Nations Charter",
        "entity_type": "treaty",
        "country_or_region": "International",
        "notes": "Founding charter of the United Nations",
    },
    {
        "name": "North Atlantic Treaty",
        "entity_type": "treaty",
        "country_or_region": "International",
        "notes": "Founding treaty of NATO",
    },
    {
        "name": "Maastricht Treaty",
        "entity_type": "treaty",
        "country_or_region": "European Union",
        "notes": "Treaty on European Union; foundational treaty for the EU",
    },
    {
        "name": "Treaty of Lisbon",
        "entity_type": "treaty",
        "country_or_region": "European Union",
        "notes": "EU reform treaty that entered into force in 2009",
    },
    {
        "name": "Rome Statute",
        "entity_type": "treaty",
        "country_or_region": "International",
        "notes": "Founding treaty of the International Criminal Court",
    },
    {
        "name": "Paris Agreement",
        "entity_type": "treaty",
        "country_or_region": "International",
        "notes": "Climate treaty under the UNFCCC",
    },
    {
        "name": "Geneva Conventions",
        "entity_type": "treaty",
        "country_or_region": "International",
        "notes": "Core treaties of international humanitarian law",
    },
    {
        "name": "Kyoto Protocol",
        "entity_type": "treaty",
        "country_or_region": "International",
        "notes": "Climate treaty linked to the UNFCCC",
    },
    {
        "name": "Schengen Agreement",
        "entity_type": "treaty",
        "country_or_region": "Europe",
        "notes": "Agreement associated with border-free travel in much of Europe",
    },
    {
        "name": "Good Friday Agreement",
        "entity_type": "treaty",
        "country_or_region": "United Kingdom / Ireland",
        "notes": "Peace agreement central to Northern Ireland politics",
    },
    {
        "name": "Camp David Accords",
        "entity_type": "treaty",
        "country_or_region": "International",
        "notes": "Major Middle East peace framework negotiated in the United States",
    },
    {
        "name": "Dayton Agreement",
        "entity_type": "treaty",
        "country_or_region": "Bosnia and Herzegovina / International",
        "notes": "Peace agreement associated with the Bosnian War",
    },
    {
        "name": "Treaty on European Union",
        "entity_type": "treaty",
        "country_or_region": "European Union",
        "notes": "Core EU treaty; often discussed alongside Maastricht and Lisbon",
    },
    {
        "name": "ASEAN Charter",
        "entity_type": "treaty",
        "country_or_region": "Southeast Asia",
        "notes": "Charter giving ASEAN its legal and institutional framework",
    },
    {
        "name": "Charter of the Organization of American States",
        "entity_type": "treaty",
        "country_or_region": "Americas",
        "notes": "Founding charter of the OAS",
    },
    {
        "name": "New START",
        "entity_type": "treaty",
        "country_or_region": "United States / Russia",
        "notes": "Strategic arms reduction treaty often referenced in security reporting",
    },
    {
        "name": "Treaty on the Non-Proliferation of Nuclear Weapons",
        "entity_type": "treaty",
        "country_or_region": "International",
        "notes": "Often shortened to NPT",
    },
    {
        "name": "Abraham Accords",
        "entity_type": "treaty",
        "country_or_region": "Middle East / International",
        "notes": "Normalization agreements often referenced in Middle East diplomacy",
    },
    # -------------------------------------------------------------------------
    # CAPITALS / POLITICAL CITIES / DIPLOMATIC HUBS
    # -------------------------------------------------------------------------
    {
        "name": "Washington, D.C.",
        "entity_type": "city",
        "country_or_region": "United States",
        "notes": "Capital city of the United States",
    },
    {
        "name": "Ottawa",
        "entity_type": "city",
        "country_or_region": "Canada",
        "notes": "Capital city of Canada",
    },
    {
        "name": "London",
        "entity_type": "city",
        "country_or_region": "United Kingdom",
        "notes": "Capital city of the United Kingdom",
    },
    {
        "name": "Paris",
        "entity_type": "city",
        "country_or_region": "France",
        "notes": "Capital city of France",
    },
    {
        "name": "Berlin",
        "entity_type": "city",
        "country_or_region": "Germany",
        "notes": "Capital city of Germany",
    },
    {
        "name": "Brussels",
        "entity_type": "city",
        "country_or_region": "Belgium / European Union",
        "notes": "Major political centre of the European Union",
    },
    {
        "name": "Kyiv",
        "entity_type": "city",
        "country_or_region": "Ukraine",
        "notes": "Capital city of Ukraine",
    },
    {
        "name": "Moscow",
        "entity_type": "city",
        "country_or_region": "Russia",
        "notes": "Capital city of Russia",
    },
    {
        "name": "Beijing",
        "entity_type": "city",
        "country_or_region": "China",
        "notes": "Capital city of China",
    },
    {
        "name": "Tokyo",
        "entity_type": "city",
        "country_or_region": "Japan",
        "notes": "Capital city of Japan",
    },
    {
        "name": "New Delhi",
        "entity_type": "city",
        "country_or_region": "India",
        "notes": "Capital city of India",
    },
    {
        "name": "Canberra",
        "entity_type": "city",
        "country_or_region": "Australia",
        "notes": "Capital city of Australia",
    },
    {
        "name": "Brasília",
        "entity_type": "city",
        "country_or_region": "Brazil",
        "notes": "Capital city of Brazil",
    },
    {
        "name": "Mexico City",
        "entity_type": "city",
        "country_or_region": "Mexico",
        "notes": "Capital city of Mexico",
    },
    {
        "name": "New York City",
        "entity_type": "city",
        "country_or_region": "United States / United Nations",
        "notes": "Home of UN Headquarters",
    },
    {
        "name": "Geneva",
        "entity_type": "city",
        "country_or_region": "Switzerland",
        "notes": "Major diplomatic city and UN hub",
    },
    {
        "name": "The Hague",
        "entity_type": "city",
        "country_or_region": "Netherlands",
        "notes": "Major international law and court city",
    },
    {
        "name": "Strasbourg",
        "entity_type": "city",
        "country_or_region": "France / European Union",
        "notes": "Political city associated with the European Parliament",
    },
    {
        "name": "Vienna",
        "entity_type": "city",
        "country_or_region": "Austria",
        "notes": "Major diplomatic city and host of many international organizations",
    },
    {
        "name": "Addis Ababa",
        "entity_type": "city",
        "country_or_region": "Ethiopia / African Union",
        "notes": "Capital of Ethiopia and seat of the African Union",
    },
]
