from synthnews.prompts import Entity


ENTITIES: list[Entity] = [
    {
        "name": "Albert Einstein",
        "entity_type": "person",
        "country_or_region": "Germany / Switzerland / United States",
        "notes": "Theoretical physicist",
    },
    {
        "name": "Marie Curie",
        "entity_type": "person",
        "country_or_region": "Poland / France",
        "notes": "Physicist and chemist; radioactivity",
    },
    {
        "name": "Isaac Newton",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Physicist and mathematician",
    },
    {
        "name": "Galileo Galilei",
        "entity_type": "person",
        "country_or_region": "Italy",
        "notes": "Astronomer and physicist",
    },
    {
        "name": "Charles Darwin",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Naturalist; evolution",
    },
    {
        "name": "Nikola Tesla",
        "entity_type": "person",
        "country_or_region": "Serbia / United States",
        "notes": "Inventor and electrical engineer",
    },
    {
        "name": "Ada Lovelace",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Early computing pioneer",
    },
    {
        "name": "Alan Turing",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Computer scientist and mathematician",
    },
    {
        "name": "Grace Hopper",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Computer scientist; compilers",
    },
    {
        "name": "Katherine Johnson",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Mathematician; NASA computations",
    },
    {
        "name": "Carl Sagan",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Astronomer and science communicator",
    },
    {
        "name": "Stephen Hawking",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Theoretical physicist",
    },
    {
        "name": "Richard Feynman",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Theoretical physicist",
    },
    {
        "name": "Jane Goodall",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Primatologist and conservationist",
    },
    {
        "name": "Rachel Carson",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Marine biologist and author",
    },
    {
        "name": "Neil deGrasse Tyson",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Astrophysicist and science communicator",
    },
    {
        "name": "Bill Nye",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Science communicator",
    },
    {
        "name": "Brian Cox",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Physicist and science presenter",
    },
    {
        "name": "Michio Kaku",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Theoretical physicist",
    },
    {
        "name": "Brian Greene",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Theoretical physicist and author",
    },
    {
        "name": "Jennifer Doudna",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Biochemist; CRISPR",
    },
    {
        "name": "Emmanuelle Charpentier",
        "entity_type": "person",
        "country_or_region": "France / Germany",
        "notes": "Microbiologist; CRISPR",
    },
    {
        "name": "Frances Arnold",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Chemical engineer; directed evolution",
    },
    {
        "name": "Svante Pääbo",
        "entity_type": "person",
        "country_or_region": "Sweden / Germany",
        "notes": "Geneticist; ancient DNA",
    },
    {
        "name": "Katalin Karikó",
        "entity_type": "person",
        "country_or_region": "Hungary / United States",
        "notes": "Biochemist; mRNA research",
    },
    {
        "name": "Drew Weissman",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Physician-scientist; mRNA research",
    },
    {
        "name": "Donna Strickland",
        "entity_type": "person",
        "country_or_region": "Canada",
        "notes": "Physicist; lasers",
    },
    {
        "name": "Kip Thorne",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Theoretical physicist; gravitation",
    },
    {
        "name": "Roger Penrose",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Mathematician and physicist",
    },
    {
        "name": "Andrea Ghez",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Astronomer; Milky Way black hole",
    },
    {
        "name": "May-Britt Moser",
        "entity_type": "person",
        "country_or_region": "Norway",
        "notes": "Neuroscientist; grid cells",
    },
    {
        "name": "Edvard Moser",
        "entity_type": "person",
        "country_or_region": "Norway",
        "notes": "Neuroscientist; grid cells",
    },
    {
        "name": "Tu Youyou",
        "entity_type": "person",
        "country_or_region": "China",
        "notes": "Pharmaceutical chemist; artemisinin",
    },
    {
        "name": "George Church",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Geneticist",
    },
    {
        "name": "Feng Zhang",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Neuroscientist; CRISPR",
    },
    {
        "name": "Jane Rigby",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Astronomer; JWST project scientist",
    },
    {
        "name": "Katie Mack",
        "entity_type": "person",
        "country_or_region": "Canada / United States",
        "notes": "Theoretical cosmologist and author",
    },
    {
        "name": "Hank Green",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Science communicator (online education)",
    },
    {
        "name": "Sabine Hossenfelder",
        "entity_type": "person",
        "country_or_region": "Germany",
        "notes": "Theoretical physicist and science communicator",
    },
    {
        "name": "Simon Singh",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Science writer",
    },
    {
        "name": "Tim Berners-Lee",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "Inventor of the World Wide Web",
    },
    {
        "name": "Linus Torvalds",
        "entity_type": "person",
        "country_or_region": "Finland / United States",
        "notes": "Creator of the Linux kernel",
    },
    {
        "name": "Guido van Rossum",
        "entity_type": "person",
        "country_or_region": "Netherlands / United States",
        "notes": "Creator of Python",
    },
    {
        "name": "James Gosling",
        "entity_type": "person",
        "country_or_region": "Canada / United States",
        "notes": "Creator of Java",
    },
    {
        "name": "Bjarne Stroustrup",
        "entity_type": "person",
        "country_or_region": "Denmark / United States",
        "notes": "Creator of C++",
    },
    {
        "name": "Brendan Eich",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Created JavaScript",
    },
    {
        "name": "Yukihiro Matsumoto",
        "entity_type": "person",
        "country_or_region": "Japan",
        "notes": "Creator of Ruby",
    },
    {
        "name": "Dennis Ritchie",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Co-created C and Unix",
    },
    {
        "name": "Ken Thompson",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Co-created Unix",
    },
    {
        "name": "Margaret Hamilton",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Software engineer; Apollo program",
    },
    {
        "name": "Geoffrey Hinton",
        "entity_type": "person",
        "country_or_region": "Canada / United Kingdom",
        "notes": "Computer scientist; deep learning",
    },
    {
        "name": "Yann LeCun",
        "entity_type": "person",
        "country_or_region": "France / United States",
        "notes": "Computer scientist; deep learning",
    },
    {
        "name": "Yoshua Bengio",
        "entity_type": "person",
        "country_or_region": "Canada",
        "notes": "Computer scientist; deep learning",
    },
    {
        "name": "Fei-Fei Li",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "Computer scientist; computer vision",
    },
    {
        "name": "Demis Hassabis",
        "entity_type": "person",
        "country_or_region": "United Kingdom",
        "notes": "AI researcher; CEO of Google DeepMind",
    },
    {
        "name": "John Jumper",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "AI researcher; protein structure prediction",
    },
    {
        "name": "NASA",
        "entity_type": "space_agency",
        "country_or_region": "United States",
        "notes": "National Aeronautics and Space Administration",
    },
    {
        "name": "European Space Agency (ESA)",
        "entity_type": "space_agency",
        "country_or_region": "Europe",
        "notes": "Intergovernmental space agency",
    },
    {
        "name": "JAXA",
        "entity_type": "space_agency",
        "country_or_region": "Japan",
        "notes": "Japan Aerospace Exploration Agency",
    },
    {
        "name": "CSA (Canadian Space Agency)",
        "entity_type": "space_agency",
        "country_or_region": "Canada",
        "notes": "Canada's national space agency",
    },
    {
        "name": "CNSA",
        "entity_type": "space_agency",
        "country_or_region": "China",
        "notes": "China National Space Administration",
    },
    {
        "name": "ISRO",
        "entity_type": "space_agency",
        "country_or_region": "India",
        "notes": "Indian Space Research Organisation",
    },
    {
        "name": "CERN",
        "entity_type": "laboratory",
        "country_or_region": "Switzerland / International",
        "notes": "European particle physics laboratory",
    },
    {
        "name": "Fermilab",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "Fermi National Accelerator Laboratory",
    },
    {
        "name": "SLAC National Accelerator Laboratory",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "Particle accelerator laboratory",
    },
    {
        "name": "Lawrence Berkeley National Laboratory",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "U.S. DOE national lab",
    },
    {
        "name": "Argonne National Laboratory",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "U.S. DOE national lab",
    },
    {
        "name": "Los Alamos National Laboratory",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "U.S. DOE national lab",
    },
    {
        "name": "Oak Ridge National Laboratory (ORNL)",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "U.S. DOE national lab",
    },
    {
        "name": "Pacific Northwest National Laboratory (PNNL)",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "U.S. DOE national lab",
    },
    {
        "name": "Jet Propulsion Laboratory (JPL)",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "NASA center managed by Caltech",
    },
    {
        "name": "MIT Media Lab",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "Research lab at MIT",
    },
    {
        "name": "Bell Labs",
        "entity_type": "laboratory",
        "country_or_region": "United States",
        "notes": "Historic industrial research lab",
    },
    {
        "name": "Max Planck Society",
        "entity_type": "research_organization",
        "country_or_region": "Germany",
        "notes": "Network of research institutes",
    },
    {
        "name": "CNRS",
        "entity_type": "research_organization",
        "country_or_region": "France",
        "notes": "National Centre for Scientific Research",
    },
    {
        "name": "National Institutes of Health (NIH)",
        "entity_type": "government_agency",
        "country_or_region": "United States",
        "notes": "Biomedical research agency",
    },
    {
        "name": "Centers for Disease Control and Prevention (CDC)",
        "entity_type": "government_agency",
        "country_or_region": "United States",
        "notes": "Public health agency",
    },
    {
        "name": "National Science Foundation (NSF)",
        "entity_type": "government_agency",
        "country_or_region": "United States",
        "notes": "Funds research and education",
    },
    {
        "name": "NOAA",
        "entity_type": "government_agency",
        "country_or_region": "United States",
        "notes": "National Oceanic and Atmospheric Administration",
    },
    {
        "name": "NIST",
        "entity_type": "standards_body",
        "country_or_region": "United States",
        "notes": "National Institute of Standards and Technology",
    },
    {
        "name": "IEEE",
        "entity_type": "standards_body",
        "country_or_region": "International",
        "notes": "Professional association and standards",
    },
    {
        "name": "IETF",
        "entity_type": "standards_body",
        "country_or_region": "International",
        "notes": "Internet Engineering Task Force",
    },
    {
        "name": "W3C",
        "entity_type": "standards_body",
        "country_or_region": "International",
        "notes": "World Wide Web Consortium",
    },
    {
        "name": "ISO",
        "entity_type": "standards_body",
        "country_or_region": "International",
        "notes": "International Organization for Standardization",
    },
    {
        "name": "Linux Foundation",
        "entity_type": "foundation",
        "country_or_region": "International",
        "notes": "Supports major open source projects",
    },
    {
        "name": "Apache Software Foundation",
        "entity_type": "foundation",
        "country_or_region": "International",
        "notes": "Open source foundation",
    },
    {
        "name": "CNCF (Cloud Native Computing Foundation)",
        "entity_type": "foundation",
        "country_or_region": "International",
        "notes": "Cloud native open source foundation",
    },
    {
        "name": "Hubble Space Telescope",
        "entity_type": "telescope",
        "country_or_region": "International / NASA-ESA",
        "notes": "Space telescope",
    },
    {
        "name": "James Webb Space Telescope (JWST)",
        "entity_type": "telescope",
        "country_or_region": "International / NASA-ESA-CSA",
        "notes": "Space telescope",
    },
    {
        "name": "Chandra X-ray Observatory",
        "entity_type": "telescope",
        "country_or_region": "United States",
        "notes": "Space telescope",
    },
    {
        "name": "Spitzer Space Telescope",
        "entity_type": "telescope",
        "country_or_region": "United States",
        "notes": "Infrared space telescope (retired)",
    },
    {
        "name": "Kepler Space Telescope",
        "entity_type": "telescope",
        "country_or_region": "United States",
        "notes": "Exoplanet mission (retired)",
    },
    {
        "name": "TESS (Transiting Exoplanet Survey Satellite)",
        "entity_type": "telescope",
        "country_or_region": "United States",
        "notes": "Exoplanet survey mission",
    },
    {
        "name": "Very Large Telescope (VLT)",
        "entity_type": "telescope",
        "country_or_region": "Chile / Europe",
        "notes": "ESO ground-based telescope array",
    },
    {
        "name": "Atacama Large Millimeter/submillimeter Array (ALMA)",
        "entity_type": "telescope",
        "country_or_region": "Chile / International",
        "notes": "Radio telescope array",
    },
    {
        "name": "Keck Observatory",
        "entity_type": "telescope",
        "country_or_region": "United States (Hawaii)",
        "notes": "Twin optical/IR telescopes",
    },
    {
        "name": "Subaru Telescope",
        "entity_type": "telescope",
        "country_or_region": "Japan (Hawaii)",
        "notes": "Optical/IR telescope",
    },
    {
        "name": "Thirty Meter Telescope (TMT)",
        "entity_type": "telescope",
        "country_or_region": "United States (Hawaii)",
        "notes": "Next-gen ground telescope project",
    },
    {
        "name": "European Extremely Large Telescope (ELT)",
        "entity_type": "telescope",
        "country_or_region": "Chile / Europe",
        "notes": "Next-gen ground telescope project",
    },
    {
        "name": "Vera C. Rubin Observatory",
        "entity_type": "telescope",
        "country_or_region": "Chile / United States",
        "notes": "Survey telescope (LSST)",
    },
    {
        "name": "Square Kilometre Array (SKA)",
        "entity_type": "telescope",
        "country_or_region": "South Africa / Australia / International",
        "notes": "Radio telescope project",
    },
    {
        "name": "Event Horizon Telescope (EHT)",
        "entity_type": "telescope",
        "country_or_region": "International",
        "notes": "Global VLBI network",
    },
    {
        "name": "LIGO",
        "entity_type": "detector",
        "country_or_region": "United States",
        "notes": "Laser Interferometer Gravitational-Wave Observatory",
    },
    {
        "name": "Virgo detector",
        "entity_type": "detector",
        "country_or_region": "Italy / France",
        "notes": "Gravitational-wave detector",
    },
    {
        "name": "KAGRA",
        "entity_type": "detector",
        "country_or_region": "Japan",
        "notes": "Gravitational-wave detector",
    },
    {
        "name": "IceCube Neutrino Observatory",
        "entity_type": "detector",
        "country_or_region": "Antarctica / International",
        "notes": "Neutrino detector",
    },
    {
        "name": "Large Hadron Collider (LHC)",
        "entity_type": "experiment",
        "country_or_region": "Switzerland / France",
        "notes": "Particle accelerator at CERN",
    },
    {
        "name": "ATLAS experiment",
        "entity_type": "experiment",
        "country_or_region": "Switzerland / France",
        "notes": "LHC detector experiment",
    },
    {
        "name": "CMS experiment",
        "entity_type": "experiment",
        "country_or_region": "Switzerland / France",
        "notes": "LHC detector experiment",
    },
    {
        "name": "LHCb experiment",
        "entity_type": "experiment",
        "country_or_region": "Switzerland / France",
        "notes": "LHC detector experiment",
    },
    {
        "name": "ALICE experiment",
        "entity_type": "experiment",
        "country_or_region": "Switzerland / France",
        "notes": "LHC detector experiment",
    },
    {
        "name": "DUNE (Deep Underground Neutrino Experiment)",
        "entity_type": "experiment",
        "country_or_region": "United States",
        "notes": "Neutrino experiment",
    },
    {
        "name": "Belle II",
        "entity_type": "experiment",
        "country_or_region": "Japan",
        "notes": "Particle physics experiment at KEK",
    },
    {
        "name": "ITER",
        "entity_type": "experiment",
        "country_or_region": "France / International",
        "notes": "Fusion energy project",
    },
    {
        "name": "National Ignition Facility (NIF)",
        "entity_type": "experiment",
        "country_or_region": "United States",
        "notes": "Inertial confinement fusion facility",
    },
    {
        "name": "Human Genome Project",
        "entity_type": "program",
        "country_or_region": "International",
        "notes": "Genome sequencing program",
    },
    {
        "name": "CRISPR-Cas9",
        "entity_type": "technology",
        "country_or_region": "International",
        "notes": "Genome editing technology",
    },
    {
        "name": "mRNA vaccines",
        "entity_type": "technology",
        "country_or_region": "International",
        "notes": "Vaccine platform technology",
    },
    {
        "name": "International Space Station (ISS)",
        "entity_type": "space_program",
        "country_or_region": "International",
        "notes": "Crewed space station",
    },
    {
        "name": "Artemis program",
        "entity_type": "space_program",
        "country_or_region": "United States / International",
        "notes": "Human lunar exploration program",
    },
    {
        "name": "Mars Perseverance rover",
        "entity_type": "space_mission",
        "country_or_region": "United States",
        "notes": "Mars rover mission",
    },
    {
        "name": "Mars Curiosity rover",
        "entity_type": "space_mission",
        "country_or_region": "United States",
        "notes": "Mars rover mission",
    },
    {
        "name": "Voyager 1",
        "entity_type": "space_mission",
        "country_or_region": "United States",
        "notes": "Deep-space probe",
    },
    {
        "name": "Voyager 2",
        "entity_type": "space_mission",
        "country_or_region": "United States",
        "notes": "Deep-space probe",
    },
    {
        "name": "Cassini–Huygens",
        "entity_type": "space_mission",
        "country_or_region": "International / NASA-ESA-ASI",
        "notes": "Saturn mission",
    },
    {
        "name": "OSIRIS-REx",
        "entity_type": "space_mission",
        "country_or_region": "United States",
        "notes": "Asteroid sample-return mission",
    },
    {
        "name": "Parker Solar Probe",
        "entity_type": "space_mission",
        "country_or_region": "United States",
        "notes": "Solar mission",
    },
    {
        "name": "Gaia",
        "entity_type": "space_mission",
        "country_or_region": "Europe",
        "notes": "Astrometry mission",
    },
    {
        "name": "Apple",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "CEO of Apple",
    },
    {
        "name": "Tim Cook",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — Apple",
    },
    {
        "name": "Microsoft",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Chairman and CEO of Microsoft",
    },
    {
        "name": "Satya Nadella",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — Microsoft",
    },
    {
        "name": "Google / Alphabet",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "CEO of Google and Alphabet",
    },
    {
        "name": "Sundar Pichai",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — Google / Alphabet",
    },
    {
        "name": "Meta",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Founder, Chairman and CEO of Meta",
    },
    {
        "name": "Mark Zuckerberg",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — Meta",
    },
    {
        "name": "Amazon",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "President and CEO of Amazon",
    },
    {
        "name": "Andy Jassy",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — Amazon",
    },
    {
        "name": "NVIDIA",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Founder and CEO of NVIDIA",
    },
    {
        "name": "Jensen Huang",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — NVIDIA",
    },
    {
        "name": "Tesla",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "CEO of Tesla",
    },
    {
        "name": "Elon Musk",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — Tesla",
    },
    {
        "name": "AMD",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Chair and CEO of AMD",
    },
    {
        "name": "Lisa Su",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — AMD",
    },
    {
        "name": "Intel",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "CEO of Intel (appointed March 2025)",
    },
    {
        "name": "Lip-Bu Tan",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — Intel",
    },
    {
        "name": "IBM",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Chairman and CEO of IBM",
    },
    {
        "name": "Arvind Krishna",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — IBM",
    },
    {
        "name": "Samsung Electronics",
        "entity_type": "tech_company",
        "country_or_region": "South Korea",
        "notes": "Co-CEO (Device eXperience Division)",
    },
    {
        "name": "TM Roh",
        "entity_type": "person",
        "country_or_region": "South Korea",
        "notes": "CEO — Samsung Electronics",
    },
    {
        "name": "Samsung Electronics",
        "entity_type": "tech_company",
        "country_or_region": "South Korea",
        "notes": "Co-CEO (Device Solutions Division)",
    },
    {
        "name": "Young Hyun Jun",
        "entity_type": "person",
        "country_or_region": "South Korea",
        "notes": "CEO — Samsung Electronics",
    },
    {
        "name": "TSMC",
        "entity_type": "tech_company",
        "country_or_region": "Taiwan",
        "notes": "President, CEO, and Chairman of TSMC",
    },
    {
        "name": "C. C. Wei",
        "entity_type": "person",
        "country_or_region": "Taiwan",
        "notes": "CEO — TSMC",
    },
    {
        "name": "SpaceX",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "President and COO of SpaceX",
    },
    {
        "name": "Gwynne Shotwell",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "President & COO — SpaceX",
    },
    {
        "name": "OpenAI",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "CEO of OpenAI (per reporting; leadership has changed historically)",
    },
    {
        "name": "Sam Altman",
        "entity_type": "person",
        "country_or_region": "United States",
        "notes": "CEO — OpenAI",
    },
    {
        "name": "Sony Interactive Entertainment",
        "entity_type": "tech_company",
        "country_or_region": "International",
        "notes": "President and CEO of SIE (announced 2025)",
    },
    {
        "name": "Hideaki Nishino",
        "entity_type": "person",
        "country_or_region": "International",
        "notes": "CEO — Sony Interactive Entertainment",
    },
    {
        "name": "ASML",
        "entity_type": "tech_company",
        "country_or_region": "Netherlands",
        "notes": "Semiconductor lithography systems",
    },
    {
        "name": "Qualcomm",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Semiconductors; mobile chipsets",
    },
    {
        "name": "Broadcom",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Semiconductors and infrastructure software",
    },
    {
        "name": "Cisco",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Networking",
    },
    {
        "name": "Oracle",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Database and cloud",
    },
    {
        "name": "Salesforce",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Enterprise SaaS",
    },
    {
        "name": "Adobe",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Creative software",
    },
    {
        "name": "ByteDance",
        "entity_type": "tech_company",
        "country_or_region": "China",
        "notes": "Internet company (TikTok)",
    },
    {
        "name": "Tencent",
        "entity_type": "tech_company",
        "country_or_region": "China",
        "notes": "Internet and games",
    },
    {
        "name": "Alibaba Group",
        "entity_type": "tech_company",
        "country_or_region": "China",
        "notes": "E-commerce and cloud",
    },
    {
        "name": "Huawei",
        "entity_type": "tech_company",
        "country_or_region": "China",
        "notes": "Telecom and devices",
    },
    {
        "name": "Ericsson",
        "entity_type": "tech_company",
        "country_or_region": "Sweden",
        "notes": "Telecommunications",
    },
    {
        "name": "Nokia",
        "entity_type": "tech_company",
        "country_or_region": "Finland",
        "notes": "Telecommunications",
    },
    {
        "name": "ARM",
        "entity_type": "tech_company",
        "country_or_region": "United Kingdom",
        "notes": "CPU architecture and IP",
    },
    {
        "name": "TSMC Arizona",
        "entity_type": "tech_company",
        "country_or_region": "United States",
        "notes": "Semiconductor manufacturing facility (subsidiary site)",
    },
    {
        "name": "iPhone",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Smartphone product line (Apple)",
    },
    {
        "name": "iPad",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Tablet product line (Apple)",
    },
    {
        "name": "MacBook Air",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Laptop product line (Apple)",
    },
    {
        "name": "MacBook Pro",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Laptop product line (Apple)",
    },
    {
        "name": "Apple Watch",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Wearable product line (Apple)",
    },
    {
        "name": "Apple Vision Pro",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Spatial computing headset (Apple)",
    },
    {
        "name": "Google Pixel",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Smartphone product line (Google)",
    },
    {
        "name": "Samsung Galaxy S",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Smartphone product line (Samsung)",
    },
    {
        "name": "Samsung Galaxy Z Fold",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Foldable smartphone product line (Samsung)",
    },
    {
        "name": "Samsung Galaxy Tab",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Tablet product line (Samsung)",
    },
    {
        "name": "Microsoft Surface Pro",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "2‑in‑1 tablet PC product line",
    },
    {
        "name": "PlayStation 5",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Gaming console (Sony)",
    },
    {
        "name": "Xbox Series X|S",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Gaming console (Microsoft)",
    },
    {
        "name": "Nintendo Switch",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Gaming console (Nintendo)",
    },
    {
        "name": "Steam Deck",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Handheld gaming PC (Valve)",
    },
    {
        "name": "Meta Quest",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "VR headset product line (Meta)",
    },
    {
        "name": "Kindle",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "E-reader product line (Amazon)",
    },
    {
        "name": "Raspberry Pi",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Single-board computer line",
    },
    {
        "name": "Arduino",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Microcontroller prototyping platform",
    },
    {
        "name": "DJI Mavic",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Consumer drone product line (DJI)",
    },
    {
        "name": "Tesla Model 3",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Electric car model (Tesla)",
    },
    {
        "name": "Tesla Model Y",
        "entity_type": "consumer_product",
        "country_or_region": "International",
        "notes": "Electric car model (Tesla)",
    },
    {
        "name": "Linux kernel",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Operating system kernel",
    },
    {
        "name": "GNU Project",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Free software project",
    },
    {
        "name": "Kubernetes",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Container orchestration",
    },
    {
        "name": "Docker",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Container platform",
    },
    {
        "name": "containerd",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Container runtime",
    },
    {
        "name": "OpenTelemetry",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Observability framework",
    },
    {
        "name": "Prometheus",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Monitoring system",
    },
    {
        "name": "Grafana",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Observability visualization",
    },
    {
        "name": "Apache Kafka",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Distributed streaming platform",
    },
    {
        "name": "RabbitMQ",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Message broker",
    },
    {
        "name": "Redis",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "In-memory data store",
    },
    {
        "name": "PostgreSQL",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Relational database",
    },
    {
        "name": "MySQL",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Relational database",
    },
    {
        "name": "SQLite",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Embedded database",
    },
    {
        "name": "Apache Spark",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Distributed data processing",
    },
    {
        "name": "Hadoop",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Distributed storage/processing",
    },
    {
        "name": "TensorFlow",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Machine learning framework",
    },
    {
        "name": "PyTorch",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Machine learning framework",
    },
    {
        "name": "scikit-learn",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Machine learning library",
    },
    {
        "name": "NumPy",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Numerical computing",
    },
    {
        "name": "pandas",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Data analysis library",
    },
    {
        "name": "Jupyter",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Interactive computing",
    },
    {
        "name": "LLVM",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Compiler infrastructure",
    },
    {
        "name": "GCC",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Compiler collection",
    },
    {
        "name": "OpenSSL",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Cryptography library",
    },
    {
        "name": "OpenSSH",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Secure shell tools",
    },
    {
        "name": "FFmpeg",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Audio/video toolkit",
    },
    {
        "name": "Blender",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "3D creation suite",
    },
    {
        "name": "Godot Engine",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Game engine",
    },
    {
        "name": "React",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "UI library",
    },
    {
        "name": "Vue.js",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "UI framework",
    },
    {
        "name": "Angular",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Web framework",
    },
    {
        "name": "Node.js",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "JavaScript runtime",
    },
    {
        "name": "Deno",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "JavaScript/TypeScript runtime",
    },
    {
        "name": "VS Code",
        "entity_type": "open_source_project",
        "country_or_region": "International",
        "notes": "Code editor (Code - OSS base)",
    },
    {
        "name": "Python",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Java",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Kotlin",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "JavaScript",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "TypeScript",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "C",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "C++",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Rust",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Go",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Swift",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Objective-C",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "C#",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Ruby",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "PHP",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "R",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Julia",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Scala",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Lua",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "SQL",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Bash",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "PowerShell",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Haskell",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Erlang",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Elixir",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Dart",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "OCaml",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Perl",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Fortran",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "MATLAB",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "Assembly",
        "entity_type": "programming_language",
        "country_or_region": "International",
        "notes": "Programming language",
    },
    {
        "name": "ChatGPT",
        "entity_type": "software_product",
        "country_or_region": "International",
        "notes": "AI chatbot product",
    },
    {
        "name": "GPT-5",
        "entity_type": "software_model",
        "country_or_region": "International",
        "notes": "Large language model family name",
    },
    {
        "name": "GitHub",
        "entity_type": "platform",
        "country_or_region": "International",
        "notes": "Software hosting and collaboration",
    },
    {
        "name": "Git",
        "entity_type": "tool",
        "country_or_region": "International",
        "notes": "Version control system",
    },
    {
        "name": "CUDA",
        "entity_type": "technology",
        "country_or_region": "International",
        "notes": "NVIDIA parallel computing platform",
    },
    {
        "name": "OpenCL",
        "entity_type": "technology",
        "country_or_region": "International",
        "notes": "Parallel computing standard",
    },
    {
        "name": "ARM architecture",
        "entity_type": "technology",
        "country_or_region": "International",
        "notes": "CPU instruction set architecture",
    },
    {
        "name": "RISC-V",
        "entity_type": "technology",
        "country_or_region": "International",
        "notes": "Open standard instruction set architecture",
    },
    {
        "name": "Wi‑Fi",
        "entity_type": "technology",
        "country_or_region": "International",
        "notes": "Wireless networking standard",
    },
    {
        "name": "5G",
        "entity_type": "technology",
        "country_or_region": "International",
        "notes": "Mobile network generation",
    },
]
