from synthnews.prompts import Entity


ENTITIES: list[Entity] = [
    {
        "name": "FIFA",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "World governing body for association football (soccer)",
    },
    {
        "name": "UEFA",
        "entity_type": "sporting_authority",
        "country_or_region": "Europe",
        "notes": "Union of European Football Associations",
    },
    {
        "name": "CONCACAF",
        "entity_type": "sporting_authority",
        "country_or_region": "North America / Central America / Caribbean",
        "notes": "Regional football confederation",
    },
    {
        "name": "CONMEBOL",
        "entity_type": "sporting_authority",
        "country_or_region": "South America",
        "notes": "South American football confederation",
    },
    {
        "name": "AFC",
        "entity_type": "sporting_authority",
        "country_or_region": "Asia",
        "notes": "Asian Football Confederation",
    },
    {
        "name": "CAF",
        "entity_type": "sporting_authority",
        "country_or_region": "Africa",
        "notes": "Confederation of African Football",
    },
    {
        "name": "OFC",
        "entity_type": "sporting_authority",
        "country_or_region": "Oceania",
        "notes": "Oceania Football Confederation",
    },
    {
        "name": "IFAB",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "International Football Association Board (Laws of the Game)",
    },
    {
        "name": "International Olympic Committee (IOC)",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "Governing body of the Olympic Movement",
    },
    {
        "name": "World Anti-Doping Agency (WADA)",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "Global anti-doping organization",
    },
    {
        "name": "Court of Arbitration for Sport (CAS)",
        "entity_type": "sporting_authority",
        "country_or_region": "Switzerland / International",
        "notes": "Sports dispute resolution court",
    },
    {
        "name": "Fédération Internationale de l'Automobile (FIA)",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "Governing body for many motorsport categories incl. F1",
    },
    {
        "name": "World Athletics",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "Governing body for athletics/track and field",
    },
    {
        "name": "World Rugby",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "Governing body for rugby union",
    },
    {
        "name": "International Cricket Council (ICC)",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "Governing body for cricket",
    },
    {
        "name": "International Ice Hockey Federation (IIHF)",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "Governing body for ice hockey",
    },
    {
        "name": "FIBA",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "International Basketball Federation",
    },
    {
        "name": "ATP Tour",
        "entity_type": "league",
        "country_or_region": "International",
        "notes": "Men's professional tennis tour",
    },
    {
        "name": "WTA",
        "entity_type": "league",
        "country_or_region": "International",
        "notes": "Women's professional tennis tour",
    },
    {
        "name": "ITF",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "International Tennis Federation",
    },
    {
        "name": "UCI",
        "entity_type": "sporting_authority",
        "country_or_region": "International",
        "notes": "Union Cycliste Internationale; cycling governing body",
    },
    {
        "name": "PGA Tour",
        "entity_type": "league",
        "country_or_region": "United States / International",
        "notes": "Men's professional golf tour",
    },
    {
        "name": "LPGA",
        "entity_type": "league",
        "country_or_region": "United States / International",
        "notes": "Women's professional golf tour",
    },
    {
        "name": "NCAA",
        "entity_type": "sporting_authority",
        "country_or_region": "United States",
        "notes": "National Collegiate Athletic Association",
    },
    {
        "name": "National Football League (NFL)",
        "entity_type": "league",
        "country_or_region": "United States",
        "notes": "Major professional American football league",
    },
    {
        "name": "National Basketball Association (NBA)",
        "entity_type": "league",
        "country_or_region": "United States / Canada",
        "notes": "Major professional basketball league",
    },
    {
        "name": "National Hockey League (NHL)",
        "entity_type": "league",
        "country_or_region": "United States / Canada",
        "notes": "Major professional ice hockey league",
    },
    {
        "name": "Major League Baseball (MLB)",
        "entity_type": "league",
        "country_or_region": "United States / Canada",
        "notes": "Major professional baseball league",
    },
    {
        "name": "Major League Soccer (MLS)",
        "entity_type": "league",
        "country_or_region": "United States / Canada",
        "notes": "Top-tier professional soccer league in US/Canada",
    },
    {
        "name": "Canadian Football League (CFL)",
        "entity_type": "league",
        "country_or_region": "Canada",
        "notes": "Professional Canadian football league",
    },
    {
        "name": "English Football League (EFL)",
        "entity_type": "league",
        "country_or_region": "United Kingdom",
        "notes": "English league system below Premier League",
    },
    {
        "name": "Premier League",
        "entity_type": "league",
        "country_or_region": "United Kingdom",
        "notes": "Top-tier English football league",
    },
    {
        "name": "LaLiga",
        "entity_type": "league",
        "country_or_region": "Spain",
        "notes": "Top-tier Spanish football league",
    },
    {
        "name": "Bundesliga",
        "entity_type": "league",
        "country_or_region": "Germany",
        "notes": "Top-tier German football league",
    },
    {
        "name": "Serie A",
        "entity_type": "league",
        "country_or_region": "Italy",
        "notes": "Top-tier Italian football league",
    },
    {
        "name": "Ligue 1",
        "entity_type": "league",
        "country_or_region": "France",
        "notes": "Top-tier French football league",
    },
    {
        "name": "NHL Players' Association (NHLPA)",
        "entity_type": "labor_union",
        "country_or_region": "United States / Canada",
        "notes": "Players' labor union/association for NHL players",
    },
    {
        "name": "National Basketball Players Association (NBPA)",
        "entity_type": "labor_union",
        "country_or_region": "United States",
        "notes": "Players' labor union for NBA players",
    },
    {
        "name": "Major League Baseball Players Association (MLBPA)",
        "entity_type": "labor_union",
        "country_or_region": "United States / Canada",
        "notes": "Players' labor union for MLB players",
    },
    {
        "name": "National Football League Players Association (NFLPA)",
        "entity_type": "labor_union",
        "country_or_region": "United States",
        "notes": "Players' labor union for NFL players",
    },
    {
        "name": "NWSL",
        "entity_type": "league",
        "country_or_region": "United States",
        "notes": "Sports league/promotion",
    },
    {
        "name": "WNBA",
        "entity_type": "league",
        "country_or_region": "United States",
        "notes": "Sports league/promotion",
    },
    {
        "name": "Liga MX",
        "entity_type": "league",
        "country_or_region": "Mexico",
        "notes": "Sports league/promotion",
    },
    {
        "name": "Brasileirão Série A",
        "entity_type": "league",
        "country_or_region": "Brazil",
        "notes": "Sports league/promotion",
    },
    {
        "name": "Argentine Primera División",
        "entity_type": "league",
        "country_or_region": "Argentina",
        "notes": "Sports league/promotion",
    },
    {
        "name": "Scottish Premiership",
        "entity_type": "league",
        "country_or_region": "United Kingdom (Scotland)",
        "notes": "Sports league/promotion",
    },
    {
        "name": "Eredivisie",
        "entity_type": "league",
        "country_or_region": "Netherlands",
        "notes": "Sports league/promotion",
    },
    {
        "name": "Primeira Liga",
        "entity_type": "league",
        "country_or_region": "Portugal",
        "notes": "Sports league/promotion",
    },
    {
        "name": "Saudi Pro League",
        "entity_type": "league",
        "country_or_region": "Saudi Arabia",
        "notes": "Sports league/promotion",
    },
    {
        "name": "J1 League",
        "entity_type": "league",
        "country_or_region": "Japan",
        "notes": "Sports league/promotion",
    },
    {
        "name": "K League 1",
        "entity_type": "league",
        "country_or_region": "South Korea",
        "notes": "Sports league/promotion",
    },
    {
        "name": "UFC",
        "entity_type": "league",
        "country_or_region": "United States / International",
        "notes": "Sports league/promotion",
    },
    {
        "name": "Bellator MMA",
        "entity_type": "league",
        "country_or_region": "United States / International",
        "notes": "Sports league/promotion",
    },
    {
        "name": "WWE",
        "entity_type": "league",
        "country_or_region": "United States / International",
        "notes": "Sports league/promotion",
    },
    {
        "name": "Olympic Games",
        "entity_type": "multi_sport_event",
        "country_or_region": "International",
        "notes": "Major recurring multi-sport event",
    },
    {
        "name": "Summer Olympic Games",
        "entity_type": "multi_sport_event",
        "country_or_region": "International",
        "notes": "Major recurring multi-sport event",
    },
    {
        "name": "Winter Olympic Games",
        "entity_type": "multi_sport_event",
        "country_or_region": "International",
        "notes": "Major recurring multi-sport event",
    },
    {
        "name": "Paralympic Games",
        "entity_type": "multi_sport_event",
        "country_or_region": "International",
        "notes": "Major recurring multi-sport event",
    },
    {
        "name": "FIFA World Cup",
        "entity_type": "tournament",
        "country_or_region": "International",
        "notes": "Major international football tournament",
    },
    {
        "name": "FIFA Women's World Cup",
        "entity_type": "tournament",
        "country_or_region": "International",
        "notes": "Major international football tournament",
    },
    {
        "name": "UEFA Champions League",
        "entity_type": "tournament",
        "country_or_region": "Europe",
        "notes": "Major club football tournament",
    },
    {
        "name": "UEFA Europa League",
        "entity_type": "tournament",
        "country_or_region": "Europe",
        "notes": "Major club football tournament",
    },
    {
        "name": "UEFA European Championship (UEFA Euro)",
        "entity_type": "tournament",
        "country_or_region": "Europe",
        "notes": "Major international football tournament",
    },
    {
        "name": "Copa América",
        "entity_type": "tournament",
        "country_or_region": "South America",
        "notes": "Major international football tournament",
    },
    {
        "name": "CONCACAF Gold Cup",
        "entity_type": "tournament",
        "country_or_region": "North America / Central America / Caribbean",
        "notes": "Regional football championship",
    },
    {
        "name": "Africa Cup of Nations (AFCON)",
        "entity_type": "tournament",
        "country_or_region": "Africa",
        "notes": "Major international football tournament",
    },
    {
        "name": "AFC Asian Cup",
        "entity_type": "tournament",
        "country_or_region": "Asia",
        "notes": "Major international football tournament",
    },
    {
        "name": "Super Bowl",
        "entity_type": "championship",
        "country_or_region": "United States",
        "notes": "NFL championship game",
    },
    {
        "name": "Stanley Cup",
        "entity_type": "championship",
        "country_or_region": "United States / Canada",
        "notes": "NHL championship trophy/playoffs",
    },
    {
        "name": "World Series",
        "entity_type": "championship",
        "country_or_region": "United States / Canada",
        "notes": "MLB championship series",
    },
    {
        "name": "NBA Finals",
        "entity_type": "championship",
        "country_or_region": "United States / Canada",
        "notes": "NBA championship series",
    },
    {
        "name": "NHL Winter Classic",
        "entity_type": "sporting_event",
        "country_or_region": "United States / Canada",
        "notes": "Outdoor NHL regular-season game event",
    },
    {
        "name": "March Madness",
        "entity_type": "tournament",
        "country_or_region": "United States",
        "notes": "NCAA men's basketball tournament",
    },
    {
        "name": "College Football Playoff",
        "entity_type": "tournament",
        "country_or_region": "United States",
        "notes": "Postseason college football championship format",
    },
    {
        "name": "The Masters",
        "entity_type": "tournament",
        "country_or_region": "United States",
        "notes": "Major golf tournament at Augusta National",
    },
    {
        "name": "PGA Championship",
        "entity_type": "tournament",
        "country_or_region": "United States",
        "notes": "Major golf tournament",
    },
    {
        "name": "U.S. Open (Golf)",
        "entity_type": "tournament",
        "country_or_region": "United States",
        "notes": "Major golf tournament",
    },
    {
        "name": "The Open Championship",
        "entity_type": "tournament",
        "country_or_region": "United Kingdom",
        "notes": "Major golf tournament",
    },
    {
        "name": "Wimbledon",
        "entity_type": "tournament",
        "country_or_region": "United Kingdom",
        "notes": "Grand Slam tennis tournament",
    },
    {
        "name": "Roland-Garros (French Open)",
        "entity_type": "tournament",
        "country_or_region": "France",
        "notes": "Grand Slam tennis tournament",
    },
    {
        "name": "US Open (Tennis)",
        "entity_type": "tournament",
        "country_or_region": "United States",
        "notes": "Grand Slam tennis tournament",
    },
    {
        "name": "Australian Open",
        "entity_type": "tournament",
        "country_or_region": "Australia",
        "notes": "Grand Slam tennis tournament",
    },
    {
        "name": "Tour de France",
        "entity_type": "sporting_event",
        "country_or_region": "France / International",
        "notes": "Major cycling stage race",
    },
    {
        "name": "Giro d'Italia",
        "entity_type": "sporting_event",
        "country_or_region": "Italy",
        "notes": "Major cycling stage race",
    },
    {
        "name": "Vuelta a España",
        "entity_type": "sporting_event",
        "country_or_region": "Spain",
        "notes": "Major cycling stage race",
    },
    {
        "name": "Formula 1 Monaco Grand Prix",
        "entity_type": "sporting_event",
        "country_or_region": "Monaco",
        "notes": "F1 race weekend event",
    },
    {
        "name": "Formula 1 British Grand Prix",
        "entity_type": "sporting_event",
        "country_or_region": "United Kingdom",
        "notes": "F1 race weekend event",
    },
    {
        "name": "Formula 1 Italian Grand Prix",
        "entity_type": "sporting_event",
        "country_or_region": "Italy",
        "notes": "F1 race weekend event",
    },
    {
        "name": "Indianapolis 500",
        "entity_type": "sporting_event",
        "country_or_region": "United States",
        "notes": "Major motorsport race",
    },
    {
        "name": "Daytona 500",
        "entity_type": "sporting_event",
        "country_or_region": "United States",
        "notes": "Major motorsport race",
    },
    {
        "name": "24 Hours of Le Mans",
        "entity_type": "sporting_event",
        "country_or_region": "France",
        "notes": "Major endurance race",
    },
    {
        "name": "Rugby World Cup",
        "entity_type": "tournament",
        "country_or_region": "International",
        "notes": "Major rugby union tournament",
    },
    {
        "name": "Cricket World Cup",
        "entity_type": "tournament",
        "country_or_region": "International",
        "notes": "Major cricket tournament",
    },
    {
        "name": "ICC Men's T20 World Cup",
        "entity_type": "tournament",
        "country_or_region": "International",
        "notes": "Major cricket tournament",
    },
    {
        "name": "Six Nations Championship",
        "entity_type": "tournament",
        "country_or_region": "Europe",
        "notes": "Annual rugby union tournament",
    },
    {
        "name": "UEFA Nations League",
        "entity_type": "tournament",
        "country_or_region": "Europe",
        "notes": "International football tournament",
    },
    {
        "name": "Nike",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Adidas",
        "entity_type": "brand",
        "country_or_region": "Germany",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Puma",
        "entity_type": "brand",
        "country_or_region": "Germany",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Under Armour",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "New Balance",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Reebok",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "ASICS",
        "entity_type": "brand",
        "country_or_region": "Japan",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Lululemon",
        "entity_type": "brand",
        "country_or_region": "Canada",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Fanatics",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "New Era",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Wilson Sporting Goods",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Spalding",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Rawlings",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Bauer Hockey",
        "entity_type": "brand",
        "country_or_region": "Canada",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "CCM Hockey",
        "entity_type": "brand",
        "country_or_region": "Canada",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Titleist",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Callaway",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "TaylorMade",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Oakley",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Garmin",
        "entity_type": "brand",
        "country_or_region": "United States",
        "notes": "Sports brand / equipment / apparel",
    },
    {
        "name": "Madison Square Garden",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "New York City; NBA/NHL arena",
    },
    {
        "name": "Yankee Stadium",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "New York City; MLB",
    },
    {
        "name": "Fenway Park",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "Boston; MLB",
    },
    {
        "name": "Wrigley Field",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "Chicago; MLB",
    },
    {
        "name": "Lambeau Field",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "Green Bay; NFL",
    },
    {
        "name": "AT&T Stadium",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "Arlington; NFL",
    },
    {
        "name": "SoFi Stadium",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "Inglewood; NFL",
    },
    {
        "name": "MetLife Stadium",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "East Rutherford; NFL",
    },
    {
        "name": "Allegiant Stadium",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "Las Vegas; NFL",
    },
    {
        "name": "TD Garden",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "Boston; NBA/NHL",
    },
    {
        "name": "Crypto.com Arena",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "Los Angeles; NBA/NHL",
    },
    {
        "name": "United Center",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United States",
        "notes": "Chicago; NBA/NHL",
    },
    {
        "name": "Scotiabank Arena",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Canada",
        "notes": "Toronto; NBA/NHL",
    },
    {
        "name": "Bell Centre",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Canada",
        "notes": "Montreal; NHL",
    },
    {
        "name": "Rogers Centre",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Canada",
        "notes": "Toronto; MLB",
    },
    {
        "name": "BC Place",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Canada",
        "notes": "Vancouver; CFL/MLS events",
    },
    {
        "name": "Wembley Stadium",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United Kingdom",
        "notes": "London; major football finals",
    },
    {
        "name": "Emirates Stadium",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United Kingdom",
        "notes": "London; Arsenal",
    },
    {
        "name": "Old Trafford",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United Kingdom",
        "notes": "Manchester; Manchester United",
    },
    {
        "name": "Anfield",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United Kingdom",
        "notes": "Liverpool; Liverpool FC",
    },
    {
        "name": "Tottenham Hotspur Stadium",
        "entity_type": "stadium_or_arena",
        "country_or_region": "United Kingdom",
        "notes": "London; Spurs",
    },
    {
        "name": "Santiago Bernabéu",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Spain",
        "notes": "Madrid; Real Madrid",
    },
    {
        "name": "Camp Nou",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Spain",
        "notes": "Barcelona; FC Barcelona",
    },
    {
        "name": "Allianz Arena",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Germany",
        "notes": "Munich; FC Bayern",
    },
    {
        "name": "Signal Iduna Park",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Germany",
        "notes": "Dortmund; Borussia Dortmund",
    },
    {
        "name": "San Siro",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Italy",
        "notes": "Milan; Inter/AC Milan",
    },
    {
        "name": "Stadio Olimpico",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Italy",
        "notes": "Rome; Roma/Lazio",
    },
    {
        "name": "Stade de France",
        "entity_type": "stadium_or_arena",
        "country_or_region": "France",
        "notes": "Paris area; national stadium",
    },
    {
        "name": "Parc des Princes",
        "entity_type": "stadium_or_arena",
        "country_or_region": "France",
        "notes": "Paris; PSG",
    },
    {
        "name": "Maracanã Stadium",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Brazil",
        "notes": "Rio de Janeiro; major football venue",
    },
    {
        "name": "Estadio Azteca",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Mexico",
        "notes": "Mexico City; major football venue",
    },
    {
        "name": "Melbourne Cricket Ground (MCG)",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Australia",
        "notes": "Melbourne; cricket/AFL",
    },
    {
        "name": "Sydney Cricket Ground (SCG)",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Australia",
        "notes": "Sydney; cricket",
    },
    {
        "name": "Tokyo Dome",
        "entity_type": "stadium_or_arena",
        "country_or_region": "Japan",
        "notes": "Tokyo; baseball",
    },
    {
        "name": "Anaheim Ducks",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Boston Bruins",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Buffalo Sabres",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Calgary Flames",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "NHL team",
    },
    {
        "name": "Carolina Hurricanes",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Chicago Blackhawks",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Colorado Avalanche",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Columbus Blue Jackets",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Dallas Stars",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Detroit Red Wings",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Edmonton Oilers",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "NHL team",
    },
    {
        "name": "Florida Panthers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Los Angeles Kings",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Minnesota Wild",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Montreal Canadiens",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "NHL team",
    },
    {
        "name": "Nashville Predators",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "New Jersey Devils",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "New York Islanders",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "New York Rangers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Ottawa Senators",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "NHL team",
    },
    {
        "name": "Philadelphia Flyers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Pittsburgh Penguins",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "San Jose Sharks",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Seattle Kraken",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "St. Louis Blues",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Tampa Bay Lightning",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Toronto Maple Leafs",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "NHL team",
    },
    {
        "name": "Vancouver Canucks",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "NHL team",
    },
    {
        "name": "Vegas Golden Knights",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Washington Capitals",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NHL team",
    },
    {
        "name": "Winnipeg Jets",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "NHL team",
    },
    {
        "name": "Arizona Cardinals",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Atlanta Falcons",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Baltimore Ravens",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Buffalo Bills",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Carolina Panthers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Chicago Bears",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Cincinnati Bengals",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Cleveland Browns",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Dallas Cowboys",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Denver Broncos",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Detroit Lions",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Green Bay Packers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Houston Texans",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Indianapolis Colts",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Jacksonville Jaguars",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Kansas City Chiefs",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Las Vegas Raiders",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Los Angeles Chargers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Los Angeles Rams",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Miami Dolphins",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Minnesota Vikings",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "New England Patriots",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "New Orleans Saints",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "New York Giants",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "New York Jets",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Philadelphia Eagles",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Pittsburgh Steelers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "San Francisco 49ers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Seattle Seahawks",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Tampa Bay Buccaneers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Tennessee Titans",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Washington Commanders",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NFL team",
    },
    {
        "name": "Atlanta Hawks",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Boston Celtics",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Brooklyn Nets",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Charlotte Hornets",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Chicago Bulls",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Cleveland Cavaliers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Dallas Mavericks",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Denver Nuggets",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Detroit Pistons",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Golden State Warriors",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Houston Rockets",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Indiana Pacers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Los Angeles Clippers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Los Angeles Lakers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Memphis Grizzlies",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Miami Heat",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Milwaukee Bucks",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Minnesota Timberwolves",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "New Orleans Pelicans",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "New York Knicks",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Oklahoma City Thunder",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Orlando Magic",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Philadelphia 76ers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Phoenix Suns",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Portland Trail Blazers",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Sacramento Kings",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "San Antonio Spurs",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Toronto Raptors",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "NBA team",
    },
    {
        "name": "Utah Jazz",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Washington Wizards",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "NBA team",
    },
    {
        "name": "Real Madrid CF",
        "entity_type": "team",
        "country_or_region": "Spain",
        "notes": "Professional football club",
    },
    {
        "name": "FC Barcelona",
        "entity_type": "team",
        "country_or_region": "Spain",
        "notes": "Professional football club",
    },
    {
        "name": "Atlético Madrid",
        "entity_type": "team",
        "country_or_region": "Spain",
        "notes": "Professional football club",
    },
    {
        "name": "Manchester United",
        "entity_type": "team",
        "country_or_region": "United Kingdom",
        "notes": "Professional football club",
    },
    {
        "name": "Liverpool FC",
        "entity_type": "team",
        "country_or_region": "United Kingdom",
        "notes": "Professional football club",
    },
    {
        "name": "Manchester City",
        "entity_type": "team",
        "country_or_region": "United Kingdom",
        "notes": "Professional football club",
    },
    {
        "name": "Arsenal FC",
        "entity_type": "team",
        "country_or_region": "United Kingdom",
        "notes": "Professional football club",
    },
    {
        "name": "Chelsea FC",
        "entity_type": "team",
        "country_or_region": "United Kingdom",
        "notes": "Professional football club",
    },
    {
        "name": "Tottenham Hotspur",
        "entity_type": "team",
        "country_or_region": "United Kingdom",
        "notes": "Professional football club",
    },
    {
        "name": "Bayern Munich",
        "entity_type": "team",
        "country_or_region": "Germany",
        "notes": "Professional football club",
    },
    {
        "name": "Borussia Dortmund",
        "entity_type": "team",
        "country_or_region": "Germany",
        "notes": "Professional football club",
    },
    {
        "name": "RB Leipzig",
        "entity_type": "team",
        "country_or_region": "Germany",
        "notes": "Professional football club",
    },
    {
        "name": "Juventus",
        "entity_type": "team",
        "country_or_region": "Italy",
        "notes": "Professional football club",
    },
    {
        "name": "AC Milan",
        "entity_type": "team",
        "country_or_region": "Italy",
        "notes": "Professional football club",
    },
    {
        "name": "Inter Milan",
        "entity_type": "team",
        "country_or_region": "Italy",
        "notes": "Professional football club",
    },
    {
        "name": "AS Roma",
        "entity_type": "team",
        "country_or_region": "Italy",
        "notes": "Professional football club",
    },
    {
        "name": "Paris Saint-Germain (PSG)",
        "entity_type": "team",
        "country_or_region": "France",
        "notes": "Professional football club",
    },
    {
        "name": "Olympique Marseille",
        "entity_type": "team",
        "country_or_region": "France",
        "notes": "Professional football club",
    },
    {
        "name": "Ajax",
        "entity_type": "team",
        "country_or_region": "Netherlands",
        "notes": "Professional football club",
    },
    {
        "name": "PSV Eindhoven",
        "entity_type": "team",
        "country_or_region": "Netherlands",
        "notes": "Professional football club",
    },
    {
        "name": "FC Porto",
        "entity_type": "team",
        "country_or_region": "Portugal",
        "notes": "Professional football club",
    },
    {
        "name": "SL Benfica",
        "entity_type": "team",
        "country_or_region": "Portugal",
        "notes": "Professional football club",
    },
    {
        "name": "Celtic FC",
        "entity_type": "team",
        "country_or_region": "United Kingdom (Scotland)",
        "notes": "Professional football club",
    },
    {
        "name": "Rangers FC",
        "entity_type": "team",
        "country_or_region": "United Kingdom (Scotland)",
        "notes": "Professional football club",
    },
    {
        "name": "Al Hilal",
        "entity_type": "team",
        "country_or_region": "Saudi Arabia",
        "notes": "Professional football club",
    },
    {
        "name": "Al Nassr",
        "entity_type": "team",
        "country_or_region": "Saudi Arabia",
        "notes": "Professional football club",
    },
    {
        "name": "LA Galaxy",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "Professional football club",
    },
    {
        "name": "Inter Miami CF",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "Professional football club",
    },
    {
        "name": "Seattle Sounders FC",
        "entity_type": "team",
        "country_or_region": "United States",
        "notes": "Professional football club",
    },
    {
        "name": "Toronto FC",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "Professional football club",
    },
    {
        "name": "CF Montréal",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "Professional football club",
    },
    {
        "name": "Vancouver Whitecaps FC",
        "entity_type": "team",
        "country_or_region": "Canada",
        "notes": "Professional football club",
    },
]
